/*
 * ge_anim_offsets.h -- ANIM_DATA_* are OFFSETS, not objects.
 *
 * GENERATED by tools/gen_anim_offsets.py. Do not edit.
 *
 * On the N64 these live in the animation_data segment, whose VRAM base is 0, so
 * a symbol's ADDRESS is its offset within the segment. That is how the game uses
 * them -- never as data:
 *
 *     modelSetAnimation(m, &ptr_animation_table->data[(s32)&ANIM_DATA_idle], ...)
 *
 * The segment itself is loaded whole and separately, by
 * alloc_load_expand_ani_table():
 *
 *     romCopy(ptr_animation_table, &_animation_dataSegmentRomStart, size);
 *
 * So the CONTENT of these symbols is never read through the symbol. Defining
 * them as arrays -- which is what a host link does when it finds them undefined
 * -- puts them at host addresses around 0x20000000, and that subscript then
 * runs half a gigabyte past the end of a 0xFFFF-byte table.
 *
 * Same technique as hostcompat/ge_segments_compat.h: a macro naming the byte AT
 * the offset, so `&NAME` is the offset and every use site works unchanged. The
 * decomp's `extern` declarations are guarded, because a macro and a declaration
 * of the same name cannot coexist.
 *
 * animation_data: VRAM 0x00000000..0x0000E7E0, ROM 0x0028E980..0x0029D160 (1:1).
 */
#ifndef GE_ANIM_OFFSETS_H
#define GE_ANIM_OFFSETS_H

#define ANIM_DATA_idle (*(s32 *)(unsigned long)0x0000001Cu)
#define ANIM_DATA_fire_hip (*(s32 *)(unsigned long)0x00000318u)
#define ANIM_DATA_fire_kneel_left_leg (*(s32 *)(unsigned long)0x00000B84u)
#define ANIM_DATA_death_neck (*(s32 *)(unsigned long)0x00002E64u)
#define ANIM_DATA_death_stagger_back_to_wall (*(s32 *)(unsigned long)0x00002F94u)
#define ANIM_DATA_side_step_left (*(s32 *)(unsigned long)0x00003D9Cu)
#define ANIM_DATA_walking (*(s32 *)(unsigned long)0x00004018u)
#define ANIM_DATA_sprinting (*(s32 *)(unsigned long)0x00004070u)
#define ANIM_DATA_running (*(s32 *)(unsigned long)0x000040D4u)
#define ANIM_DATA_bond_eye_walk (*(s32 *)(unsigned long)0x00004144u)
#define ANIM_DATA_bond_eye_fire (*(s32 *)(unsigned long)0x00004298u)
#define ANIM_DATA_bond_watch (*(s32 *)(unsigned long)0x000042C8u)
#define ANIM_DATA_surrendering_armed (*(s32 *)(unsigned long)0x00004384u)
#define ANIM_DATA_surrendering_armed_drop_weapon (*(s32 *)(unsigned long)0x00004504u)
#define ANIM_DATA_fire_jump_to_side_left (*(s32 *)(unsigned long)0x000047BCu)
#define ANIM_DATA_fire_jump_to_side_right (*(s32 *)(unsigned long)0x00004A40u)
#define ANIM_DATA_hit_butt_long (*(s32 *)(unsigned long)0x00004CE0u)
#define ANIM_DATA_hit_butt_short (*(s32 *)(unsigned long)0x00004F14u)
#define ANIM_DATA_death_left_leg (*(s32 *)(unsigned long)0x0000540Cu)
#define ANIM_DATA_slide_right (*(s32 *)(unsigned long)0x000054A0u)
#define ANIM_DATA_slide_left (*(s32 *)(unsigned long)0x00005554u)
#define ANIM_DATA_jump_backwards (*(s32 *)(unsigned long)0x00005684u)
#define ANIM_DATA_extending_left_hand (*(s32 *)(unsigned long)0x00005744u)
#define ANIM_DATA_fire_throw_grenade (*(s32 *)(unsigned long)0x00005964u)
#define ANIM_DATA_spotting_bond (*(s32 *)(unsigned long)0x00005D10u)
#define ANIM_DATA_look_around (*(s32 *)(unsigned long)0x00005EF0u)
#define ANIM_DATA_fire_standing_draw_one_handed_weapon_fast (*(s32 *)(unsigned long)0x00006254u)
#define ANIM_DATA_fire_kneel_forward_one_handed_weapon_slow (*(s32 *)(unsigned long)0x00006C18u)
#define ANIM_DATA_running_one_handed_weapon (*(s32 *)(unsigned long)0x0000777Cu)
#define ANIM_DATA_sprinting_one_handed_weapon (*(s32 *)(unsigned long)0x000077D4u)
#define ANIM_DATA_idle_unarmed (*(s32 *)(unsigned long)0x00008194u)
#define ANIM_DATA_walking_unarmed (*(s32 *)(unsigned long)0x00008204u)
#define ANIM_DATA_walking_female (*(s32 *)(unsigned long)0x000084C4u)
#define ANIM_DATA_running_female (*(s32 *)(unsigned long)0x00008520u)
#define ANIM_DATA_sneeze (*(s32 *)(unsigned long)0x0000B9A8u)

#endif /* GE_ANIM_OFFSETS_H */
