/*
 * ge_segments_compat.h — host stand-ins for the linker's *Segment* symbols.
 *
 * The game declares these as ordinary externs and only ever takes their
 * ADDRESS:
 *
 *     romCopy(dst, &_animation_dataSegmentRomStart, size);
 *     size = (u32)&_fontdlSegmentRomEnd - (u32)&_fontdlSegmentRomStart;
 *
 * On N64 the linker gives each one an absolute value — a ROM byte offset, or a
 * RDRAM/TLB virtual address. A host toolchain cannot place an ordinary symbol
 * at a chosen address, and on Windows there is no portable way to define an
 * absolute symbol at all.
 *
 * So each name becomes a macro naming the byte AT that address. Then `&name`
 * is the address itself and every existing use site works unchanged, with no
 * edits to the expressions that use them:
 *
 *     &_codeSegmentRomStart        ->  (unsigned char *)0x00001050
 *     (u32)&_codeSegmentRomStart   ->  0x00001050
 *
 * The dereference is never evaluated — only its address is taken — so this
 * points at nothing and reads nothing.
 *
 * CONSEQUENCE: the decomp's own `extern` declarations of these names must be
 * compiled out on the host path, because `extern u32 *(*(unsigned char *)0x1050);`
 * is not a declaration. Every such block is guarded with #ifdef TARGET_N64.
 *
 * GENERATED by tools/extract_segments.py — do not edit.
 */
#ifndef GE_SEGMENTS_COMPAT_H
#define GE_SEGMENTS_COMPAT_H

#include "ge_segments.h"

#define GE_SEG_AT(v) (*(unsigned char *)(unsigned long)(v))

#define _GlobalimagetableSegmentEnd GE_SEG_AT(GE_SEG__GlobalimagetableSegmentEnd)
#define _GlobalimagetableSegmentRomEnd GE_SEG_AT(GE_SEG__GlobalimagetableSegmentRomEnd)
#define _GlobalimagetableSegmentRomStart GE_SEG_AT(GE_SEG__GlobalimagetableSegmentRomStart)
#define _GlobalimagetableSegmentStart GE_SEG_AT(GE_SEG__GlobalimagetableSegmentStart)
#define __dataSegmentVaddrStart GE_SEG_AT(GE_SEG___dataSegmentVaddrStart)
#define _alt_startSegmentRomStart GE_SEG_AT(GE_SEG__alt_startSegmentRomStart)
#define _alt_startSegmentStart GE_SEG_AT(GE_SEG__alt_startSegmentStart)
#define _animation_dataSegmentEnd GE_SEG_AT(GE_SEG__animation_dataSegmentEnd)
#define _animation_dataSegmentRomEnd GE_SEG_AT(GE_SEG__animation_dataSegmentRomEnd)
#define _animation_dataSegmentRomStart GE_SEG_AT(GE_SEG__animation_dataSegmentRomStart)
#define _animation_dataSegmentStart GE_SEG_AT(GE_SEG__animation_dataSegmentStart)
#define _animation_entriesSegmentEnd GE_SEG_AT(GE_SEG__animation_entriesSegmentEnd)
#define _animation_entriesSegmentRomEnd GE_SEG_AT(GE_SEG__animation_entriesSegmentRomEnd)
#define _animation_entriesSegmentRomStart GE_SEG_AT(GE_SEG__animation_entriesSegmentRomStart)
#define _animation_entriesSegmentStart GE_SEG_AT(GE_SEG__animation_entriesSegmentStart)
#define _bootSegmentEnd GE_SEG_AT(GE_SEG__bootSegmentEnd)
#define _bootSegmentRomEnd GE_SEG_AT(GE_SEG__bootSegmentRomEnd)
#define _bootSegmentRomStart GE_SEG_AT(GE_SEG__bootSegmentRomStart)
#define _bootSegmentStart GE_SEG_AT(GE_SEG__bootSegmentStart)
#define _bssSegmentEnd GE_SEG_AT(GE_SEG__bssSegmentEnd)
#define _bssSegmentStart GE_SEG_AT(GE_SEG__bssSegmentStart)
#define _cdataSegmentEnd GE_SEG_AT(GE_SEG__cdataSegmentEnd)
#define _cdataSegmentRomEnd GE_SEG_AT(GE_SEG__cdataSegmentRomEnd)
#define _cdataSegmentRomStart GE_SEG_AT(GE_SEG__cdataSegmentRomStart)
#define _cdataSegmentStart GE_SEG_AT(GE_SEG__cdataSegmentStart)
#define _cfbSegmentEnd GE_SEG_AT(GE_SEG__cfbSegmentEnd)
#define _cfbSegmentStart GE_SEG_AT(GE_SEG__cfbSegmentStart)
#define _codeSegmentEnd GE_SEG_AT(GE_SEG__codeSegmentEnd)
#define _codeSegmentRomEnd GE_SEG_AT(GE_SEG__codeSegmentRomEnd)
#define _codeSegmentRomStart GE_SEG_AT(GE_SEG__codeSegmentRomStart)
#define _codeSegmentStart GE_SEG_AT(GE_SEG__codeSegmentStart)
#define _csegmentSegmentEnd GE_SEG_AT(GE_SEG__csegmentSegmentEnd)
#define _csegmentSegmentRomEnd GE_SEG_AT(GE_SEG__csegmentSegmentRomEnd)
#define _csegmentSegmentRomStart GE_SEG_AT(GE_SEG__csegmentSegmentRomStart)
#define _csegmentSegmentStart GE_SEG_AT(GE_SEG__csegmentSegmentStart)
#define _dataSegmentVaddrEnd GE_SEG_AT(GE_SEG__dataSegmentVaddrEnd)
#define _efontchardataSegmentEnd GE_SEG_AT(GE_SEG__efontchardataSegmentEnd)
#define _efontchardataSegmentRomEnd GE_SEG_AT(GE_SEG__efontchardataSegmentRomEnd)
#define _efontchardataSegmentRomStart GE_SEG_AT(GE_SEG__efontchardataSegmentRomStart)
#define _efontchardataSegmentStart GE_SEG_AT(GE_SEG__efontchardataSegmentStart)
#define _fontbankgothicSegmentEnd GE_SEG_AT(GE_SEG__fontbankgothicSegmentEnd)
#define _fontbankgothicSegmentRomEnd GE_SEG_AT(GE_SEG__fontbankgothicSegmentRomEnd)
#define _fontbankgothicSegmentRomStart GE_SEG_AT(GE_SEG__fontbankgothicSegmentRomStart)
#define _fontbankgothicSegmentStart GE_SEG_AT(GE_SEG__fontbankgothicSegmentStart)
#define _fontdlSegmentEnd GE_SEG_AT(GE_SEG__fontdlSegmentEnd)
#define _fontdlSegmentRomEnd GE_SEG_AT(GE_SEG__fontdlSegmentRomEnd)
#define _fontdlSegmentRomStart GE_SEG_AT(GE_SEG__fontdlSegmentRomStart)
#define _fontdlSegmentStart GE_SEG_AT(GE_SEG__fontdlSegmentStart)
#define _fontzurichboldSegmentEnd GE_SEG_AT(GE_SEG__fontzurichboldSegmentEnd)
#define _fontzurichboldSegmentRomEnd GE_SEG_AT(GE_SEG__fontzurichboldSegmentRomEnd)
#define _fontzurichboldSegmentRomStart GE_SEG_AT(GE_SEG__fontzurichboldSegmentRomStart)
#define _fontzurichboldSegmentStart GE_SEG_AT(GE_SEG__fontzurichboldSegmentStart)
#define _gameSegmentEnd GE_SEG_AT(GE_SEG__gameSegmentEnd)
#define _gameSegmentRomEnd GE_SEG_AT(GE_SEG__gameSegmentRomEnd)
#define _gameSegmentRomStart GE_SEG_AT(GE_SEG__gameSegmentRomStart)
#define _gameSegmentStart GE_SEG_AT(GE_SEG__gameSegmentStart)
#define _headerSegmentEnd GE_SEG_AT(GE_SEG__headerSegmentEnd)
#define _headerSegmentRomEnd GE_SEG_AT(GE_SEG__headerSegmentRomEnd)
#define _headerSegmentRomStart GE_SEG_AT(GE_SEG__headerSegmentRomStart)
#define _headerSegmentStart GE_SEG_AT(GE_SEG__headerSegmentStart)
#define _imagesSegmentEnd GE_SEG_AT(GE_SEG__imagesSegmentEnd)
#define _imagesSegmentRomEnd GE_SEG_AT(GE_SEG__imagesSegmentRomEnd)
#define _imagesSegmentRomStart GE_SEG_AT(GE_SEG__imagesSegmentRomStart)
#define _imagesSegmentStart GE_SEG_AT(GE_SEG__imagesSegmentStart)
#define _inflateSegmentEnd GE_SEG_AT(GE_SEG__inflateSegmentEnd)
#define _inflateSegmentRomEnd GE_SEG_AT(GE_SEG__inflateSegmentRomEnd)
#define _inflateSegmentRomStart GE_SEG_AT(GE_SEG__inflateSegmentRomStart)
#define _inflateSegmentStart GE_SEG_AT(GE_SEG__inflateSegmentStart)
#define _instrumentsctlSegmentRomEnd GE_SEG_AT(GE_SEG__instrumentsctlSegmentRomEnd)
#define _instrumentsctlSegmentRomStart GE_SEG_AT(GE_SEG__instrumentsctlSegmentRomStart)
#define _instrumentstblSegmentRomEnd GE_SEG_AT(GE_SEG__instrumentstblSegmentRomEnd)
#define _instrumentstblSegmentRomStart GE_SEG_AT(GE_SEG__instrumentstblSegmentRomStart)
#define _jfontchardataSegmentEnd GE_SEG_AT(GE_SEG__jfontchardataSegmentEnd)
#define _jfontchardataSegmentRomEnd GE_SEG_AT(GE_SEG__jfontchardataSegmentRomEnd)
#define _jfontchardataSegmentRomStart GE_SEG_AT(GE_SEG__jfontchardataSegmentRomStart)
#define _jfontchardataSegmentStart GE_SEG_AT(GE_SEG__jfontchardataSegmentStart)
#define _musicfilesSegmentEnd GE_SEG_AT(GE_SEG__musicfilesSegmentEnd)
#define _musicfilesSegmentRomEnd GE_SEG_AT(GE_SEG__musicfilesSegmentRomEnd)
#define _musicfilesSegmentRomStart GE_SEG_AT(GE_SEG__musicfilesSegmentRomStart)
#define _musicfilesSegmentStart GE_SEG_AT(GE_SEG__musicfilesSegmentStart)
#define _musicsampletblSegmentRomEnd GE_SEG_AT(GE_SEG__musicsampletblSegmentRomEnd)
#define _musicsampletblSegmentRomStart GE_SEG_AT(GE_SEG__musicsampletblSegmentRomStart)
#define _obsegSegmentEnd GE_SEG_AT(GE_SEG__obsegSegmentEnd)
#define _obsegSegmentRomEnd GE_SEG_AT(GE_SEG__obsegSegmentRomEnd)
#define _obsegSegmentRomStart GE_SEG_AT(GE_SEG__obsegSegmentRomStart)
#define _obsegSegmentStart GE_SEG_AT(GE_SEG__obsegSegmentStart)
#define _ramromDam1SegmentRomStart GE_SEG_AT(GE_SEG__ramromDam1SegmentRomStart)
#define _ramromfilesSegmentEnd GE_SEG_AT(GE_SEG__ramromfilesSegmentEnd)
#define _ramromfilesSegmentRomEnd GE_SEG_AT(GE_SEG__ramromfilesSegmentRomEnd)
#define _ramromfilesSegmentRomStart GE_SEG_AT(GE_SEG__ramromfilesSegmentRomStart)
#define _ramromfilesSegmentStart GE_SEG_AT(GE_SEG__ramromfilesSegmentStart)
#define _rarewarelogoSegmentEnd GE_SEG_AT(GE_SEG__rarewarelogoSegmentEnd)
#define _rarewarelogoSegmentRomEnd GE_SEG_AT(GE_SEG__rarewarelogoSegmentRomEnd)
#define _rarewarelogoSegmentRomStart GE_SEG_AT(GE_SEG__rarewarelogoSegmentRomStart)
#define _rarewarelogoSegmentStart GE_SEG_AT(GE_SEG__rarewarelogoSegmentStart)
#define _romSegmentEnd GE_SEG_AT(GE_SEG__romSegmentEnd)
#define _romSegmentStart GE_SEG_AT(GE_SEG__romSegmentStart)
#define _romfiles2SegmentEnd GE_SEG_AT(GE_SEG__romfiles2SegmentEnd)
#define _romfiles2SegmentRomEnd GE_SEG_AT(GE_SEG__romfiles2SegmentRomEnd)
#define _romfiles2SegmentRomStart GE_SEG_AT(GE_SEG__romfiles2SegmentRomStart)
#define _romfiles2SegmentStart GE_SEG_AT(GE_SEG__romfiles2SegmentStart)
#define _sfxctlSegmentRomEnd GE_SEG_AT(GE_SEG__sfxctlSegmentRomEnd)
#define _sfxctlSegmentRomStart GE_SEG_AT(GE_SEG__sfxctlSegmentRomStart)
#define _sfxtblSegmentRomEnd GE_SEG_AT(GE_SEG__sfxtblSegmentRomEnd)
#define _sfxtblSegmentRomStart GE_SEG_AT(GE_SEG__sfxtblSegmentRomStart)
#define _stacksSegmentEnd GE_SEG_AT(GE_SEG__stacksSegmentEnd)
#define _stacksSegmentStart GE_SEG_AT(GE_SEG__stacksSegmentStart)
#define _startSegmentEnd GE_SEG_AT(GE_SEG__startSegmentEnd)
#define _startSegmentRomEnd GE_SEG_AT(GE_SEG__startSegmentRomEnd)
#define _startSegmentRomStart GE_SEG_AT(GE_SEG__startSegmentRomStart)
#define _startSegmentStart GE_SEG_AT(GE_SEG__startSegmentStart)

#endif /* GE_SEGMENTS_COMPAT_H */
