/*
 * ge_segsym_offsets.h -- segment-relative symbols are OFFSETS, not objects.
 *
 * GENERATED by tools/gen_segsym_offsets.py. Do not edit.
 *
 * Five of the ROM's segments have a VRAM base that is not their cartridge
 * position. A symbol in one of those has an address that is meaningful only
 * RELATIVE to where the segment gets loaded, and the game uses it exactly that
 * way -- never as data:
 *
 *     globalbank_rdram_offset = (u32)pGlobalimagetable + 0xFE000000;   // -0x02000000
 *     texLoadFromDisplayList(globalbank_rdram_offset + (u32)&globalDL_0x000, 0);
 *
 * so `&globalDL_0x000` has to be 0x02000000 for that sum to land on the loaded
 * copy. A host link finds these undefined and makes them BSS arrays at
 * ~0x20000000, and the sum then points half a gigabyte past the segment.
 *
 * Same technique as hostcompat/ge_anim_offsets.h, which fixed the identical
 * problem for the animation_data segment: a macro naming the byte AT the
 * offset, so `&NAME` is the offset and every use site works unchanged.
 *
 *     fontdl            vram 0x01000000   rom 0x00117880
 *     Globalimagetable  vram 0x02000000   rom 0x0029D160
 *     rarewarelogo      vram 0x02000000   rom 0x0029E560
 *
 * Note Globalimagetable and rarewarelogo SHARE a VRAM base, which is why the
 * segment a symbol belongs to has to come from ge007.ld rather than from its
 * address (see tools/resolve_assets.py).
 */
#ifndef GE_SEGSYM_OFFSETS_H
#define GE_SEGSYM_OFFSETS_H

#define dlBasicGeometry (*(u8 *)(unsigned long)0x01000000u)
#define dlZBufferGeometry (*(u8 *)(unsigned long)0x01000020u)
#define dlFastPipelineSetup (*(u8 *)(unsigned long)0x01000040u)
#define globalDL_0x000 (*(u8 *)(unsigned long)0x02000000u)
#define globalDL_0x078 (*(u8 *)(unsigned long)0x02000078u)
#define globalDL_0x120 (*(u8 *)(unsigned long)0x02000120u)
#define globalDL_0x1c8 (*(u8 *)(unsigned long)0x020001C8u)
#define globalDL_0x270 (*(u8 *)(unsigned long)0x02000270u)
#define globalDL_0x318 (*(u8 *)(unsigned long)0x02000318u)
#define globalDL_0x3c0 (*(u8 *)(unsigned long)0x020003C0u)
#define globalDL_0x468 (*(u8 *)(unsigned long)0x02000468u)
#define globalDL_0x510 (*(u8 *)(unsigned long)0x02000510u)
#define globalDL_0x5b8 (*(u8 *)(unsigned long)0x020005B8u)
#define globalDL_0x660 (*(u8 *)(unsigned long)0x02000660u)
#define globalDL_0x708 (*(u8 *)(unsigned long)0x02000708u)
#define globalDL_0x7b0 (*(u8 *)(unsigned long)0x020007B0u)
#define globalDL_0x858 (*(u8 *)(unsigned long)0x02000858u)
#define globalDL_0x900 (*(u8 *)(unsigned long)0x02000900u)
#define globalDL_0x9a8 (*(u8 *)(unsigned long)0x020009A8u)
#define globalDL_0xa50 (*(u8 *)(unsigned long)0x02000A50u)
#define s_genericimage (*(u8 *)(unsigned long)0x02000AC8u)
#define s_impactimages (*(u8 *)(unsigned long)0x02000AD4u)
#define s_explosion_smokeimages (*(u8 *)(unsigned long)0x02000BC4u)
#define s_scattered_explosions (*(u8 *)(unsigned long)0x02000C0Cu)
#define s_flareimage1 (*(u8 *)(unsigned long)0x02000C48u)
#define s_flareimage2 (*(u8 *)(unsigned long)0x02000C54u)
#define s_flareimage3 (*(u8 *)(unsigned long)0x02000C60u)
#define s_flareimage4 (*(u8 *)(unsigned long)0x02000C6Cu)
#define s_flareimage5 (*(u8 *)(unsigned long)0x02000C78u)
#define s_ammo9mmimage (*(u8 *)(unsigned long)0x02000C84u)
#define s_rifleammoimage (*(u8 *)(unsigned long)0x02000C90u)
#define s_shotgunammoimage (*(u8 *)(unsigned long)0x02000C9Cu)
#define s_knifeammoimage (*(u8 *)(unsigned long)0x02000CA8u)
#define s_glammoimage (*(u8 *)(unsigned long)0x02000CB4u)
#define s_rocketammoimage (*(u8 *)(unsigned long)0x02000CC0u)
#define s_genericmineammoimage (*(u8 *)(unsigned long)0x02000CCCu)
#define s_grenadeammoimage (*(u8 *)(unsigned long)0x02000CD8u)
#define s_magnumammoimage (*(u8 *)(unsigned long)0x02000CE4u)
#define s_goldengunammoimage (*(u8 *)(unsigned long)0x02000CF0u)
#define s_remotemineammoimage (*(u8 *)(unsigned long)0x02000CFCu)
#define s_timedmineammoimage (*(u8 *)(unsigned long)0x02000D08u)
#define s_proxmineammoimage (*(u8 *)(unsigned long)0x02000D14u)
#define s_tankammoimage (*(u8 *)(unsigned long)0x02000D20u)
#define s_crosshairimage (*(u8 *)(unsigned long)0x02000D2Cu)
#define s_betacrosshairimage (*(u8 *)(unsigned long)0x02000D38u)
#define s_glassoverlayimage (*(u8 *)(unsigned long)0x02000D44u)
#define s_monitorimages (*(u8 *)(unsigned long)0x02000D5Cu)
#define s_skywaterimages (*(u8 *)(unsigned long)0x02000FB4u)
#define s_mainfolderimages (*(u8 *)(unsigned long)0x02000FD8u)
#define s_mpradarimages (*(u8 *)(unsigned long)0x02001020u)
#define s_mpcharselimages (*(u8 *)(unsigned long)0x0200102Cu)
#define s_mpstageselimages (*(u8 *)(unsigned long)0x0200132Cu)
#define D_020043E8 (*(u8 *)(unsigned long)0x020043E8u)
#define DL_RAREWARETEXT (*(u8 *)(unsigned long)0x020044B0u)
#define D_02004758 (*(u8 *)(unsigned long)0x02004758u)
#define D_02004FE8 (*(u8 *)(unsigned long)0x02004FE8u)
#define D_02005FF0 (*(u8 *)(unsigned long)0x02005FF0u)

#endif /* GE_SEGSYM_OFFSETS_H */
