/*
 * ge_segments.h -- GENERATED by tools/extract_segments.py. Do not edit.
 *
 * ROM layout constants for one specific ROM version:
 *   SHA1 abe01e4aeb033b6c0836819f549c791b26cfde83
 *
 * These are the values of the linker-defined *Segment* symbols. On N64 they are
 * absolute link-time constants; a host toolchain cannot give a symbol a chosen
 * address, so the port uses the values directly. See the tool's docstring.
 *
 * 111 symbols.
 */
#ifndef GE_SEGMENTS_H
#define GE_SEGMENTS_H

#define GE_ROM_SHA1 "abe01e4aeb033b6c0836819f549c791b26cfde83"

#define GE_SEG__GlobalimagetableSegmentEnd       0x02001400u
#define GE_SEG__GlobalimagetableSegmentRomEnd    0x0029E560u
#define GE_SEG__GlobalimagetableSegmentRomStart  0x0029D160u
#define GE_SEG__GlobalimagetableSegmentStart     0x02000000u
#define GE_SEG___dataSegmentVaddrStart           0x80020D90u
#define GE_SEG__alt_startSegmentRomStart         0x00101000u
#define GE_SEG__alt_startSegmentStart            0x70100400u
#define GE_SEG__animation_dataSegmentEnd         0x0000E7E0u
#define GE_SEG__animation_dataSegmentRomEnd      0x0029D160u
#define GE_SEG__animation_dataSegmentRomStart    0x0028E980u
#define GE_SEG__animation_dataSegmentStart       0x00000000u
#define GE_SEG__animation_entriesSegmentEnd      0x00169EC0u
#define GE_SEG__animation_entriesSegmentRomEnd   0x0028E980u
#define GE_SEG__animation_entriesSegmentRomStart 0x00124AC0u
#define GE_SEG__animation_entriesSegmentStart    0x00000000u
#define GE_SEG__bootSegmentEnd                   0x04001000u
#define GE_SEG__bootSegmentRomEnd                0x00001000u
#define GE_SEG__bootSegmentRomStart              0x00000040u
#define GE_SEG__bootSegmentStart                 0x04000040u
#define GE_SEG__bssSegmentEnd                    0x8008E360u
#define GE_SEG__bssSegmentStart                  0x8005D2E0u
#define GE_SEG__cdataSegmentEnd                  0x00033590u
#define GE_SEG__cdataSegmentRomEnd               0x00033590u
#define GE_SEG__cdataSegmentRomStart             0x00021990u
#define GE_SEG__cdataSegmentStart                0x00021990u
#define GE_SEG__cfbSegmentEnd                    0x80400000u
#define GE_SEG__cfbSegmentStart                  0x803B5000u
#define GE_SEG__codeSegmentEnd                   0x70020D90u
#define GE_SEG__codeSegmentRomEnd                0x00021990u
#define GE_SEG__codeSegmentRomStart              0x00001050u
#define GE_SEG__codeSegmentStart                 0x70000450u
#define GE_SEG__csegmentSegmentEnd               0x8005D2E0u
#define GE_SEG__csegmentSegmentRomEnd            0x00C3C550u
#define GE_SEG__csegmentSegmentRomStart          0x00C00000u
#define GE_SEG__csegmentSegmentStart             0x80020D90u
#define GE_SEG__dataSegmentVaddrEnd              0x00C3C550u
#define GE_SEG__efontchardataSegmentEnd          0x00001A80u
#define GE_SEG__efontchardataSegmentRomEnd       0x00124AC0u
#define GE_SEG__efontchardataSegmentRomStart     0x00123040u
#define GE_SEG__efontchardataSegmentStart        0x00000000u
#define GE_SEG__fontbankgothicSegmentEnd         0x000024B0u
#define GE_SEG__fontbankgothicSegmentRomEnd      0x002E88A0u
#define GE_SEG__fontbankgothicSegmentRomStart    0x002E63F0u
#define GE_SEG__fontbankgothicSegmentStart       0x00000000u
#define GE_SEG__fontdlSegmentEnd                 0x010000C0u
#define GE_SEG__fontdlSegmentRomEnd              0x00117940u
#define GE_SEG__fontdlSegmentRomStart            0x00117880u
#define GE_SEG__fontdlSegmentStart               0x01000000u
#define GE_SEG__fontzurichboldSegmentEnd         0x00003540u
#define GE_SEG__fontzurichboldSegmentRomEnd      0x002EBDE0u
#define GE_SEG__fontzurichboldSegmentRomStart    0x002E88A0u
#define GE_SEG__fontzurichboldSegmentStart       0x00000000u
#define GE_SEG__gameSegmentEnd                   0x7F0E2D50u
#define GE_SEG__gameSegmentRomEnd                0x00117880u
#define GE_SEG__gameSegmentRomStart              0x00034B30u
#define GE_SEG__gameSegmentStart                 0x7F000000u
#define GE_SEG__headerSegmentEnd                 0x04000040u
#define GE_SEG__headerSegmentRomEnd              0x00000040u
#define GE_SEG__headerSegmentRomStart            0x00000000u
#define GE_SEG__headerSegmentStart               0x04000000u
#define GE_SEG__imagesSegmentEnd                 0x00BE6D10u
#define GE_SEG__imagesSegmentRomEnd              0x00BE6D10u
#define GE_SEG__imagesSegmentRomStart            0x008F7DF0u
#define GE_SEG__imagesSegmentStart               0x008F7DF0u
#define GE_SEG__inflateSegmentEnd                0x702015A0u
#define GE_SEG__inflateSegmentRomEnd             0x00034B30u
#define GE_SEG__inflateSegmentRomStart           0x00033590u
#define GE_SEG__inflateSegmentStart              0x70200000u
#define GE_SEG__instrumentsctlSegmentRomEnd      0x003B87F0u
#define GE_SEG__instrumentsctlSegmentRomStart    0x003B4450u
#define GE_SEG__instrumentstblSegmentRomEnd      0x00419790u
#define GE_SEG__instrumentstblSegmentRomStart    0x003B87F0u
#define GE_SEG__jfontchardataSegmentEnd          0x0000B700u
#define GE_SEG__jfontchardataSegmentRomEnd       0x00123040u
#define GE_SEG__jfontchardataSegmentRomStart     0x00117940u
#define GE_SEG__jfontchardataSegmentStart        0x00000000u
#define GE_SEG__musicfilesSegmentEnd             0x00438660u
#define GE_SEG__musicfilesSegmentRomEnd          0x00438660u
#define GE_SEG__musicfilesSegmentRomStart        0x002EBDE0u
#define GE_SEG__musicfilesSegmentStart           0x002EBDE0u
#define GE_SEG__musicsampletblSegmentRomEnd      0x0041998Cu
#define GE_SEG__musicsampletblSegmentRomStart    0x00419790u
#define GE_SEG__obsegSegmentEnd                  0x008F7DF0u
#define GE_SEG__obsegSegmentRomEnd               0x008F7DF0u
#define GE_SEG__obsegSegmentRomStart             0x00438660u
#define GE_SEG__obsegSegmentStart                0x00438660u
#define GE_SEG__ramromDam1SegmentRomStart        0x002BF2D0u
#define GE_SEG__ramromfilesSegmentEnd            0x002E63F0u
#define GE_SEG__ramromfilesSegmentRomEnd         0x002E63F0u
#define GE_SEG__ramromfilesSegmentRomStart       0x002BF2D0u
#define GE_SEG__ramromfilesSegmentStart          0x002BF2D0u
#define GE_SEG__rarewarelogoSegmentEnd           0x020067F0u
#define GE_SEG__rarewarelogoSegmentRomEnd        0x002A4D50u
#define GE_SEG__rarewarelogoSegmentRomStart      0x0029E560u
#define GE_SEG__rarewarelogoSegmentStart         0x02000000u
#define GE_SEG__romSegmentEnd                    0x00BE6D10u
#define GE_SEG__romSegmentStart                  0x00000000u
#define GE_SEG__romfiles2SegmentEnd              0x002BF2D0u
#define GE_SEG__romfiles2SegmentRomEnd           0x002BF2D0u
#define GE_SEG__romfiles2SegmentRomStart         0x002A4D50u
#define GE_SEG__romfiles2SegmentStart            0x002A4D50u
#define GE_SEG__sfxctlSegmentRomEnd              0x002F19A0u
#define GE_SEG__sfxctlSegmentRomStart            0x002EBDE0u
#define GE_SEG__sfxtblSegmentRomEnd              0x003B4450u
#define GE_SEG__sfxtblSegmentRomStart            0x002F19A0u
#define GE_SEG__stacksSegmentEnd                 0x803B5000u
#define GE_SEG__stacksSegmentStart               0x803AB400u
#define GE_SEG__startSegmentEnd                  0x80000450u
#define GE_SEG__startSegmentRomEnd               0x00001050u
#define GE_SEG__startSegmentRomStart             0x00001000u
#define GE_SEG__startSegmentStart                0x80000400u

/*
 * src/boot.s also defines these as two-instruction accessor
 * FUNCTIONS returning the symbol above. src/ultra/segments.c
 * implements them for the host.
 */
/*   get_cdataSegmentRomEnd() */
/*   get_cdataSegmentRomStart() */
/*   get_csegmentSegmentStart() */
/*   get_inflateSegmentRomEnd() */
/*   get_inflateSegmentRomStart() */

#endif /* GE_SEGMENTS_H */
