/*
 * ge_ucode.h -- GENERATED by tools/gen_ucode_blobs.py. Do not edit.
 *
 * Maps the decomp's assembly labels onto the generated arrays. The *End names
 * are macros because C cannot place a symbol at another array's end; the
 * matching `extern` declarations in src/game/rsp.c are guarded for the host.
 */
#ifndef GE_UCODE_H
#define GE_UCODE_H

#ifdef __cplusplus
extern "C" {
#endif

extern long long int ge_gsp3DText[644];
#define gsp3DTextStart (ge_gsp3DText)
#define gsp3DTextEnd   (ge_gsp3DText + 644)
#define GE_GSP3D_TEXT_BYTES 5152

extern long long int ge_gsp3DData[256];
#define gsp3DDataStart (ge_gsp3DData)
#define gsp3DDataEnd   (ge_gsp3DData + 256)
#define GE_GSP3D_DATA_BYTES 2048

extern long long int ge_aspMainText[440];
#define aspMainTextStart (ge_aspMainText)
#define aspMainTextEnd   (ge_aspMainText + 440)
#define GE_ASPMAIN_TEXT_BYTES 3520

extern long long int ge_aspMainData[88];
#define aspMainDataStart (ge_aspMainData)
#define aspMainDataEnd   (ge_aspMainData + 88)
#define GE_ASPMAIN_DATA_BYTES 704

extern long long int ge_rspbootText[26];
#define rspbootTextStart (ge_rspbootText)
#define rspbootTextEnd   (ge_rspbootText + 26)
#define GE_RSPBOOT_TEXT_BYTES 208

#ifdef __cplusplus
}
#endif

#endif /* GE_UCODE_H */
