/*
 * segments.c — the ROM layout the game expects from its linker.
 *
 * WHY THIS FILE EXISTS
 *
 * The game reaches its own ROM layout through linker-defined symbols:
 *
 *     romCopy(dst, &_animation_dataSegmentRomStart, size);
 *     size = (u32)&_inflateSegmentRomStart - (u32)&_codeSegmentRomStart;
 *
 * On N64 those are absolute link-time constants — ROM byte offsets, and RDRAM
 * or TLB virtual addresses. A host toolchain cannot give an ordinary symbol a
 * chosen address, and on Windows there is no portable way to define an absolute
 * symbol at all. So the port cannot reproduce them as symbols; it needs their
 * values, which hostcompat/ge_segments.h supplies (generated by
 * tools/extract_segments.py from a linked map file).
 *
 * WHY THE VALUES ARE ALLOWED TO BE CONSTANTS
 *
 * They are fixed for a given ROM version — every US cartridge has the same
 * layout — and the port already requires the user's own ROM and checks its
 * SHA1. GE_ROM_SHA1 records which ROM the table was generated from, and
 * geSegmentsCheckRom() makes the assumption fail loudly rather than silently
 * reading the wrong offsets if someone points the port at a different version.
 *
 * WHAT THIS DOES NOT DO
 *
 * It ships no ROM data. These are offsets into the user's own file.
 */

#include <string.h>

#include "ge_segments.h"
#include "segments.h"

/*
 * src/boot.s defines five two-instruction accessors that return a linker
 * symbol. They are ordinary functions on N64 and ordinary functions here.
 */
unsigned int get_csegmentSegmentStart(void)  { return GE_SEG__csegmentSegmentStart;  }
unsigned int get_cdataSegmentRomStart(void)  { return GE_SEG__cdataSegmentRomStart;  }
unsigned int get_cdataSegmentRomEnd(void)    { return GE_SEG__cdataSegmentRomEnd;    }
unsigned int get_inflateSegmentRomStart(void){ return GE_SEG__inflateSegmentRomStart;}
unsigned int get_inflateSegmentRomEnd(void)  { return GE_SEG__inflateSegmentRomEnd;  }

const char *geSegmentsExpectedRomSha1(void)
{
    return GE_ROM_SHA1;
}

int geSegmentsCheckRom(const char *sha1_hex)
{
    if (sha1_hex == 0) {
        return 0;
    }
    /*
     * Deliberately strict. A near-miss here means every ROM offset below is
     * subtly wrong, which would surface much later as corrupt textures or a
     * hang in decompression — a class of bug that is miserable to trace back
     * to its cause. Better to refuse at mount time.
     */
    return strcmp(sha1_hex, GE_ROM_SHA1) == 0;
}
