/*
 * segments.h — host-side ROM layout accessors.
 *
 * See segments.c for why the port carries these values rather than linker
 * symbols. The table itself is hostcompat/ge_segments.h, generated by
 * tools/extract_segments.py.
 */
#ifndef GE_ULTRA_SEGMENTS_H
#define GE_ULTRA_SEGMENTS_H

#ifdef __cplusplus
extern "C" {
#endif

/* The five accessors src/boot.s defines in assembly. */
unsigned int get_csegmentSegmentStart(void);
unsigned int get_cdataSegmentRomStart(void);
unsigned int get_cdataSegmentRomEnd(void);
unsigned int get_inflateSegmentRomStart(void);
unsigned int get_inflateSegmentRomEnd(void);

/* SHA1 the segment table was generated from. */
const char *geSegmentsExpectedRomSha1(void);

/*
 * Non-zero if sha1_hex matches the ROM this table describes. Call at mount
 * time: a mismatched ROM makes every offset wrong in a way that only shows up
 * much later, as corrupt data or a hang in decompression.
 */
int geSegmentsCheckRom(const char *sha1_hex);

#ifdef __cplusplus
}
#endif

#endif /* GE_ULTRA_SEGMENTS_H */
