/*
 * ge_assets.h -- GENERATED by tools/gen_asset_symbols.py. Do not edit.
 */
#ifndef GE_ASSETS_H
#define GE_ASSETS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef struct GeAssetEntry {
    const char    *name;
    unsigned char *data;       /* where the game expects it */
    unsigned int   size;
    unsigned int   rom_offset; /* where it lives in the user's ROM; 0 = unknown */
} GeAssetEntry;

/*
 * Copy every asset from the mounted ROM into its symbol. Returns the number
 * loaded; entries with rom_offset 0, or that would run past the end of the ROM,
 * are skipped and counted in *skipped.
 */
unsigned int geAssetsLoad(const unsigned char *rom, unsigned int rom_size,
                          unsigned int *skipped);

/*
 * Translate a host address that lies inside a known asset into its ROM offset.
 * Returns 1 on success. The DMA path uses this because the game passes asset
 * symbol ADDRESSES to the PI as device addresses -- on N64 they are the same
 * number. See ge_assets_load.c.
 */
int geAssetsRomOffsetFor(const void *host_addr, unsigned int *rom_offset);

typedef struct GeAssetSpan {
    const unsigned char *lo;
    const unsigned char *hi;
    unsigned int         conflicts;  /* assets overlapping a ROM-offset window */
} GeAssetSpan;

/*
 * Are the asset symbols linked clear of every address the game could mean as a
 * ROM offset? Returns 1 when they are. Call this at startup, BEFORE installing
 * the translator: if it returns 0 the translator will capture genuine ROM
 * offsets and hand back different ones, and the failure surfaces as the game's
 * own decompressor spinning on data that is not compressed.
 */
int geAssetsCheckAddressSpace(unsigned int rom_size, GeAssetSpan *out);

extern const GeAssetEntry ge_asset_manifest[];
extern const unsigned int ge_asset_count;

/*
 * End labels. The game uses `&X_end - &X` as a size:
 *
 *     romCopy(dst, &unknown2, (u32)&unknown2_end - (u32)&unknown2);
 *
 * C cannot place one object's symbol at another object's end, so
 * these name the byte one past the array -- the same technique the
 * segment table uses. The decomp's `extern` for them is guarded,
 * because a macro and a declaration of that name cannot coexist.
 */
extern unsigned char unknown2[107904];
#define unknown2_end (*(unknown2 + 107904u))

#ifdef __cplusplus
}
#endif

#endif /* GE_ASSETS_H */
