/*
 * ge_assets.c -- GENERATED by tools/gen_asset_symbols.py. Do not edit.
 *
 * 821 asset symbols, defined at their real sizes so the game links.
 * They are ZERO until geAssetsLoad() fills them -- see the generator's
 * docstring for why the data is not baked in here.
 */
#include "ge_assets.h"

unsigned char CarmourguardZ[9344] __attribute__((aligned(16)));
unsigned char CbaronsamediZ[14064] __attribute__((aligned(16)));
unsigned char CbluecamguardZ[9968] __attribute__((aligned(16)));
unsigned char CbluemanZ[7696] __attribute__((aligned(16)));
unsigned char CbluewomanZ[7872] __attribute__((aligned(16)));
unsigned char CboilerbondZ[11280] __attribute__((aligned(16)));
unsigned char CboilertrevZ[13952] __attribute__((aligned(16)));
unsigned char CborisZ[12576] __attribute__((aligned(16)));
unsigned char CcamguardZ[9952] __attribute__((aligned(16)));
unsigned char CcardimanZ[7680] __attribute__((aligned(16)));
unsigned char CcheckmanZ[7808] __attribute__((aligned(16)));
unsigned char CcommguardZ[9728] __attribute__((aligned(16)));
unsigned char CdjbondZ[11920] __attribute__((aligned(16)));
unsigned char CfattechwomanZ[7968] __attribute__((aligned(16)));
unsigned char Cgreatguard2Z[10016] __attribute__((aligned(16)));
unsigned char CgreatguardZ[9856] __attribute__((aligned(16)));
unsigned char CgreyguardZ[9936] __attribute__((aligned(16)));
unsigned char CgreymanZ[7616] __attribute__((aligned(16)));
unsigned char CheadalanZ[1488] __attribute__((aligned(16)));
unsigned char CheadbZ[1392] __attribute__((aligned(16)));
unsigned char CheadbalaclavaZ[976] __attribute__((aligned(16)));
unsigned char CheadbikeZ[1696] __attribute__((aligned(16)));
unsigned char CheadbrosnanZ[3408] __attribute__((aligned(16)));
unsigned char CheadbrosnanboilerZ[2976] __attribute__((aligned(16)));
unsigned char CheadbrosnansnowZ[3712] __attribute__((aligned(16)));
unsigned char CheadbrosnansuitZ[3456] __attribute__((aligned(16)));
unsigned char CheadbrosnantimberZ[3008] __attribute__((aligned(16)));
unsigned char CheadchrisZ[1344] __attribute__((aligned(16)));
unsigned char CheaddaveZ[1408] __attribute__((aligned(16)));
unsigned char CheaddesZ[1328] __attribute__((aligned(16)));
unsigned char CheadduncanZ[1312] __attribute__((aligned(16)));
unsigned char CheaddwayneZ[1408] __attribute__((aligned(16)));
unsigned char CheadgrahamZ[1392] __attribute__((aligned(16)));
unsigned char CheadgrantZ[1328] __attribute__((aligned(16)));
unsigned char CheadjimZ[1328] __attribute__((aligned(16)));
unsigned char Cheadjoe2Z[1056] __attribute__((aligned(16)));
unsigned char CheadjoeZ[1392] __attribute__((aligned(16)));
unsigned char CheadjoelZ[1296] __attribute__((aligned(16)));
unsigned char CheadkarlZ[1376] __attribute__((aligned(16)));
unsigned char CheadkenZ[1360] __attribute__((aligned(16)));
unsigned char CheadleeZ[1408] __attribute__((aligned(16)));
unsigned char CheadmandyZ[1008] __attribute__((aligned(16)));
unsigned char CheadmarionZ[1040] __attribute__((aligned(16)));
unsigned char CheadmarkZ[1328] __attribute__((aligned(16)));
unsigned char CheadmartinZ[1376] __attribute__((aligned(16)));
unsigned char CheadmishkinZ[1376] __attribute__((aligned(16)));
unsigned char CheadneilZ[1312] __attribute__((aligned(16)));
unsigned char CheadpeteZ[1424] __attribute__((aligned(16)));
unsigned char CheadrobinZ[1296] __attribute__((aligned(16)));
unsigned char CheadsallyZ[1024] __attribute__((aligned(16)));
unsigned char CheadscottZ[1408] __attribute__((aligned(16)));
unsigned char CheadshaunZ[1504] __attribute__((aligned(16)));
unsigned char CheadsteveeZ[1360] __attribute__((aligned(16)));
unsigned char CheadstevehZ[1360] __attribute__((aligned(16)));
unsigned char CheadvivienZ[1168] __attribute__((aligned(16)));
unsigned char CjawsZ[11328] __attribute__((aligned(16)));
unsigned char CjeanwomanZ[8208] __attribute__((aligned(16)));
unsigned char CmaydayZ[11168] __attribute__((aligned(16)));
unsigned char CmoonfemaleZ[8528] __attribute__((aligned(16)));
unsigned char CmoonguardZ[9712] __attribute__((aligned(16)));
unsigned char CnatalyaZ[14528] __attribute__((aligned(16)));
unsigned char CnavyguardZ[9952] __attribute__((aligned(16)));
unsigned char CoddjobZ[12592] __attribute__((aligned(16)));
unsigned char ColiveguardZ[9808] __attribute__((aligned(16)));
unsigned char CorumovZ[13360] __attribute__((aligned(16)));
unsigned char CpilotZ[12416] __attribute__((aligned(16)));
unsigned char CredmanZ[10032] __attribute__((aligned(16)));
unsigned char CrusguardZ[7216] __attribute__((aligned(16)));
unsigned char CsnowbondZ[13104] __attribute__((aligned(16)));
unsigned char CsnowguardZ[11392] __attribute__((aligned(16)));
unsigned char CspicebondZ[14624] __attribute__((aligned(16)));
unsigned char Csuit_lf_handZ[12832] __attribute__((aligned(16)));
unsigned char CsuitbondZ[11664] __attribute__((aligned(16)));
unsigned char CtechmanZ[9904] __attribute__((aligned(16)));
unsigned char CtechwomanZ[8176] __attribute__((aligned(16)));
unsigned char CtimberbondZ[11568] __attribute__((aligned(16)));
unsigned char CtrevelyanZ[14288] __attribute__((aligned(16)));
unsigned char CtrevguardZ[9744] __attribute__((aligned(16)));
unsigned char CvalentinZ[12144] __attribute__((aligned(16)));
unsigned char CxeniaZ[14832] __attribute__((aligned(16)));
unsigned char Gak47Z[2576] __attribute__((aligned(16)));
unsigned char GaudiotapeZ[912] __attribute__((aligned(16)));
unsigned char GautoshotZ[6160] __attribute__((aligned(16)));
unsigned char GblackboxZ[1536] __attribute__((aligned(16)));
unsigned char GblueprintsZ[256] __attribute__((aligned(16)));
unsigned char GbombcaseZ[1936] __attribute__((aligned(16)));
unsigned char GbombdefuserZ[1520] __attribute__((aligned(16)));
unsigned char GbriefcaseZ[1936] __attribute__((aligned(16)));
unsigned char GbugZ[2416] __attribute__((aligned(16)));
unsigned char GbugdetectorZ[848] __attribute__((aligned(16)));
unsigned char GbungeeZ[848] __attribute__((aligned(16)));
unsigned char GcameraZ[1152] __attribute__((aligned(16)));
unsigned char GcartblueZ[608] __attribute__((aligned(16)));
unsigned char GcartridgeZ[304] __attribute__((aligned(16)));
unsigned char GcartrifleZ[528] __attribute__((aligned(16)));
unsigned char GcartshellZ[512] __attribute__((aligned(16)));
unsigned char GcircuitboardZ[320] __attribute__((aligned(16)));
unsigned char GclipboardZ[496] __attribute__((aligned(16)));
unsigned char GcreditcardZ[848] __attribute__((aligned(16)));
unsigned char GdarkglassesZ[848] __attribute__((aligned(16)));
unsigned char GdatathiefZ[320] __attribute__((aligned(16)));
unsigned char GdattapeZ[368] __attribute__((aligned(16)));
unsigned char GdoordecoderZ[1408] __attribute__((aligned(16)));
unsigned char GdoorexploderZ[848] __attribute__((aligned(16)));
unsigned char GdossierredZ[864] __attribute__((aligned(16)));
unsigned char GdynamiteZ[848] __attribute__((aligned(16)));
unsigned char GexplosivefloppyZ[592] __attribute__((aligned(16)));
unsigned char GexplosivepenZ[848] __attribute__((aligned(16)));
unsigned char GextinguisherZ[2032] __attribute__((aligned(16)));
unsigned char GfingergunZ[848] __attribute__((aligned(16)));
unsigned char GfistZ[5888] __attribute__((aligned(16)));
unsigned char GflarepistolZ[848] __attribute__((aligned(16)));
unsigned char Gfnp90Z[3232] __attribute__((aligned(16)));
unsigned char GgaskeyringZ[2608] __attribute__((aligned(16)));
unsigned char GgoldbarZ[848] __attribute__((aligned(16)));
unsigned char GgoldeneyekeyZ[2480] __attribute__((aligned(16)));
unsigned char GgoldengunZ[6112] __attribute__((aligned(16)));
unsigned char GgoldwppkZ[6496] __attribute__((aligned(16)));
unsigned char GgrenadeZ[2608] __attribute__((aligned(16)));
unsigned char GgrenadelaunchZ[4224] __attribute__((aligned(16)));
unsigned char GheroinZ[848] __attribute__((aligned(16)));
unsigned char GjoypadZ[7856] __attribute__((aligned(16)));
unsigned char GkeyanalysercaseZ[1936] __attribute__((aligned(16)));
unsigned char GkeyboltZ[2544] __attribute__((aligned(16)));
unsigned char GkeycardZ[304] __attribute__((aligned(16)));
unsigned char GkeyyaleZ[3408] __attribute__((aligned(16)));
unsigned char GknifeZ[6864] __attribute__((aligned(16)));
unsigned char GlaserZ[3568] __attribute__((aligned(16)));
unsigned char GlectreZ[848] __attribute__((aligned(16)));
unsigned char GlockexploderZ[848] __attribute__((aligned(16)));
unsigned char Gm16Z[2592] __attribute__((aligned(16)));
unsigned char GmapZ[240] __attribute__((aligned(16)));
unsigned char GmicrocameraZ[1600] __attribute__((aligned(16)));
unsigned char GmicrocodeZ[848] __attribute__((aligned(16)));
unsigned char GmicrofilmZ[848] __attribute__((aligned(16)));
unsigned char GmoneyZ[848] __attribute__((aligned(16)));
unsigned char Gmp5kZ[3040] __attribute__((aligned(16)));
unsigned char Gmp5ksilZ[3328] __attribute__((aligned(16)));
unsigned char GpitongunZ[848] __attribute__((aligned(16)));
unsigned char GplansZ[464] __attribute__((aligned(16)));
unsigned char GplastiqueZ[848] __attribute__((aligned(16)));
unsigned char GpolarizedglassesZ[1376] __attribute__((aligned(16)));
unsigned char GproximitymineZ[2032] __attribute__((aligned(16)));
unsigned char GremotemineZ[2496] __attribute__((aligned(16)));
unsigned char GrocketlaunchZ[4640] __attribute__((aligned(16)));
unsigned char GrugerZ[7568] __attribute__((aligned(16)));
unsigned char GsafecrackercaseZ[1936] __attribute__((aligned(16)));
unsigned char GshotgunZ[3808] __attribute__((aligned(16)));
unsigned char GsilverwppkZ[6496] __attribute__((aligned(16)));
unsigned char GskorpionZ[4608] __attribute__((aligned(16)));
unsigned char GsniperrifleZ[4208] __attribute__((aligned(16)));
unsigned char GspectreZ[3200] __attribute__((aligned(16)));
unsigned char GspooltapeZ[848] __attribute__((aligned(16)));
unsigned char GspyfileZ[848] __attribute__((aligned(16)));
unsigned char GstafflistZ[416] __attribute__((aligned(16)));
unsigned char GtaserZ[7776] __attribute__((aligned(16)));
unsigned char GthrowknifeZ[6896] __attribute__((aligned(16)));
unsigned char GtimedmineZ[2752] __attribute__((aligned(16)));
unsigned char GtriggerZ[13312] __attribute__((aligned(16)));
unsigned char Gtt33Z[6944] __attribute__((aligned(16)));
unsigned char GuziZ[2320] __attribute__((aligned(16)));
unsigned char GvideotapeZ[528] __attribute__((aligned(16)));
unsigned char GwatchcommunicatorZ[5216] __attribute__((aligned(16)));
unsigned char GwatchgeigercounterZ[5216] __attribute__((aligned(16)));
unsigned char GwatchidentifierZ[5216] __attribute__((aligned(16)));
unsigned char GwatchlaserZ[13312] __attribute__((aligned(16)));
unsigned char GwatchmagnetattractZ[5200] __attribute__((aligned(16)));
unsigned char GwatchmagnetrepelZ[5216] __attribute__((aligned(16)));
unsigned char GweaponcaseZ[1936] __attribute__((aligned(16)));
unsigned char GwppkZ[7312] __attribute__((aligned(16)));
unsigned char GwppksilZ[7488] __attribute__((aligned(16)));
unsigned char GwristdartZ[848] __attribute__((aligned(16)));
unsigned char LameE[16] __attribute__((aligned(16)));
unsigned char LameJ[16] __attribute__((aligned(16)));
unsigned char LarchE[1584] __attribute__((aligned(16)));
unsigned char LarchJ[1632] __attribute__((aligned(16)));
unsigned char LarecE[1488] __attribute__((aligned(16)));
unsigned char LarecJ[1424] __attribute__((aligned(16)));
unsigned char LarkE[1696] __attribute__((aligned(16)));
unsigned char LarkJ[1712] __attribute__((aligned(16)));
unsigned char LashE[16] __attribute__((aligned(16)));
unsigned char LashJ[16] __attribute__((aligned(16)));
unsigned char LaztE[1088] __attribute__((aligned(16)));
unsigned char LaztJ[1200] __attribute__((aligned(16)));
unsigned char LcatE[16] __attribute__((aligned(16)));
unsigned char LcatJ[16] __attribute__((aligned(16)));
unsigned char LcaveE[1024] __attribute__((aligned(16)));
unsigned char LcaveJ[1120] __attribute__((aligned(16)));
unsigned char LcradE[1232] __attribute__((aligned(16)));
unsigned char LcradJ[1200] __attribute__((aligned(16)));
unsigned char LcrypE[592] __attribute__((aligned(16)));
unsigned char LcrypJ[704] __attribute__((aligned(16)));
unsigned char LdamE[1104] __attribute__((aligned(16)));
unsigned char LdamJ[1136] __attribute__((aligned(16)));
unsigned char LdepoE[880] __attribute__((aligned(16)));
unsigned char LdepoJ[832] __attribute__((aligned(16)));
unsigned char LdestE[1168] __attribute__((aligned(16)));
unsigned char LdestJ[1120] __attribute__((aligned(16)));
unsigned char LdishE[16] __attribute__((aligned(16)));
unsigned char LdishJ[16] __attribute__((aligned(16)));
unsigned char LearE[16] __attribute__((aligned(16)));
unsigned char LearJ[16] __attribute__((aligned(16)));
unsigned char LeldE[16] __attribute__((aligned(16)));
unsigned char LeldJ[16] __attribute__((aligned(16)));
unsigned char LgunE[1824] __attribute__((aligned(16)));
unsigned char LgunJ[1872] __attribute__((aligned(16)));
unsigned char LimpE[16] __attribute__((aligned(16)));
unsigned char LimpJ[16] __attribute__((aligned(16)));
unsigned char LjunE[1312] __attribute__((aligned(16)));
unsigned char LjunJ[1344] __attribute__((aligned(16)));
unsigned char LleeE[16] __attribute__((aligned(16)));
unsigned char LleeJ[16] __attribute__((aligned(16)));
unsigned char LlenE[1600] __attribute__((aligned(16)));
unsigned char LlenJ[688] __attribute__((aligned(16)));
unsigned char LlipE[16] __attribute__((aligned(16)));
unsigned char LlipJ[16] __attribute__((aligned(16)));
unsigned char LlueE[16] __attribute__((aligned(16)));
unsigned char LlueJ[16] __attribute__((aligned(16)));
unsigned char LmiscE[672] __attribute__((aligned(16)));
unsigned char LmiscJ[736] __attribute__((aligned(16)));
unsigned char LmpmenuE[416] __attribute__((aligned(16)));
unsigned char LmpmenuJ[400] __attribute__((aligned(16)));
unsigned char LmpweaponsE[192] __attribute__((aligned(16)));
unsigned char LmpweaponsJ[224] __attribute__((aligned(16)));
unsigned char LoatE[16] __attribute__((aligned(16)));
unsigned char LoatJ[16] __attribute__((aligned(16)));
unsigned char LoptionsE[560] __attribute__((aligned(16)));
unsigned char LoptionsJ[592] __attribute__((aligned(16)));
unsigned char LpamE[16] __attribute__((aligned(16)));
unsigned char LpamJ[16] __attribute__((aligned(16)));
unsigned char LpeteE[1152] __attribute__((aligned(16)));
unsigned char LpeteJ[1136] __attribute__((aligned(16)));
unsigned char LpropobjE[672] __attribute__((aligned(16)));
unsigned char LpropobjJ[704] __attribute__((aligned(16)));
unsigned char LrefE[16] __attribute__((aligned(16)));
unsigned char LrefJ[16] __attribute__((aligned(16)));
unsigned char LritE[16] __attribute__((aligned(16)));
unsigned char LritJ[16] __attribute__((aligned(16)));
unsigned char LrunE[624] __attribute__((aligned(16)));
unsigned char LrunJ[656] __attribute__((aligned(16)));
unsigned char LsevE[1376] __attribute__((aligned(16)));
unsigned char LsevJ[1296] __attribute__((aligned(16)));
unsigned char LsevbE[1872] __attribute__((aligned(16)));
unsigned char LsevbJ[2032] __attribute__((aligned(16)));
unsigned char LsevxE[1120] __attribute__((aligned(16)));
unsigned char LsevxJ[960] __attribute__((aligned(16)));
unsigned char LsevxbE[1168] __attribute__((aligned(16)));
unsigned char LsevxbJ[1104] __attribute__((aligned(16)));
unsigned char LshoE[16] __attribute__((aligned(16)));
unsigned char LshoJ[16] __attribute__((aligned(16)));
unsigned char LsiloE[1456] __attribute__((aligned(16)));
unsigned char LsiloJ[1504] __attribute__((aligned(16)));
unsigned char LstatE[2336] __attribute__((aligned(16)));
unsigned char LstatJ[2160] __attribute__((aligned(16)));
unsigned char LtitleE[2752] __attribute__((aligned(16)));
unsigned char LtitleJ[2960] __attribute__((aligned(16)));
unsigned char LtraE[1072] __attribute__((aligned(16)));
unsigned char LtraJ[1056] __attribute__((aligned(16)));
unsigned char LwaxE[16] __attribute__((aligned(16)));
unsigned char LwaxJ[16] __attribute__((aligned(16)));
unsigned char PICBMZ[9600] __attribute__((aligned(16)));
unsigned char PICBM_noseZ[1968] __attribute__((aligned(16)));
unsigned char Pak47magZ[480] __attribute__((aligned(16)));
unsigned char Palarm1Z[352] __attribute__((aligned(16)));
unsigned char Palarm2Z[416] __attribute__((aligned(16)));
unsigned char Pammo_crate1Z[576] __attribute__((aligned(16)));
unsigned char Pammo_crate2Z[576] __attribute__((aligned(16)));
unsigned char Pammo_crate3Z[592] __attribute__((aligned(16)));
unsigned char Pammo_crate4Z[624] __attribute__((aligned(16)));
unsigned char Pammo_crate5Z[704] __attribute__((aligned(16)));
unsigned char PapcZ[7264] __attribute__((aligned(16)));
unsigned char Parchsecdoor1Z[480] __attribute__((aligned(16)));
unsigned char Parchsecdoor2Z[464] __attribute__((aligned(16)));
unsigned char ParticZ[3584] __attribute__((aligned(16)));
unsigned char PartictrailerZ[2320] __attribute__((aligned(16)));
unsigned char PbarricadeZ[576] __attribute__((aligned(16)));
unsigned char Pbin1Z[848] __attribute__((aligned(16)));
unsigned char Pblotter1Z[224] __attribute__((aligned(16)));
unsigned char PbodyarmourZ[1184] __attribute__((aligned(16)));
unsigned char PbodyarmourvestZ[1056] __attribute__((aligned(16)));
unsigned char PbollardZ[512] __attribute__((aligned(16)));
unsigned char PbombZ[368] __attribute__((aligned(16)));
unsigned char Pbook1Z[400] __attribute__((aligned(16)));
unsigned char Pbookshelf1Z[1776] __attribute__((aligned(16)));
unsigned char Pborg_crateZ[368] __attribute__((aligned(16)));
unsigned char PboxcartridgesZ[512] __attribute__((aligned(16)));
unsigned char Pboxes2x4Z[1072] __attribute__((aligned(16)));
unsigned char Pboxes3x4Z[1088] __attribute__((aligned(16)));
unsigned char Pboxes4x4Z[1632] __attribute__((aligned(16)));
unsigned char PbrakeunitZ[880] __attribute__((aligned(16)));
unsigned char Pbridge_console1aZ[1408] __attribute__((aligned(16)));
unsigned char Pbridge_console1bZ[1376] __attribute__((aligned(16)));
unsigned char Pbridge_console2aZ[1408] __attribute__((aligned(16)));
unsigned char Pbridge_console2bZ[1264] __attribute__((aligned(16)));
unsigned char Pbridge_console3aZ[1360] __attribute__((aligned(16)));
unsigned char Pbridge_console3bZ[1424] __attribute__((aligned(16)));
unsigned char PcarbmwZ[3296] __attribute__((aligned(16)));
unsigned char Pcard_box1Z[512] __attribute__((aligned(16)));
unsigned char Pcard_box2Z[576] __attribute__((aligned(16)));
unsigned char Pcard_box3Z[496] __attribute__((aligned(16)));
unsigned char Pcard_box4_lgZ[432] __attribute__((aligned(16)));
unsigned char Pcard_box5_lgZ[512] __attribute__((aligned(16)));
unsigned char Pcard_box6_lgZ[496] __attribute__((aligned(16)));
unsigned char PcarescortZ[3072] __attribute__((aligned(16)));
unsigned char PcargolfZ[3120] __attribute__((aligned(16)));
unsigned char PcarweirdZ[4416] __attribute__((aligned(16)));
unsigned char PcarzilZ[5632] __attribute__((aligned(16)));
unsigned char PcctvZ[896] __attribute__((aligned(16)));
unsigned char PchraudiotapeZ[1376] __attribute__((aligned(16)));
unsigned char PchrautoshotZ[864] __attribute__((aligned(16)));
unsigned char PchrblackboxZ[2176] __attribute__((aligned(16)));
unsigned char PchrblueprintsZ[336] __attribute__((aligned(16)));
unsigned char PchrbombcaseZ[496] __attribute__((aligned(16)));
unsigned char PchrbombdefuserZ[2272] __attribute__((aligned(16)));
unsigned char PchrbriefcaseZ[400] __attribute__((aligned(16)));
unsigned char PchrbugZ[3504] __attribute__((aligned(16)));
unsigned char PchrbugdetectorZ[368] __attribute__((aligned(16)));
unsigned char PchrbungeeZ[368] __attribute__((aligned(16)));
unsigned char PchrcameraZ[1680] __attribute__((aligned(16)));
unsigned char PchrcircuitboardZ[416] __attribute__((aligned(16)));
unsigned char PchrclipboardZ[640] __attribute__((aligned(16)));
unsigned char PchrcreditcardZ[368] __attribute__((aligned(16)));
unsigned char PchrdarkglassesZ[368] __attribute__((aligned(16)));
unsigned char PchrdatathiefZ[416] __attribute__((aligned(16)));
unsigned char PchrdattapeZ[496] __attribute__((aligned(16)));
unsigned char PchrdoordecoderZ[2144] __attribute__((aligned(16)));
unsigned char PchrdoorexploderZ[368] __attribute__((aligned(16)));
unsigned char PchrdossierredZ[1232] __attribute__((aligned(16)));
unsigned char PchrdynamiteZ[368] __attribute__((aligned(16)));
unsigned char PchrexplosivepenZ[368] __attribute__((aligned(16)));
unsigned char PchrextinguisherZ[1280] __attribute__((aligned(16)));
unsigned char PchrfingergunZ[368] __attribute__((aligned(16)));
unsigned char PchrflarepistolZ[368] __attribute__((aligned(16)));
unsigned char Pchrfnp90Z[1120] __attribute__((aligned(16)));
unsigned char PchrgaskeyringZ[3856] __attribute__((aligned(16)));
unsigned char PchrgoldbarZ[368] __attribute__((aligned(16)));
unsigned char PchrgoldenZ[624] __attribute__((aligned(16)));
unsigned char PchrgoldeneyekeyZ[3744] __attribute__((aligned(16)));
unsigned char PchrgoldwppkZ[368] __attribute__((aligned(16)));
unsigned char PchrgrenadeZ[880] __attribute__((aligned(16)));
unsigned char PchrgrenadelaunchZ[912] __attribute__((aligned(16)));
unsigned char PchrgrenaderoundZ[624] __attribute__((aligned(16)));
unsigned char PchrheroinZ[368] __attribute__((aligned(16)));
unsigned char PchrkalashZ[1008] __attribute__((aligned(16)));
unsigned char PchrkeyanalysercaseZ[496] __attribute__((aligned(16)));
unsigned char PchrkeyboltZ[3744] __attribute__((aligned(16)));
unsigned char PchrkeyyaleZ[5216] __attribute__((aligned(16)));
unsigned char PchrknifeZ[512] __attribute__((aligned(16)));
unsigned char PchrlaserZ[960] __attribute__((aligned(16)));
unsigned char PchrlectreZ[368] __attribute__((aligned(16)));
unsigned char PchrlockexploderZ[368] __attribute__((aligned(16)));
unsigned char Pchrm16Z[976] __attribute__((aligned(16)));
unsigned char PchrmapZ[336] __attribute__((aligned(16)));
unsigned char PchrmicrocameraZ[2288] __attribute__((aligned(16)));
unsigned char PchrmicrocodeZ[368] __attribute__((aligned(16)));
unsigned char PchrmicrofilmZ[368] __attribute__((aligned(16)));
unsigned char PchrmoneyZ[368] __attribute__((aligned(16)));
unsigned char Pchrmp5kZ[896] __attribute__((aligned(16)));
unsigned char Pchrmp5ksilZ[1040] __attribute__((aligned(16)));
unsigned char PchrpitongunZ[368] __attribute__((aligned(16)));
unsigned char PchrplansZ[656] __attribute__((aligned(16)));
unsigned char PchrplastiqueZ[1120] __attribute__((aligned(16)));
unsigned char PchrpolarizedglassesZ[2240] __attribute__((aligned(16)));
unsigned char PchrproximitymineZ[1120] __attribute__((aligned(16)));
unsigned char PchrremotemineZ[1120] __attribute__((aligned(16)));
unsigned char PchrrocketZ[1456] __attribute__((aligned(16)));
unsigned char PchrrocketlaunchZ[992] __attribute__((aligned(16)));
unsigned char PchrrugerZ[992] __attribute__((aligned(16)));
unsigned char PchrsafecrackercaseZ[496] __attribute__((aligned(16)));
unsigned char PchrshotgunZ[848] __attribute__((aligned(16)));
unsigned char PchrsilverwppkZ[368] __attribute__((aligned(16)));
unsigned char PchrskorpionZ[896] __attribute__((aligned(16)));
unsigned char PchrsniperrifleZ[912] __attribute__((aligned(16)));
unsigned char PchrspectreZ[880] __attribute__((aligned(16)));
unsigned char PchrspooltapeZ[368] __attribute__((aligned(16)));
unsigned char PchrspyfileZ[368] __attribute__((aligned(16)));
unsigned char PchrstafflistZ[544] __attribute__((aligned(16)));
unsigned char PchrtesttubeZ[448] __attribute__((aligned(16)));
unsigned char PchrthrowknifeZ[544] __attribute__((aligned(16)));
unsigned char PchrtimedmineZ[1328] __attribute__((aligned(16)));
unsigned char Pchrtt33Z[656] __attribute__((aligned(16)));
unsigned char PchruziZ[720] __attribute__((aligned(16)));
unsigned char PchrvideotapeZ[720] __attribute__((aligned(16)));
unsigned char PchrweaponcaseZ[512] __attribute__((aligned(16)));
unsigned char PchrwppkZ[576] __attribute__((aligned(16)));
unsigned char PchrwppksilZ[736] __attribute__((aligned(16)));
unsigned char PchrwristdartZ[368] __attribute__((aligned(16)));
unsigned char Pconsole1Z[1664] __attribute__((aligned(16)));
unsigned char Pconsole2Z[1664] __attribute__((aligned(16)));
unsigned char Pconsole3Z[1680] __attribute__((aligned(16)));
unsigned char Pconsole_sev2aZ[1056] __attribute__((aligned(16)));
unsigned char Pconsole_sev2bZ[1216] __attribute__((aligned(16)));
unsigned char Pconsole_sev2cZ[1088] __attribute__((aligned(16)));
unsigned char Pconsole_sev2dZ[1072] __attribute__((aligned(16)));
unsigned char Pconsole_sev_GEaZ[1072] __attribute__((aligned(16)));
unsigned char Pconsole_sev_GEbZ[1072] __attribute__((aligned(16)));
unsigned char Pconsole_sevaZ[1152] __attribute__((aligned(16)));
unsigned char Pconsole_sevbZ[1136] __attribute__((aligned(16)));
unsigned char Pconsole_sevcZ[1072] __attribute__((aligned(16)));
unsigned char Pconsole_sevdZ[1072] __attribute__((aligned(16)));
unsigned char Pcryptdoor1aZ[400] __attribute__((aligned(16)));
unsigned char Pcryptdoor1bZ[400] __attribute__((aligned(16)));
unsigned char Pcryptdoor2aZ[400] __attribute__((aligned(16)));
unsigned char Pcryptdoor2bZ[400] __attribute__((aligned(16)));
unsigned char Pcryptdoor3Z[624] __attribute__((aligned(16)));
unsigned char Pcryptdoor4Z[384] __attribute__((aligned(16)));
unsigned char PdamchaindoorZ[640] __attribute__((aligned(16)));
unsigned char PdamgatedoorZ[544] __attribute__((aligned(16)));
unsigned char PdamtundoorZ[880] __attribute__((aligned(16)));
unsigned char Pdepot_door_steelZ[416] __attribute__((aligned(16)));
unsigned char Pdepot_gate_entryZ[576] __attribute__((aligned(16)));
unsigned char Pdesk1Z[384] __attribute__((aligned(16)));
unsigned char Pdesk2Z[384] __attribute__((aligned(16)));
unsigned char Pdesk_arecibo1Z[576] __attribute__((aligned(16)));
unsigned char Pdesk_lamp2Z[768] __attribute__((aligned(16)));
unsigned char Pdest_engineZ[6384] __attribute__((aligned(16)));
unsigned char Pdest_exocetZ[1632] __attribute__((aligned(16)));
unsigned char Pdest_gunZ[1648] __attribute__((aligned(16)));
unsigned char Pdest_harpoonZ[2208] __attribute__((aligned(16)));
unsigned char Pdest_seawolfZ[4016] __attribute__((aligned(16)));
unsigned char Pdisc_readerZ[448] __attribute__((aligned(16)));
unsigned char Pdisk_drive1Z[400] __attribute__((aligned(16)));
unsigned char Pdoor_azt_chairZ[384] __attribute__((aligned(16)));
unsigned char Pdoor_azt_deskZ[1088] __attribute__((aligned(16)));
unsigned char Pdoor_azt_desk_topZ[912] __attribute__((aligned(16)));
unsigned char Pdoor_aztecZ[560] __attribute__((aligned(16)));
unsigned char Pdoor_dest1Z[768] __attribute__((aligned(16)));
unsigned char Pdoor_dest2Z[960] __attribute__((aligned(16)));
unsigned char Pdoor_eyelidZ[1376] __attribute__((aligned(16)));
unsigned char Pdoor_irisZ[2640] __attribute__((aligned(16)));
unsigned char Pdoor_mfZ[752] __attribute__((aligned(16)));
unsigned char Pdoor_roller1Z[880] __attribute__((aligned(16)));
unsigned char Pdoor_roller2Z[576] __attribute__((aligned(16)));
unsigned char Pdoor_roller3Z[576] __attribute__((aligned(16)));
unsigned char Pdoor_roller4Z[608] __attribute__((aligned(16)));
unsigned char Pdoor_rollertrainZ[304] __attribute__((aligned(16)));
unsigned char Pdoor_st_arec1Z[608] __attribute__((aligned(16)));
unsigned char Pdoor_st_arec2Z[736] __attribute__((aligned(16)));
unsigned char Pdoor_winZ[416] __attribute__((aligned(16)));
unsigned char PdoorconsoleZ[1136] __attribute__((aligned(16)));
unsigned char PdoorpanelZ[880] __attribute__((aligned(16)));
unsigned char Pdoorprison1Z[336] __attribute__((aligned(16)));
unsigned char PdoorstatgateZ[512] __attribute__((aligned(16)));
unsigned char PexplosionbitZ[288] __attribute__((aligned(16)));
unsigned char Pfiling_cabinet1Z[384] __attribute__((aligned(16)));
unsigned char PflagZ[304] __attribute__((aligned(16)));
unsigned char PfloppyZ[800] __attribute__((aligned(16)));
unsigned char Pfnp90magZ[416] __attribute__((aligned(16)));
unsigned char Pgas_plant_met1_do1Z[896] __attribute__((aligned(16)));
unsigned char Pgas_plant_sw2_do1Z[480] __attribute__((aligned(16)));
unsigned char Pgas_plant_sw3_do1Z[512] __attribute__((aligned(16)));
unsigned char Pgas_plant_sw4_do1Z[352] __attribute__((aligned(16)));
unsigned char Pgas_plant_sw_do1Z[656] __attribute__((aligned(16)));
unsigned char Pgas_plant_wc_cub1Z[528] __attribute__((aligned(16)));
unsigned char PgasbarrelZ[528] __attribute__((aligned(16)));
unsigned char PgasbarrelsZ[1344] __attribute__((aligned(16)));
unsigned char Pgasplant_clear_doorZ[1376] __attribute__((aligned(16)));
unsigned char PgastankZ[1456] __attribute__((aligned(16)));
unsigned char Pglassware1Z[352] __attribute__((aligned(16)));
unsigned char Pglassware2Z[656] __attribute__((aligned(16)));
unsigned char Pglassware3Z[528] __attribute__((aligned(16)));
unsigned char Pglassware4Z[1408] __attribute__((aligned(16)));
unsigned char PgoldeneyelogoZ[3760] __attribute__((aligned(16)));
unsigned char PgoldenshellsZ[512] __attribute__((aligned(16)));
unsigned char PgroundgunZ[2000] __attribute__((aligned(16)));
unsigned char Pgun_runway1Z[1856] __attribute__((aligned(16)));
unsigned char PhatberetZ[672] __attribute__((aligned(16)));
unsigned char PhatberetblueZ[720] __attribute__((aligned(16)));
unsigned char PhatberetredZ[736] __attribute__((aligned(16)));
unsigned char PhatchboltZ[208] __attribute__((aligned(16)));
unsigned char PhatchdoorZ[544] __attribute__((aligned(16)));
unsigned char PhatchsevxZ[368] __attribute__((aligned(16)));
unsigned char PhatfurryZ[560] __attribute__((aligned(16)));
unsigned char PhatfurryblackZ[544] __attribute__((aligned(16)));
unsigned char PhatfurrybrownZ[528] __attribute__((aligned(16)));
unsigned char PhathelmetZ[560] __attribute__((aligned(16)));
unsigned char PhathelmetgreyZ[560] __attribute__((aligned(16)));
unsigned char PhatmoonZ[992] __attribute__((aligned(16)));
unsigned char PhatpeakedZ[784] __attribute__((aligned(16)));
unsigned char PhattbirdZ[592] __attribute__((aligned(16)));
unsigned char PhattbirdbrownZ[624] __attribute__((aligned(16)));
unsigned char PhelicopterZ[16928] __attribute__((aligned(16)));
unsigned char PhindZ[6000] __attribute__((aligned(16)));
unsigned char PjeepZ[4448] __attribute__((aligned(16)));
unsigned char Pjerry_can1Z[608] __attribute__((aligned(16)));
unsigned char Pjungle3_treeZ[1920] __attribute__((aligned(16)));
unsigned char Pjungle5_treeZ[1328] __attribute__((aligned(16)));
unsigned char Pkey_holderZ[848] __attribute__((aligned(16)));
unsigned char Pkeyboard1Z[368] __attribute__((aligned(16)));
unsigned char Pkit_units1Z[672] __attribute__((aligned(16)));
unsigned char PlabbenchZ[976] __attribute__((aligned(16)));
unsigned char PlandmineZ[624] __attribute__((aligned(16)));
unsigned char PlegalpageZ[4032] __attribute__((aligned(16)));
unsigned char Pletter_tray1Z[352] __attribute__((aligned(16)));
unsigned char Plocker3Z[400] __attribute__((aligned(16)));
unsigned char Plocker4Z[400] __attribute__((aligned(16)));
unsigned char Pm16magZ[320] __attribute__((aligned(16)));
unsigned char PmagnumshellsZ[512] __attribute__((aligned(16)));
unsigned char Pmainframe1Z[768] __attribute__((aligned(16)));
unsigned char Pmainframe2Z[720] __attribute__((aligned(16)));
unsigned char Pmetal_chair1Z[832] __attribute__((aligned(16)));
unsigned char Pmetal_crate1Z[448] __attribute__((aligned(16)));
unsigned char Pmetal_crate2Z[448] __attribute__((aligned(16)));
unsigned char Pmetal_crate3Z[448] __attribute__((aligned(16)));
unsigned char Pmetal_crate4Z[448] __attribute__((aligned(16)));
unsigned char PmilcopterZ[6368] __attribute__((aligned(16)));
unsigned char PmiltruckZ[8960] __attribute__((aligned(16)));
unsigned char Pmissile_rack2Z[2576] __attribute__((aligned(16)));
unsigned char Pmissile_rackZ[992] __attribute__((aligned(16)));
unsigned char PmodemboxZ[832] __attribute__((aligned(16)));
unsigned char PmotorbikeZ[3776] __attribute__((aligned(16)));
unsigned char Pmp5kmagZ[336] __attribute__((aligned(16)));
unsigned char PnintendologoZ[10976] __attribute__((aligned(16)));
unsigned char Poil_drum1Z[624] __attribute__((aligned(16)));
unsigned char Poil_drum2Z[752] __attribute__((aligned(16)));
unsigned char Poil_drum3Z[752] __attribute__((aligned(16)));
unsigned char Poil_drum5Z[752] __attribute__((aligned(16)));
unsigned char Poil_drum6Z[784] __attribute__((aligned(16)));
unsigned char Poil_drum7Z[768] __attribute__((aligned(16)));
unsigned char PpadlockZ[2640] __attribute__((aligned(16)));
unsigned char PpalmZ[1104] __attribute__((aligned(16)));
unsigned char PpalmtreeZ[1232] __attribute__((aligned(16)));
unsigned char Pphone1Z[320] __attribute__((aligned(16)));
unsigned char PplaneZ[9696] __attribute__((aligned(16)));
unsigned char Pplant11Z[960] __attribute__((aligned(16)));
unsigned char Pplant1Z[912] __attribute__((aligned(16)));
unsigned char Pplant2Z[864] __attribute__((aligned(16)));
unsigned char Pplant2bZ[1040] __attribute__((aligned(16)));
unsigned char Pplant3Z[1104] __attribute__((aligned(16)));
unsigned char Pradio_unit1Z[432] __attribute__((aligned(16)));
unsigned char Pradio_unit2Z[448] __attribute__((aligned(16)));
unsigned char Pradio_unit3Z[448] __attribute__((aligned(16)));
unsigned char Pradio_unit4Z[448] __attribute__((aligned(16)));
unsigned char ProofgunZ[1632] __attribute__((aligned(16)));
unsigned char PsafeZ[848] __attribute__((aligned(16)));
unsigned char PsafedoorZ[1264] __attribute__((aligned(16)));
unsigned char Psat1_reflectZ[5488] __attribute__((aligned(16)));
unsigned char PsatboxZ[288] __attribute__((aligned(16)));
unsigned char PsatdishZ[1120] __attribute__((aligned(16)));
unsigned char Psec_panelZ[416] __attribute__((aligned(16)));
unsigned char Psev_door3Z[656] __attribute__((aligned(16)));
unsigned char Psev_door3_windZ[912] __attribute__((aligned(16)));
unsigned char Psev_door4_windZ[992] __attribute__((aligned(16)));
unsigned char Psev_doorZ[848] __attribute__((aligned(16)));
unsigned char Psev_door_v1Z[816] __attribute__((aligned(16)));
unsigned char Psev_trislideZ[944] __attribute__((aligned(16)));
unsigned char PsevdishZ[3872] __attribute__((aligned(16)));
unsigned char PsevdoormetslideZ[736] __attribute__((aligned(16)));
unsigned char PsevdoornowindZ[368] __attribute__((aligned(16)));
unsigned char PsevdoorwindZ[1072] __attribute__((aligned(16)));
unsigned char PsevdoorwoodZ[944] __attribute__((aligned(16)));
unsigned char PshuttleZ[10752] __attribute__((aligned(16)));
unsigned char Pshuttle_door_lZ[3120] __attribute__((aligned(16)));
unsigned char Pshuttle_door_rZ[3328] __attribute__((aligned(16)));
unsigned char PsilencerZ[416] __attribute__((aligned(16)));
unsigned char Psilo_lift_doorZ[576] __attribute__((aligned(16)));
unsigned char PsilotopdoorZ[752] __attribute__((aligned(16)));
unsigned char PskorpionmagZ[352] __attribute__((aligned(16)));
unsigned char PspectremagZ[368] __attribute__((aligned(16)));
unsigned char PspeedboatZ[3392] __attribute__((aligned(16)));
unsigned char Pst_pete_room_1iZ[12608] __attribute__((aligned(16)));
unsigned char Pst_pete_room_2iZ[12768] __attribute__((aligned(16)));
unsigned char Pst_pete_room_3tZ[12096] __attribute__((aligned(16)));
unsigned char Pst_pete_room_5cZ[13712] __attribute__((aligned(16)));
unsigned char Pst_pete_room_6cZ[13328] __attribute__((aligned(16)));
unsigned char Psteel_door1Z[624] __attribute__((aligned(16)));
unsigned char Psteel_door2Z[688] __attribute__((aligned(16)));
unsigned char Psteel_door2bZ[720] __attribute__((aligned(16)));
unsigned char Psteel_door3Z[720] __attribute__((aligned(16)));
unsigned char Pstool1Z[704] __attribute__((aligned(16)));
unsigned char Pswipe_card2Z[400] __attribute__((aligned(16)));
unsigned char Pswivel_chair1Z[656] __attribute__((aligned(16)));
unsigned char PtankZ[6816] __attribute__((aligned(16)));
unsigned char PtigerZ[7824] __attribute__((aligned(16)));
unsigned char Ptorpedo_rackZ[2176] __attribute__((aligned(16)));
unsigned char Ptrain_door2Z[976] __attribute__((aligned(16)));
unsigned char Ptrain_door3Z[1056] __attribute__((aligned(16)));
unsigned char Ptrain_doorZ[624] __attribute__((aligned(16)));
unsigned char PtrainextdoorZ[832] __attribute__((aligned(16)));
unsigned char Ptt33magZ[320] __attribute__((aligned(16)));
unsigned char Ptuning_console1Z[1312] __attribute__((aligned(16)));
unsigned char Ptv1Z[464] __attribute__((aligned(16)));
unsigned char Ptv4screenZ[416] __attribute__((aligned(16)));
unsigned char Ptv_holderZ[1744] __attribute__((aligned(16)));
unsigned char PtvscreenZ[208] __attribute__((aligned(16)));
unsigned char PuzimagZ[320] __attribute__((aligned(16)));
unsigned char PvertdoorZ[1552] __attribute__((aligned(16)));
unsigned char PwalletbondZ[5552] __attribute__((aligned(16)));
unsigned char PwindowZ[240] __attribute__((aligned(16)));
unsigned char Pwindow_cor11Z[224] __attribute__((aligned(16)));
unsigned char Pwindow_lib_lg1Z[224] __attribute__((aligned(16)));
unsigned char Pwindow_lib_sm1Z[240] __attribute__((aligned(16)));
unsigned char Pwood_lg_crate1Z[640] __attribute__((aligned(16)));
unsigned char Pwood_lg_crate2Z[544] __attribute__((aligned(16)));
unsigned char Pwood_md_crate3Z[544] __attribute__((aligned(16)));
unsigned char Pwood_sm_crate4Z[608] __attribute__((aligned(16)));
unsigned char Pwood_sm_crate5Z[608] __attribute__((aligned(16)));
unsigned char Pwood_sm_crate6Z[544] __attribute__((aligned(16)));
unsigned char Pwooden_table1Z[880] __attribute__((aligned(16)));
unsigned char PwppkmagZ[320] __attribute__((aligned(16)));
unsigned char Tbg_ame_all_p_stanZ[6448] __attribute__((aligned(16)));
unsigned char Tbg_arch_all_p_stanZ[23792] __attribute__((aligned(16)));
unsigned char Tbg_arec_all_p_stanZ[33616] __attribute__((aligned(16)));
unsigned char Tbg_ark_all_p_stanZ[36800] __attribute__((aligned(16)));
unsigned char Tbg_ash_all_p_stanZ[6448] __attribute__((aligned(16)));
unsigned char Tbg_azt_all_p_stanZ[21888] __attribute__((aligned(16)));
unsigned char Tbg_cat_all_p_stanZ[10032] __attribute__((aligned(16)));
unsigned char Tbg_cave_all_p_stanZ[20208] __attribute__((aligned(16)));
unsigned char Tbg_crad_all_p_stanZ[10512] __attribute__((aligned(16)));
unsigned char Tbg_cryp_all_p_stanZ[12400] __attribute__((aligned(16)));
unsigned char Tbg_dam_all_p_stanZ[41952] __attribute__((aligned(16)));
unsigned char Tbg_depo_all_p_stanZ[28480] __attribute__((aligned(16)));
unsigned char Tbg_dest_all_p_stanZ[26864] __attribute__((aligned(16)));
unsigned char Tbg_dish_all_p_stanZ[2832] __attribute__((aligned(16)));
unsigned char Tbg_imp_all_p_stanZ[6448] __attribute__((aligned(16)));
unsigned char Tbg_jun_all_p_stanZ[29008] __attribute__((aligned(16)));
unsigned char Tbg_len_all_p_stanZ[2752] __attribute__((aligned(16)));
unsigned char Tbg_oat_all_p_stanZ[6400] __attribute__((aligned(16)));
unsigned char Tbg_pete_all_p_stanZ[18064] __attribute__((aligned(16)));
unsigned char Tbg_ref_all_p_stanZ[7632] __attribute__((aligned(16)));
unsigned char Tbg_run_all_p_stanZ[6784] __attribute__((aligned(16)));
unsigned char Tbg_sev_all_p_stanZ[15824] __attribute__((aligned(16)));
unsigned char Tbg_sevb_all_p_stanZ[20288] __attribute__((aligned(16)));
unsigned char Tbg_sevx_all_p_stanZ[37680] __attribute__((aligned(16)));
unsigned char Tbg_silo_all_p_stanZ[37024] __attribute__((aligned(16)));
unsigned char Tbg_stat_all_p_stanZ[20160] __attribute__((aligned(16)));
unsigned char Tbg_tra_all_p_stanZ[9168] __attribute__((aligned(16)));
unsigned char UbriefarchZ[32] __attribute__((aligned(16)));
unsigned char UbriefarkZ[32] __attribute__((aligned(16)));
unsigned char UbriefaztZ[32] __attribute__((aligned(16)));
unsigned char UbriefcaveZ[32] __attribute__((aligned(16)));
unsigned char UbriefcontrolZ[32] __attribute__((aligned(16)));
unsigned char UbriefcradZ[32] __attribute__((aligned(16)));
unsigned char UbriefcrypZ[32] __attribute__((aligned(16)));
unsigned char UbriefdamZ[32] __attribute__((aligned(16)));
unsigned char UbriefdepoZ[32] __attribute__((aligned(16)));
unsigned char UbriefdestZ[32] __attribute__((aligned(16)));
unsigned char UbriefjunZ[32] __attribute__((aligned(16)));
unsigned char UbriefpeteZ[32] __attribute__((aligned(16)));
unsigned char UbriefrunZ[32] __attribute__((aligned(16)));
unsigned char UbriefsevbZ[32] __attribute__((aligned(16)));
unsigned char UbriefsevbunkerZ[32] __attribute__((aligned(16)));
unsigned char UbriefsevxZ[32] __attribute__((aligned(16)));
unsigned char UbriefsevxbZ[32] __attribute__((aligned(16)));
unsigned char UbriefsiloZ[32] __attribute__((aligned(16)));
unsigned char UbriefstatueZ[32] __attribute__((aligned(16)));
unsigned char UbrieftraZ[32] __attribute__((aligned(16)));
unsigned char Ump_setupameZ[1824] __attribute__((aligned(16)));
unsigned char Ump_setuparchZ[11680] __attribute__((aligned(16)));
unsigned char Ump_setuparkZ[7488] __attribute__((aligned(16)));
unsigned char Ump_setupashZ[1776] __attribute__((aligned(16)));
unsigned char Ump_setupcaveZ[9568] __attribute__((aligned(16)));
unsigned char Ump_setupcradZ[2400] __attribute__((aligned(16)));
unsigned char Ump_setupcrypZ[3424] __attribute__((aligned(16)));
unsigned char Ump_setupdishZ[1008] __attribute__((aligned(16)));
unsigned char Ump_setupimpZ[1600] __attribute__((aligned(16)));
unsigned char Ump_setupoatZ[848] __attribute__((aligned(16)));
unsigned char Ump_setuprefZ[1040] __attribute__((aligned(16)));
unsigned char Ump_setupsevbZ[4880] __attribute__((aligned(16)));
unsigned char Ump_setupstatueZ[3712] __attribute__((aligned(16)));
unsigned char UsetuparchZ[17936] __attribute__((aligned(16)));
unsigned char UsetuparkZ[15248] __attribute__((aligned(16)));
unsigned char UsetupaztZ[10496] __attribute__((aligned(16)));
unsigned char UsetupcaveZ[15968] __attribute__((aligned(16)));
unsigned char UsetupcontrolZ[15104] __attribute__((aligned(16)));
unsigned char UsetupcradZ[7216] __attribute__((aligned(16)));
unsigned char UsetupcrypZ[7824] __attribute__((aligned(16)));
unsigned char UsetupdamZ[17104] __attribute__((aligned(16)));
unsigned char UsetupdepoZ[12176] __attribute__((aligned(16)));
unsigned char UsetupdestZ[9040] __attribute__((aligned(16)));
unsigned char UsetupjunZ[14080] __attribute__((aligned(16)));
unsigned char UsetuplenZ[1488] __attribute__((aligned(16)));
unsigned char UsetuppeteZ[12160] __attribute__((aligned(16)));
unsigned char UsetuprunZ[6240] __attribute__((aligned(16)));
unsigned char UsetupsevbZ[9824] __attribute__((aligned(16)));
unsigned char UsetupsevbunkerZ[6704] __attribute__((aligned(16)));
unsigned char UsetupsevxZ[17168] __attribute__((aligned(16)));
unsigned char UsetupsevxbZ[16624] __attribute__((aligned(16)));
unsigned char UsetupsiloZ[10832] __attribute__((aligned(16)));
unsigned char UsetupstatueZ[10192] __attribute__((aligned(16)));
unsigned char UsetuptraZ[12848] __attribute__((aligned(16)));
unsigned char bg_arch_all_p_seg[154352] __attribute__((aligned(16)));
unsigned char bg_arec_all_p_seg[189312] __attribute__((aligned(16)));
unsigned char bg_ark_all_p_seg[200576] __attribute__((aligned(16)));
unsigned char bg_azt_all_p_seg[137808] __attribute__((aligned(16)));
unsigned char bg_cat_all_p_seg[21808] __attribute__((aligned(16)));
unsigned char bg_cave_all_p_seg[148720] __attribute__((aligned(16)));
unsigned char bg_crad_all_p_seg[66384] __attribute__((aligned(16)));
unsigned char bg_cryp_all_p_seg[87728] __attribute__((aligned(16)));
unsigned char bg_dam_all_p_seg[197024] __attribute__((aligned(16)));
unsigned char bg_depo_all_p_seg[182640] __attribute__((aligned(16)));
unsigned char bg_dest_all_p_seg[186816] __attribute__((aligned(16)));
unsigned char bg_dish_all_p_seg[18544] __attribute__((aligned(16)));
unsigned char bg_ear_all_p_seg[1] __attribute__((aligned(16)));
unsigned char bg_imp_all_p_seg[1] __attribute__((aligned(16)));
unsigned char bg_jun_all_p_seg[86352] __attribute__((aligned(16)));
unsigned char bg_lee_all_p_seg[1] __attribute__((aligned(16)));
unsigned char bg_len_all_p_seg[4000] __attribute__((aligned(16)));
unsigned char bg_lip_all_p_seg[1] __attribute__((aligned(16)));
unsigned char bg_oat_all_p_seg[28240] __attribute__((aligned(16)));
unsigned char bg_pam_all_p_seg[9344] __attribute__((aligned(16)));
unsigned char bg_pete_all_p_seg[105520] __attribute__((aligned(16)));
unsigned char bg_ref_all_p_seg[38416] __attribute__((aligned(16)));
unsigned char bg_rit_all_p_seg[1] __attribute__((aligned(16)));
unsigned char bg_run_all_p_seg[41936] __attribute__((aligned(16)));
unsigned char bg_sev_all_p_seg[69104] __attribute__((aligned(16)));
unsigned char bg_sevb_all_p_seg[109984] __attribute__((aligned(16)));
unsigned char bg_sevx_all_p_seg[116176] __attribute__((aligned(16)));
unsigned char bg_sho_all_p_seg[1] __attribute__((aligned(16)));
unsigned char bg_silo_all_p_seg[331584] __attribute__((aligned(16)));
unsigned char bg_stat_all_p_seg[139472] __attribute__((aligned(16)));
unsigned char bg_tra_all_p_seg[132464] __attribute__((aligned(16)));
unsigned char bg_wax_all_p_seg[9344] __attribute__((aligned(16)));
unsigned char ob__ob_end_seg[16] __attribute__((aligned(16)));
unsigned char ramrom_BunkerI_1[13200] __attribute__((aligned(16)));
unsigned char ramrom_BunkerI_2[21120] __attribute__((aligned(16)));
unsigned char ramrom_Dam_1[20992] __attribute__((aligned(16)));
unsigned char ramrom_Dam_2[8144] __attribute__((aligned(16)));
unsigned char ramrom_Facility_1[6832] __attribute__((aligned(16)));
unsigned char ramrom_Facility_2[9184] __attribute__((aligned(16)));
unsigned char ramrom_Facility_3[7280] __attribute__((aligned(16)));
unsigned char ramrom_Frigate_1[6576] __attribute__((aligned(16)));
unsigned char ramrom_Frigate_2[13536] __attribute__((aligned(16)));
unsigned char ramrom_Runway_1[10064] __attribute__((aligned(16)));
unsigned char ramrom_Runway_2[10512] __attribute__((aligned(16)));
unsigned char ramrom_Silo_1[8592] __attribute__((aligned(16)));
unsigned char ramrom_Silo_2[8144] __attribute__((aligned(16)));
unsigned char ramrom_Train[15856] __attribute__((aligned(16)));
unsigned char unknown2[107904] __attribute__((aligned(16)));

const GeAssetEntry ge_asset_manifest[] = {
    { "CarmourguardZ", CarmourguardZ, 9344u, 0x006ECB90u },
    { "CbaronsamediZ", CbaronsamediZ, 14064u, 0x006EF010u },
    { "CbluecamguardZ", CbluecamguardZ, 9968u, 0x006F2700u },
    { "CbluemanZ", CbluemanZ, 7696u, 0x006F4DF0u },
    { "CbluewomanZ", CbluewomanZ, 7872u, 0x006F6C00u },
    { "CboilerbondZ", CboilerbondZ, 11280u, 0x006F8AC0u },
    { "CboilertrevZ", CboilertrevZ, 13952u, 0x006FB6D0u },
    { "CborisZ", CborisZ, 12576u, 0x006FED50u },
    { "CcamguardZ", CcamguardZ, 9952u, 0x00701E70u },
    { "CcardimanZ", CcardimanZ, 7680u, 0x00704550u },
    { "CcheckmanZ", CcheckmanZ, 7808u, 0x00706350u },
    { "CcommguardZ", CcommguardZ, 9728u, 0x007081D0u },
    { "CdjbondZ", CdjbondZ, 11920u, 0x0070A7D0u },
    { "CfattechwomanZ", CfattechwomanZ, 7968u, 0x0070D660u },
    { "Cgreatguard2Z", Cgreatguard2Z, 10016u, 0x0070F580u },
    { "CgreatguardZ", CgreatguardZ, 9856u, 0x00711CA0u },
    { "CgreyguardZ", CgreyguardZ, 9936u, 0x00714320u },
    { "CgreymanZ", CgreymanZ, 7616u, 0x007169F0u },
    { "CheadalanZ", CheadalanZ, 1488u, 0x007187B0u },
    { "CheadbZ", CheadbZ, 1392u, 0x00718D80u },
    { "CheadbalaclavaZ", CheadbalaclavaZ, 976u, 0x007192F0u },
    { "CheadbikeZ", CheadbikeZ, 1696u, 0x007196C0u },
    { "CheadbrosnanZ", CheadbrosnanZ, 3408u, 0x00719D60u },
    { "CheadbrosnanboilerZ", CheadbrosnanboilerZ, 2976u, 0x0071AAB0u },
    { "CheadbrosnansnowZ", CheadbrosnansnowZ, 3712u, 0x0071B650u },
    { "CheadbrosnansuitZ", CheadbrosnansuitZ, 3456u, 0x0071C4D0u },
    { "CheadbrosnantimberZ", CheadbrosnantimberZ, 3008u, 0x0071D250u },
    { "CheadchrisZ", CheadchrisZ, 1344u, 0x0071DE10u },
    { "CheaddaveZ", CheaddaveZ, 1408u, 0x0071E350u },
    { "CheaddesZ", CheaddesZ, 1328u, 0x0071E8D0u },
    { "CheadduncanZ", CheadduncanZ, 1312u, 0x0071EE00u },
    { "CheaddwayneZ", CheaddwayneZ, 1408u, 0x0071F320u },
    { "CheadgrahamZ", CheadgrahamZ, 1392u, 0x0071F8A0u },
    { "CheadgrantZ", CheadgrantZ, 1328u, 0x0071FE10u },
    { "CheadjimZ", CheadjimZ, 1328u, 0x00720340u },
    { "Cheadjoe2Z", Cheadjoe2Z, 1056u, 0x00720870u },
    { "CheadjoeZ", CheadjoeZ, 1392u, 0x00720C90u },
    { "CheadjoelZ", CheadjoelZ, 1296u, 0x00721200u },
    { "CheadkarlZ", CheadkarlZ, 1376u, 0x00721710u },
    { "CheadkenZ", CheadkenZ, 1360u, 0x00721C70u },
    { "CheadleeZ", CheadleeZ, 1408u, 0x007221C0u },
    { "CheadmandyZ", CheadmandyZ, 1008u, 0x00722740u },
    { "CheadmarionZ", CheadmarionZ, 1040u, 0x00722B30u },
    { "CheadmarkZ", CheadmarkZ, 1328u, 0x00722F40u },
    { "CheadmartinZ", CheadmartinZ, 1376u, 0x00723470u },
    { "CheadmishkinZ", CheadmishkinZ, 1376u, 0x007239D0u },
    { "CheadneilZ", CheadneilZ, 1312u, 0x00723F30u },
    { "CheadpeteZ", CheadpeteZ, 1424u, 0x00724450u },
    { "CheadrobinZ", CheadrobinZ, 1296u, 0x007249E0u },
    { "CheadsallyZ", CheadsallyZ, 1024u, 0x00724EF0u },
    { "CheadscottZ", CheadscottZ, 1408u, 0x007252F0u },
    { "CheadshaunZ", CheadshaunZ, 1504u, 0x00725870u },
    { "CheadsteveeZ", CheadsteveeZ, 1360u, 0x00725E50u },
    { "CheadstevehZ", CheadstevehZ, 1360u, 0x007263A0u },
    { "CheadvivienZ", CheadvivienZ, 1168u, 0x007268F0u },
    { "CjawsZ", CjawsZ, 11328u, 0x00726D80u },
    { "CjeanwomanZ", CjeanwomanZ, 8208u, 0x007299C0u },
    { "CmaydayZ", CmaydayZ, 11168u, 0x0072B9D0u },
    { "CmoonfemaleZ", CmoonfemaleZ, 8528u, 0x0072E570u },
    { "CmoonguardZ", CmoonguardZ, 9712u, 0x007306C0u },
    { "CnatalyaZ", CnatalyaZ, 14528u, 0x00732CB0u },
    { "CnavyguardZ", CnavyguardZ, 9952u, 0x00736570u },
    { "CoddjobZ", CoddjobZ, 12592u, 0x00738C50u },
    { "ColiveguardZ", ColiveguardZ, 9808u, 0x0073BD80u },
    { "CorumovZ", CorumovZ, 13360u, 0x0073E3D0u },
    { "CpilotZ", CpilotZ, 12416u, 0x00741800u },
    { "CredmanZ", CredmanZ, 10032u, 0x00744880u },
    { "CrusguardZ", CrusguardZ, 7216u, 0x00746FB0u },
    { "CsnowbondZ", CsnowbondZ, 13104u, 0x00748BE0u },
    { "CsnowguardZ", CsnowguardZ, 11392u, 0x0074BF10u },
    { "CspicebondZ", CspicebondZ, 14624u, 0x0074EB90u },
    { "Csuit_lf_handZ", Csuit_lf_handZ, 12832u, 0x007524B0u },
    { "CsuitbondZ", CsuitbondZ, 11664u, 0x007556D0u },
    { "CtechmanZ", CtechmanZ, 9904u, 0x00758460u },
    { "CtechwomanZ", CtechwomanZ, 8176u, 0x0075AB10u },
    { "CtimberbondZ", CtimberbondZ, 11568u, 0x0075CB00u },
    { "CtrevelyanZ", CtrevelyanZ, 14288u, 0x0075F830u },
    { "CtrevguardZ", CtrevguardZ, 9744u, 0x00763000u },
    { "CvalentinZ", CvalentinZ, 12144u, 0x00765610u },
    { "CxeniaZ", CxeniaZ, 14832u, 0x00768580u },
    { "Gak47Z", Gak47Z, 2576u, 0x0076BF70u },
    { "GaudiotapeZ", GaudiotapeZ, 912u, 0x0076C980u },
    { "GautoshotZ", GautoshotZ, 6160u, 0x0076CD10u },
    { "GblackboxZ", GblackboxZ, 1536u, 0x0076E520u },
    { "GblueprintsZ", GblueprintsZ, 256u, 0x0076EB20u },
    { "GbombcaseZ", GbombcaseZ, 1936u, 0x0076EC20u },
    { "GbombdefuserZ", GbombdefuserZ, 1520u, 0x0076F3B0u },
    { "GbriefcaseZ", GbriefcaseZ, 1936u, 0x0076F9A0u },
    { "GbugZ", GbugZ, 2416u, 0x00770130u },
    { "GbugdetectorZ", GbugdetectorZ, 848u, 0x00770AA0u },
    { "GbungeeZ", GbungeeZ, 848u, 0x00770DF0u },
    { "GcameraZ", GcameraZ, 1152u, 0x00771140u },
    { "GcartblueZ", GcartblueZ, 608u, 0x007715C0u },
    { "GcartridgeZ", GcartridgeZ, 304u, 0x00771820u },
    { "GcartrifleZ", GcartrifleZ, 528u, 0x00771950u },
    { "GcartshellZ", GcartshellZ, 512u, 0x00771B60u },
    { "GcircuitboardZ", GcircuitboardZ, 320u, 0x00771D60u },
    { "GclipboardZ", GclipboardZ, 496u, 0x00771EA0u },
    { "GcreditcardZ", GcreditcardZ, 848u, 0x00772090u },
    { "GdarkglassesZ", GdarkglassesZ, 848u, 0x007723E0u },
    { "GdatathiefZ", GdatathiefZ, 320u, 0x00772730u },
    { "GdattapeZ", GdattapeZ, 368u, 0x00772870u },
    { "GdoordecoderZ", GdoordecoderZ, 1408u, 0x007729E0u },
    { "GdoorexploderZ", GdoorexploderZ, 848u, 0x00772F60u },
    { "GdossierredZ", GdossierredZ, 864u, 0x007732B0u },
    { "GdynamiteZ", GdynamiteZ, 848u, 0x00773610u },
    { "GexplosivefloppyZ", GexplosivefloppyZ, 592u, 0x00773960u },
    { "GexplosivepenZ", GexplosivepenZ, 848u, 0x00773BB0u },
    { "GextinguisherZ", GextinguisherZ, 2032u, 0x00773F00u },
    { "GfingergunZ", GfingergunZ, 848u, 0x007746F0u },
    { "GfistZ", GfistZ, 5888u, 0x00774A40u },
    { "GflarepistolZ", GflarepistolZ, 848u, 0x00776140u },
    { "Gfnp90Z", Gfnp90Z, 3232u, 0x00776490u },
    { "GgaskeyringZ", GgaskeyringZ, 2608u, 0x00777130u },
    { "GgoldbarZ", GgoldbarZ, 848u, 0x00777B60u },
    { "GgoldeneyekeyZ", GgoldeneyekeyZ, 2480u, 0x00777EB0u },
    { "GgoldengunZ", GgoldengunZ, 6112u, 0x00778860u },
    { "GgoldwppkZ", GgoldwppkZ, 6496u, 0x0077A040u },
    { "GgrenadeZ", GgrenadeZ, 2608u, 0x0077B9A0u },
    { "GgrenadelaunchZ", GgrenadelaunchZ, 4224u, 0x0077C3D0u },
    { "GheroinZ", GheroinZ, 848u, 0x0077D450u },
    { "GjoypadZ", GjoypadZ, 7856u, 0x0077D7A0u },
    { "GkeyanalysercaseZ", GkeyanalysercaseZ, 1936u, 0x0077F650u },
    { "GkeyboltZ", GkeyboltZ, 2544u, 0x0077FDE0u },
    { "GkeycardZ", GkeycardZ, 304u, 0x007807D0u },
    { "GkeyyaleZ", GkeyyaleZ, 3408u, 0x00780900u },
    { "GknifeZ", GknifeZ, 6864u, 0x00781650u },
    { "GlaserZ", GlaserZ, 3568u, 0x00783120u },
    { "GlectreZ", GlectreZ, 848u, 0x00783F10u },
    { "GlockexploderZ", GlockexploderZ, 848u, 0x00784260u },
    { "Gm16Z", Gm16Z, 2592u, 0x007845B0u },
    { "GmapZ", GmapZ, 240u, 0x00784FD0u },
    { "GmicrocameraZ", GmicrocameraZ, 1600u, 0x007850C0u },
    { "GmicrocodeZ", GmicrocodeZ, 848u, 0x00785700u },
    { "GmicrofilmZ", GmicrofilmZ, 848u, 0x00785A50u },
    { "GmoneyZ", GmoneyZ, 848u, 0x00785DA0u },
    { "Gmp5kZ", Gmp5kZ, 3040u, 0x007860F0u },
    { "Gmp5ksilZ", Gmp5ksilZ, 3328u, 0x00786CD0u },
    { "GpitongunZ", GpitongunZ, 848u, 0x007879D0u },
    { "GplansZ", GplansZ, 464u, 0x00787D20u },
    { "GplastiqueZ", GplastiqueZ, 848u, 0x00787EF0u },
    { "GpolarizedglassesZ", GpolarizedglassesZ, 1376u, 0x00788240u },
    { "GproximitymineZ", GproximitymineZ, 2032u, 0x007887A0u },
    { "GremotemineZ", GremotemineZ, 2496u, 0x00788F90u },
    { "GrocketlaunchZ", GrocketlaunchZ, 4640u, 0x00789950u },
    { "GrugerZ", GrugerZ, 7568u, 0x0078AB70u },
    { "GsafecrackercaseZ", GsafecrackercaseZ, 1936u, 0x0078C900u },
    { "GshotgunZ", GshotgunZ, 3808u, 0x0078D090u },
    { "GsilverwppkZ", GsilverwppkZ, 6496u, 0x0078DF70u },
    { "GskorpionZ", GskorpionZ, 4608u, 0x0078F8D0u },
    { "GsniperrifleZ", GsniperrifleZ, 4208u, 0x00790AD0u },
    { "GspectreZ", GspectreZ, 3200u, 0x00791B40u },
    { "GspooltapeZ", GspooltapeZ, 848u, 0x007927C0u },
    { "GspyfileZ", GspyfileZ, 848u, 0x00792B10u },
    { "GstafflistZ", GstafflistZ, 416u, 0x00792E60u },
    { "GtaserZ", GtaserZ, 7776u, 0x00793000u },
    { "GthrowknifeZ", GthrowknifeZ, 6896u, 0x00794E60u },
    { "GtimedmineZ", GtimedmineZ, 2752u, 0x00796950u },
    { "GtriggerZ", GtriggerZ, 13312u, 0x00797410u },
    { "Gtt33Z", Gtt33Z, 6944u, 0x0079A810u },
    { "GuziZ", GuziZ, 2320u, 0x0079C330u },
    { "GvideotapeZ", GvideotapeZ, 528u, 0x0079CC40u },
    { "GwatchcommunicatorZ", GwatchcommunicatorZ, 5216u, 0x0079CE50u },
    { "GwatchgeigercounterZ", GwatchgeigercounterZ, 5216u, 0x0079E2B0u },
    { "GwatchidentifierZ", GwatchidentifierZ, 5216u, 0x0079F710u },
    { "GwatchlaserZ", GwatchlaserZ, 13312u, 0x007A0B70u },
    { "GwatchmagnetattractZ", GwatchmagnetattractZ, 5200u, 0x007A3F70u },
    { "GwatchmagnetrepelZ", GwatchmagnetrepelZ, 5216u, 0x007A53C0u },
    { "GweaponcaseZ", GweaponcaseZ, 1936u, 0x007A6820u },
    { "GwppkZ", GwppkZ, 7312u, 0x007A6FB0u },
    { "GwppksilZ", GwppksilZ, 7488u, 0x007A8C40u },
    { "GwristdartZ", GwristdartZ, 848u, 0x007AA980u },
    { "LameE", LameE, 16u, 0x008E7410u },
    { "LameJ", LameJ, 16u, 0x008E7420u },
    { "LarchE", LarchE, 1584u, 0x008E7430u },
    { "LarchJ", LarchJ, 1632u, 0x008E7A60u },
    { "LarecE", LarecE, 1488u, 0x008E80C0u },
    { "LarecJ", LarecJ, 1424u, 0x008E8690u },
    { "LarkE", LarkE, 1696u, 0x008E8C20u },
    { "LarkJ", LarkJ, 1712u, 0x008E92C0u },
    { "LashE", LashE, 16u, 0x008E9970u },
    { "LashJ", LashJ, 16u, 0x008E9980u },
    { "LaztE", LaztE, 1088u, 0x008E9990u },
    { "LaztJ", LaztJ, 1200u, 0x008E9DD0u },
    { "LcatE", LcatE, 16u, 0x008EA280u },
    { "LcatJ", LcatJ, 16u, 0x008EA290u },
    { "LcaveE", LcaveE, 1024u, 0x008EA2A0u },
    { "LcaveJ", LcaveJ, 1120u, 0x008EA6A0u },
    { "LcradE", LcradE, 1232u, 0x008EAB00u },
    { "LcradJ", LcradJ, 1200u, 0x008EAFD0u },
    { "LcrypE", LcrypE, 592u, 0x008EB480u },
    { "LcrypJ", LcrypJ, 704u, 0x008EB6D0u },
    { "LdamE", LdamE, 1104u, 0x008EB990u },
    { "LdamJ", LdamJ, 1136u, 0x008EBDE0u },
    { "LdepoE", LdepoE, 880u, 0x008EC250u },
    { "LdepoJ", LdepoJ, 832u, 0x008EC5C0u },
    { "LdestE", LdestE, 1168u, 0x008EC900u },
    { "LdestJ", LdestJ, 1120u, 0x008ECD90u },
    { "LdishE", LdishE, 16u, 0x008ED1F0u },
    { "LdishJ", LdishJ, 16u, 0x008ED200u },
    { "LearE", LearE, 16u, 0x008ED210u },
    { "LearJ", LearJ, 16u, 0x008ED220u },
    { "LeldE", LeldE, 16u, 0x008ED230u },
    { "LeldJ", LeldJ, 16u, 0x008ED240u },
    { "LgunE", LgunE, 1824u, 0x008ED250u },
    { "LgunJ", LgunJ, 1872u, 0x008ED970u },
    { "LimpE", LimpE, 16u, 0x008EE0C0u },
    { "LimpJ", LimpJ, 16u, 0x008EE0D0u },
    { "LjunE", LjunE, 1312u, 0x008EE0E0u },
    { "LjunJ", LjunJ, 1344u, 0x008EE600u },
    { "LleeE", LleeE, 16u, 0x008EEB40u },
    { "LleeJ", LleeJ, 16u, 0x008EEB50u },
    { "LlenE", LlenE, 1600u, 0x008EEB60u },
    { "LlenJ", LlenJ, 688u, 0x008EF1A0u },
    { "LlipE", LlipE, 16u, 0x008EF450u },
    { "LlipJ", LlipJ, 16u, 0x008EF460u },
    { "LlueE", LlueE, 16u, 0x008EF470u },
    { "LlueJ", LlueJ, 16u, 0x008EF480u },
    { "LmiscE", LmiscE, 672u, 0x008EF490u },
    { "LmiscJ", LmiscJ, 736u, 0x008EF730u },
    { "LmpmenuE", LmpmenuE, 416u, 0x008EFA10u },
    { "LmpmenuJ", LmpmenuJ, 400u, 0x008EFBB0u },
    { "LmpweaponsE", LmpweaponsE, 192u, 0x008EFD40u },
    { "LmpweaponsJ", LmpweaponsJ, 224u, 0x008EFE00u },
    { "LoatE", LoatE, 16u, 0x008EFEE0u },
    { "LoatJ", LoatJ, 16u, 0x008EFEF0u },
    { "LoptionsE", LoptionsE, 560u, 0x008EFF00u },
    { "LoptionsJ", LoptionsJ, 592u, 0x008F0130u },
    { "LpamE", LpamE, 16u, 0x008F0380u },
    { "LpamJ", LpamJ, 16u, 0x008F0390u },
    { "LpeteE", LpeteE, 1152u, 0x008F03A0u },
    { "LpeteJ", LpeteJ, 1136u, 0x008F0820u },
    { "LpropobjE", LpropobjE, 672u, 0x008F0C90u },
    { "LpropobjJ", LpropobjJ, 704u, 0x008F0F30u },
    { "LrefE", LrefE, 16u, 0x008F11F0u },
    { "LrefJ", LrefJ, 16u, 0x008F1200u },
    { "LritE", LritE, 16u, 0x008F1210u },
    { "LritJ", LritJ, 16u, 0x008F1220u },
    { "LrunE", LrunE, 624u, 0x008F1230u },
    { "LrunJ", LrunJ, 656u, 0x008F14A0u },
    { "LsevE", LsevE, 1376u, 0x008F1730u },
    { "LsevJ", LsevJ, 1296u, 0x008F1C90u },
    { "LsevbE", LsevbE, 1872u, 0x008F21A0u },
    { "LsevbJ", LsevbJ, 2032u, 0x008F28F0u },
    { "LsevxE", LsevxE, 1120u, 0x008F30E0u },
    { "LsevxJ", LsevxJ, 960u, 0x008F3540u },
    { "LsevxbE", LsevxbE, 1168u, 0x008F3900u },
    { "LsevxbJ", LsevxbJ, 1104u, 0x008F3D90u },
    { "LshoE", LshoE, 16u, 0x008F41E0u },
    { "LshoJ", LshoJ, 16u, 0x008F41F0u },
    { "LsiloE", LsiloE, 1456u, 0x008F4200u },
    { "LsiloJ", LsiloJ, 1504u, 0x008F47B0u },
    { "LstatE", LstatE, 2336u, 0x008F4D90u },
    { "LstatJ", LstatJ, 2160u, 0x008F56B0u },
    { "LtitleE", LtitleE, 2752u, 0x008F5F20u },
    { "LtitleJ", LtitleJ, 2960u, 0x008F69E0u },
    { "LtraE", LtraE, 1072u, 0x008F7570u },
    { "LtraJ", LtraJ, 1056u, 0x008F79A0u },
    { "LwaxE", LwaxE, 16u, 0x008F7DC0u },
    { "LwaxJ", LwaxJ, 16u, 0x008F7DD0u },
    { "PICBMZ", PICBMZ, 9600u, 0x007AACD0u },
    { "PICBM_noseZ", PICBM_noseZ, 1968u, 0x007AD250u },
    { "Pak47magZ", Pak47magZ, 480u, 0x007ADA00u },
    { "Palarm1Z", Palarm1Z, 352u, 0x007ADBE0u },
    { "Palarm2Z", Palarm2Z, 416u, 0x007ADD40u },
    { "Pammo_crate1Z", Pammo_crate1Z, 576u, 0x007ADEE0u },
    { "Pammo_crate2Z", Pammo_crate2Z, 576u, 0x007AE120u },
    { "Pammo_crate3Z", Pammo_crate3Z, 592u, 0x007AE360u },
    { "Pammo_crate4Z", Pammo_crate4Z, 624u, 0x007AE5B0u },
    { "Pammo_crate5Z", Pammo_crate5Z, 704u, 0x007AE820u },
    { "PapcZ", PapcZ, 7264u, 0x007AEAE0u },
    { "Parchsecdoor1Z", Parchsecdoor1Z, 480u, 0x007B0740u },
    { "Parchsecdoor2Z", Parchsecdoor2Z, 464u, 0x007B0920u },
    { "ParticZ", ParticZ, 3584u, 0x007B0AF0u },
    { "PartictrailerZ", PartictrailerZ, 2320u, 0x007B18F0u },
    { "PbarricadeZ", PbarricadeZ, 576u, 0x007B2200u },
    { "Pbin1Z", Pbin1Z, 848u, 0x007B2440u },
    { "Pblotter1Z", Pblotter1Z, 224u, 0x007B2790u },
    { "PbodyarmourZ", PbodyarmourZ, 1184u, 0x007B2870u },
    { "PbodyarmourvestZ", PbodyarmourvestZ, 1056u, 0x007B2D10u },
    { "PbollardZ", PbollardZ, 512u, 0x007B3130u },
    { "PbombZ", PbombZ, 368u, 0x007B3330u },
    { "Pbook1Z", Pbook1Z, 400u, 0x007B34A0u },
    { "Pbookshelf1Z", Pbookshelf1Z, 1776u, 0x007B3630u },
    { "Pborg_crateZ", Pborg_crateZ, 368u, 0x007B3D20u },
    { "PboxcartridgesZ", PboxcartridgesZ, 512u, 0x007B3E90u },
    { "Pboxes2x4Z", Pboxes2x4Z, 1072u, 0x007B4090u },
    { "Pboxes3x4Z", Pboxes3x4Z, 1088u, 0x007B44C0u },
    { "Pboxes4x4Z", Pboxes4x4Z, 1632u, 0x007B4900u },
    { "PbrakeunitZ", PbrakeunitZ, 880u, 0x007B4F60u },
    { "Pbridge_console1aZ", Pbridge_console1aZ, 1408u, 0x007B52D0u },
    { "Pbridge_console1bZ", Pbridge_console1bZ, 1376u, 0x007B5850u },
    { "Pbridge_console2aZ", Pbridge_console2aZ, 1408u, 0x007B5DB0u },
    { "Pbridge_console2bZ", Pbridge_console2bZ, 1264u, 0x007B6330u },
    { "Pbridge_console3aZ", Pbridge_console3aZ, 1360u, 0x007B6820u },
    { "Pbridge_console3bZ", Pbridge_console3bZ, 1424u, 0x007B6D70u },
    { "PcarbmwZ", PcarbmwZ, 3296u, 0x007B7300u },
    { "Pcard_box1Z", Pcard_box1Z, 512u, 0x007B7FE0u },
    { "Pcard_box2Z", Pcard_box2Z, 576u, 0x007B81E0u },
    { "Pcard_box3Z", Pcard_box3Z, 496u, 0x007B8420u },
    { "Pcard_box4_lgZ", Pcard_box4_lgZ, 432u, 0x007B8610u },
    { "Pcard_box5_lgZ", Pcard_box5_lgZ, 512u, 0x007B87C0u },
    { "Pcard_box6_lgZ", Pcard_box6_lgZ, 496u, 0x007B89C0u },
    { "PcarescortZ", PcarescortZ, 3072u, 0x007B8BB0u },
    { "PcargolfZ", PcargolfZ, 3120u, 0x007B97B0u },
    { "PcarweirdZ", PcarweirdZ, 4416u, 0x007BA3E0u },
    { "PcarzilZ", PcarzilZ, 5632u, 0x007BB520u },
    { "PcctvZ", PcctvZ, 896u, 0x007BCB20u },
    { "PchraudiotapeZ", PchraudiotapeZ, 1376u, 0x007BCEA0u },
    { "PchrautoshotZ", PchrautoshotZ, 864u, 0x007BD400u },
    { "PchrblackboxZ", PchrblackboxZ, 2176u, 0x007BD760u },
    { "PchrblueprintsZ", PchrblueprintsZ, 336u, 0x007BDFE0u },
    { "PchrbombcaseZ", PchrbombcaseZ, 496u, 0x007BE130u },
    { "PchrbombdefuserZ", PchrbombdefuserZ, 2272u, 0x007BE320u },
    { "PchrbriefcaseZ", PchrbriefcaseZ, 400u, 0x007BEC00u },
    { "PchrbugZ", PchrbugZ, 3504u, 0x007BED90u },
    { "PchrbugdetectorZ", PchrbugdetectorZ, 368u, 0x007BFB40u },
    { "PchrbungeeZ", PchrbungeeZ, 368u, 0x007BFCB0u },
    { "PchrcameraZ", PchrcameraZ, 1680u, 0x007BFE20u },
    { "PchrcircuitboardZ", PchrcircuitboardZ, 416u, 0x007C04B0u },
    { "PchrclipboardZ", PchrclipboardZ, 640u, 0x007C0650u },
    { "PchrcreditcardZ", PchrcreditcardZ, 368u, 0x007C08D0u },
    { "PchrdarkglassesZ", PchrdarkglassesZ, 368u, 0x007C0A40u },
    { "PchrdatathiefZ", PchrdatathiefZ, 416u, 0x007C0BB0u },
    { "PchrdattapeZ", PchrdattapeZ, 496u, 0x007C0D50u },
    { "PchrdoordecoderZ", PchrdoordecoderZ, 2144u, 0x007C0F40u },
    { "PchrdoorexploderZ", PchrdoorexploderZ, 368u, 0x007C17A0u },
    { "PchrdossierredZ", PchrdossierredZ, 1232u, 0x007C1910u },
    { "PchrdynamiteZ", PchrdynamiteZ, 368u, 0x007C1DE0u },
    { "PchrexplosivepenZ", PchrexplosivepenZ, 368u, 0x007C1F50u },
    { "PchrextinguisherZ", PchrextinguisherZ, 1280u, 0x007C20C0u },
    { "PchrfingergunZ", PchrfingergunZ, 368u, 0x007C25C0u },
    { "PchrflarepistolZ", PchrflarepistolZ, 368u, 0x007C2730u },
    { "Pchrfnp90Z", Pchrfnp90Z, 1120u, 0x007C28A0u },
    { "PchrgaskeyringZ", PchrgaskeyringZ, 3856u, 0x007C2D00u },
    { "PchrgoldbarZ", PchrgoldbarZ, 368u, 0x007C3C10u },
    { "PchrgoldenZ", PchrgoldenZ, 624u, 0x007C3D80u },
    { "PchrgoldeneyekeyZ", PchrgoldeneyekeyZ, 3744u, 0x007C3FF0u },
    { "PchrgoldwppkZ", PchrgoldwppkZ, 368u, 0x007C4E90u },
    { "PchrgrenadeZ", PchrgrenadeZ, 880u, 0x007C5000u },
    { "PchrgrenadelaunchZ", PchrgrenadelaunchZ, 912u, 0x007C5370u },
    { "PchrgrenaderoundZ", PchrgrenaderoundZ, 624u, 0x007C5700u },
    { "PchrheroinZ", PchrheroinZ, 368u, 0x007C5970u },
    { "PchrkalashZ", PchrkalashZ, 1008u, 0x007C5AE0u },
    { "PchrkeyanalysercaseZ", PchrkeyanalysercaseZ, 496u, 0x007C5ED0u },
    { "PchrkeyboltZ", PchrkeyboltZ, 3744u, 0x007C60C0u },
    { "PchrkeyyaleZ", PchrkeyyaleZ, 5216u, 0x007C6F60u },
    { "PchrknifeZ", PchrknifeZ, 512u, 0x007C83C0u },
    { "PchrlaserZ", PchrlaserZ, 960u, 0x007C85C0u },
    { "PchrlectreZ", PchrlectreZ, 368u, 0x007C8980u },
    { "PchrlockexploderZ", PchrlockexploderZ, 368u, 0x007C8AF0u },
    { "Pchrm16Z", Pchrm16Z, 976u, 0x007C8C60u },
    { "PchrmapZ", PchrmapZ, 336u, 0x007C9030u },
    { "PchrmicrocameraZ", PchrmicrocameraZ, 2288u, 0x007C9180u },
    { "PchrmicrocodeZ", PchrmicrocodeZ, 368u, 0x007C9A70u },
    { "PchrmicrofilmZ", PchrmicrofilmZ, 368u, 0x007C9BE0u },
    { "PchrmoneyZ", PchrmoneyZ, 368u, 0x007C9D50u },
    { "Pchrmp5kZ", Pchrmp5kZ, 896u, 0x007C9EC0u },
    { "Pchrmp5ksilZ", Pchrmp5ksilZ, 1040u, 0x007CA240u },
    { "PchrpitongunZ", PchrpitongunZ, 368u, 0x007CA650u },
    { "PchrplansZ", PchrplansZ, 656u, 0x007CA7C0u },
    { "PchrplastiqueZ", PchrplastiqueZ, 1120u, 0x007CAA50u },
    { "PchrpolarizedglassesZ", PchrpolarizedglassesZ, 2240u, 0x007CAEB0u },
    { "PchrproximitymineZ", PchrproximitymineZ, 1120u, 0x007CB770u },
    { "PchrremotemineZ", PchrremotemineZ, 1120u, 0x007CBBD0u },
    { "PchrrocketZ", PchrrocketZ, 1456u, 0x007CC030u },
    { "PchrrocketlaunchZ", PchrrocketlaunchZ, 992u, 0x007CC5E0u },
    { "PchrrugerZ", PchrrugerZ, 992u, 0x007CC9C0u },
    { "PchrsafecrackercaseZ", PchrsafecrackercaseZ, 496u, 0x007CCDA0u },
    { "PchrshotgunZ", PchrshotgunZ, 848u, 0x007CCF90u },
    { "PchrsilverwppkZ", PchrsilverwppkZ, 368u, 0x007CD2E0u },
    { "PchrskorpionZ", PchrskorpionZ, 896u, 0x007CD450u },
    { "PchrsniperrifleZ", PchrsniperrifleZ, 912u, 0x007CD7D0u },
    { "PchrspectreZ", PchrspectreZ, 880u, 0x007CDB60u },
    { "PchrspooltapeZ", PchrspooltapeZ, 368u, 0x007CDED0u },
    { "PchrspyfileZ", PchrspyfileZ, 368u, 0x007CE040u },
    { "PchrstafflistZ", PchrstafflistZ, 544u, 0x007CE1B0u },
    { "PchrtesttubeZ", PchrtesttubeZ, 448u, 0x007CE3D0u },
    { "PchrthrowknifeZ", PchrthrowknifeZ, 544u, 0x007CE590u },
    { "PchrtimedmineZ", PchrtimedmineZ, 1328u, 0x007CE7B0u },
    { "Pchrtt33Z", Pchrtt33Z, 656u, 0x007CECE0u },
    { "PchruziZ", PchruziZ, 720u, 0x007CEF70u },
    { "PchrvideotapeZ", PchrvideotapeZ, 720u, 0x007CF240u },
    { "PchrweaponcaseZ", PchrweaponcaseZ, 512u, 0x007CF510u },
    { "PchrwppkZ", PchrwppkZ, 576u, 0x007CF710u },
    { "PchrwppksilZ", PchrwppksilZ, 736u, 0x007CF950u },
    { "PchrwristdartZ", PchrwristdartZ, 368u, 0x007CFC30u },
    { "Pconsole1Z", Pconsole1Z, 1664u, 0x007CFDA0u },
    { "Pconsole2Z", Pconsole2Z, 1664u, 0x007D0420u },
    { "Pconsole3Z", Pconsole3Z, 1680u, 0x007D0AA0u },
    { "Pconsole_sev2aZ", Pconsole_sev2aZ, 1056u, 0x007D1130u },
    { "Pconsole_sev2bZ", Pconsole_sev2bZ, 1216u, 0x007D1550u },
    { "Pconsole_sev2cZ", Pconsole_sev2cZ, 1088u, 0x007D1A10u },
    { "Pconsole_sev2dZ", Pconsole_sev2dZ, 1072u, 0x007D1E50u },
    { "Pconsole_sev_GEaZ", Pconsole_sev_GEaZ, 1072u, 0x007D2280u },
    { "Pconsole_sev_GEbZ", Pconsole_sev_GEbZ, 1072u, 0x007D26B0u },
    { "Pconsole_sevaZ", Pconsole_sevaZ, 1152u, 0x007D2AE0u },
    { "Pconsole_sevbZ", Pconsole_sevbZ, 1136u, 0x007D2F60u },
    { "Pconsole_sevcZ", Pconsole_sevcZ, 1072u, 0x007D33D0u },
    { "Pconsole_sevdZ", Pconsole_sevdZ, 1072u, 0x007D3800u },
    { "Pcryptdoor1aZ", Pcryptdoor1aZ, 400u, 0x007D3C30u },
    { "Pcryptdoor1bZ", Pcryptdoor1bZ, 400u, 0x007D3DC0u },
    { "Pcryptdoor2aZ", Pcryptdoor2aZ, 400u, 0x007D3F50u },
    { "Pcryptdoor2bZ", Pcryptdoor2bZ, 400u, 0x007D40E0u },
    { "Pcryptdoor3Z", Pcryptdoor3Z, 624u, 0x007D4270u },
    { "Pcryptdoor4Z", Pcryptdoor4Z, 384u, 0x007D44E0u },
    { "PdamchaindoorZ", PdamchaindoorZ, 640u, 0x007D4660u },
    { "PdamgatedoorZ", PdamgatedoorZ, 544u, 0x007D48E0u },
    { "PdamtundoorZ", PdamtundoorZ, 880u, 0x007D4B00u },
    { "Pdepot_door_steelZ", Pdepot_door_steelZ, 416u, 0x007D4E70u },
    { "Pdepot_gate_entryZ", Pdepot_gate_entryZ, 576u, 0x007D5010u },
    { "Pdesk1Z", Pdesk1Z, 384u, 0x007D5250u },
    { "Pdesk2Z", Pdesk2Z, 384u, 0x007D53D0u },
    { "Pdesk_arecibo1Z", Pdesk_arecibo1Z, 576u, 0x007D5550u },
    { "Pdesk_lamp2Z", Pdesk_lamp2Z, 768u, 0x007D5790u },
    { "Pdest_engineZ", Pdest_engineZ, 6384u, 0x007D5A90u },
    { "Pdest_exocetZ", Pdest_exocetZ, 1632u, 0x007D7380u },
    { "Pdest_gunZ", Pdest_gunZ, 1648u, 0x007D79E0u },
    { "Pdest_harpoonZ", Pdest_harpoonZ, 2208u, 0x007D8050u },
    { "Pdest_seawolfZ", Pdest_seawolfZ, 4016u, 0x007D88F0u },
    { "Pdisc_readerZ", Pdisc_readerZ, 448u, 0x007D98A0u },
    { "Pdisk_drive1Z", Pdisk_drive1Z, 400u, 0x007D9A60u },
    { "Pdoor_azt_chairZ", Pdoor_azt_chairZ, 384u, 0x007D9BF0u },
    { "Pdoor_azt_deskZ", Pdoor_azt_deskZ, 1088u, 0x007D9D70u },
    { "Pdoor_azt_desk_topZ", Pdoor_azt_desk_topZ, 912u, 0x007DA1B0u },
    { "Pdoor_aztecZ", Pdoor_aztecZ, 560u, 0x007DA540u },
    { "Pdoor_dest1Z", Pdoor_dest1Z, 768u, 0x007DA770u },
    { "Pdoor_dest2Z", Pdoor_dest2Z, 960u, 0x007DAA70u },
    { "Pdoor_eyelidZ", Pdoor_eyelidZ, 1376u, 0x007DAE30u },
    { "Pdoor_irisZ", Pdoor_irisZ, 2640u, 0x007DB390u },
    { "Pdoor_mfZ", Pdoor_mfZ, 752u, 0x007DBDE0u },
    { "Pdoor_roller1Z", Pdoor_roller1Z, 880u, 0x007DC0D0u },
    { "Pdoor_roller2Z", Pdoor_roller2Z, 576u, 0x007DC440u },
    { "Pdoor_roller3Z", Pdoor_roller3Z, 576u, 0x007DC680u },
    { "Pdoor_roller4Z", Pdoor_roller4Z, 608u, 0x007DC8C0u },
    { "Pdoor_rollertrainZ", Pdoor_rollertrainZ, 304u, 0x007DCB20u },
    { "Pdoor_st_arec1Z", Pdoor_st_arec1Z, 608u, 0x007DCC50u },
    { "Pdoor_st_arec2Z", Pdoor_st_arec2Z, 736u, 0x007DCEB0u },
    { "Pdoor_winZ", Pdoor_winZ, 416u, 0x007DD190u },
    { "PdoorconsoleZ", PdoorconsoleZ, 1136u, 0x007DD330u },
    { "PdoorpanelZ", PdoorpanelZ, 880u, 0x007DD7A0u },
    { "Pdoorprison1Z", Pdoorprison1Z, 336u, 0x007DDB10u },
    { "PdoorstatgateZ", PdoorstatgateZ, 512u, 0x007DDC60u },
    { "PexplosionbitZ", PexplosionbitZ, 288u, 0x007DDE60u },
    { "Pfiling_cabinet1Z", Pfiling_cabinet1Z, 384u, 0x007DDF80u },
    { "PflagZ", PflagZ, 304u, 0x007DE100u },
    { "PfloppyZ", PfloppyZ, 800u, 0x007DE230u },
    { "Pfnp90magZ", Pfnp90magZ, 416u, 0x007DE550u },
    { "Pgas_plant_met1_do1Z", Pgas_plant_met1_do1Z, 896u, 0x007DE6F0u },
    { "Pgas_plant_sw2_do1Z", Pgas_plant_sw2_do1Z, 480u, 0x007DEA70u },
    { "Pgas_plant_sw3_do1Z", Pgas_plant_sw3_do1Z, 512u, 0x007DEC50u },
    { "Pgas_plant_sw4_do1Z", Pgas_plant_sw4_do1Z, 352u, 0x007DEE50u },
    { "Pgas_plant_sw_do1Z", Pgas_plant_sw_do1Z, 656u, 0x007DEFB0u },
    { "Pgas_plant_wc_cub1Z", Pgas_plant_wc_cub1Z, 528u, 0x007DF240u },
    { "PgasbarrelZ", PgasbarrelZ, 528u, 0x007DF450u },
    { "PgasbarrelsZ", PgasbarrelsZ, 1344u, 0x007DF660u },
    { "Pgasplant_clear_doorZ", Pgasplant_clear_doorZ, 1376u, 0x007DFBA0u },
    { "PgastankZ", PgastankZ, 1456u, 0x007E0100u },
    { "Pglassware1Z", Pglassware1Z, 352u, 0x007E06B0u },
    { "Pglassware2Z", Pglassware2Z, 656u, 0x007E0810u },
    { "Pglassware3Z", Pglassware3Z, 528u, 0x007E0AA0u },
    { "Pglassware4Z", Pglassware4Z, 1408u, 0x007E0CB0u },
    { "PgoldeneyelogoZ", PgoldeneyelogoZ, 3760u, 0x007E1230u },
    { "PgoldenshellsZ", PgoldenshellsZ, 512u, 0x007E20E0u },
    { "PgroundgunZ", PgroundgunZ, 2000u, 0x007E22E0u },
    { "Pgun_runway1Z", Pgun_runway1Z, 1856u, 0x007E2AB0u },
    { "PhatberetZ", PhatberetZ, 672u, 0x007E31F0u },
    { "PhatberetblueZ", PhatberetblueZ, 720u, 0x007E3490u },
    { "PhatberetredZ", PhatberetredZ, 736u, 0x007E3760u },
    { "PhatchboltZ", PhatchboltZ, 208u, 0x007E3A40u },
    { "PhatchdoorZ", PhatchdoorZ, 544u, 0x007E3B10u },
    { "PhatchsevxZ", PhatchsevxZ, 368u, 0x007E3D30u },
    { "PhatfurryZ", PhatfurryZ, 560u, 0x007E3EA0u },
    { "PhatfurryblackZ", PhatfurryblackZ, 544u, 0x007E40D0u },
    { "PhatfurrybrownZ", PhatfurrybrownZ, 528u, 0x007E42F0u },
    { "PhathelmetZ", PhathelmetZ, 560u, 0x007E4500u },
    { "PhathelmetgreyZ", PhathelmetgreyZ, 560u, 0x007E4730u },
    { "PhatmoonZ", PhatmoonZ, 992u, 0x007E4960u },
    { "PhatpeakedZ", PhatpeakedZ, 784u, 0x007E4D40u },
    { "PhattbirdZ", PhattbirdZ, 592u, 0x007E5050u },
    { "PhattbirdbrownZ", PhattbirdbrownZ, 624u, 0x007E52A0u },
    { "PhelicopterZ", PhelicopterZ, 16928u, 0x007E5510u },
    { "PhindZ", PhindZ, 6000u, 0x007E9730u },
    { "PjeepZ", PjeepZ, 4448u, 0x007EAEA0u },
    { "Pjerry_can1Z", Pjerry_can1Z, 608u, 0x007EC000u },
    { "Pjungle3_treeZ", Pjungle3_treeZ, 1920u, 0x007EC260u },
    { "Pjungle5_treeZ", Pjungle5_treeZ, 1328u, 0x007EC9E0u },
    { "Pkey_holderZ", Pkey_holderZ, 848u, 0x007ECF10u },
    { "Pkeyboard1Z", Pkeyboard1Z, 368u, 0x007ED260u },
    { "Pkit_units1Z", Pkit_units1Z, 672u, 0x007ED3D0u },
    { "PlabbenchZ", PlabbenchZ, 976u, 0x007ED670u },
    { "PlandmineZ", PlandmineZ, 624u, 0x007EDA40u },
    { "PlegalpageZ", PlegalpageZ, 4032u, 0x007EDCB0u },
    { "Pletter_tray1Z", Pletter_tray1Z, 352u, 0x007EEC70u },
    { "Plocker3Z", Plocker3Z, 400u, 0x007EEDD0u },
    { "Plocker4Z", Plocker4Z, 400u, 0x007EEF60u },
    { "Pm16magZ", Pm16magZ, 320u, 0x007EF0F0u },
    { "PmagnumshellsZ", PmagnumshellsZ, 512u, 0x007EF230u },
    { "Pmainframe1Z", Pmainframe1Z, 768u, 0x007EF430u },
    { "Pmainframe2Z", Pmainframe2Z, 720u, 0x007EF730u },
    { "Pmetal_chair1Z", Pmetal_chair1Z, 832u, 0x007EFA00u },
    { "Pmetal_crate1Z", Pmetal_crate1Z, 448u, 0x007EFD40u },
    { "Pmetal_crate2Z", Pmetal_crate2Z, 448u, 0x007EFF00u },
    { "Pmetal_crate3Z", Pmetal_crate3Z, 448u, 0x007F00C0u },
    { "Pmetal_crate4Z", Pmetal_crate4Z, 448u, 0x007F0280u },
    { "PmilcopterZ", PmilcopterZ, 6368u, 0x007F0440u },
    { "PmiltruckZ", PmiltruckZ, 8960u, 0x007F1D20u },
    { "Pmissile_rack2Z", Pmissile_rack2Z, 2576u, 0x007F4020u },
    { "Pmissile_rackZ", Pmissile_rackZ, 992u, 0x007F4A30u },
    { "PmodemboxZ", PmodemboxZ, 832u, 0x007F4E10u },
    { "PmotorbikeZ", PmotorbikeZ, 3776u, 0x007F5150u },
    { "Pmp5kmagZ", Pmp5kmagZ, 336u, 0x007F6010u },
    { "PnintendologoZ", PnintendologoZ, 10976u, 0x007F6160u },
    { "Poil_drum1Z", Poil_drum1Z, 624u, 0x007F8C40u },
    { "Poil_drum2Z", Poil_drum2Z, 752u, 0x007F8EB0u },
    { "Poil_drum3Z", Poil_drum3Z, 752u, 0x007F91A0u },
    { "Poil_drum5Z", Poil_drum5Z, 752u, 0x007F9490u },
    { "Poil_drum6Z", Poil_drum6Z, 784u, 0x007F9780u },
    { "Poil_drum7Z", Poil_drum7Z, 768u, 0x007F9A90u },
    { "PpadlockZ", PpadlockZ, 2640u, 0x007F9D90u },
    { "PpalmZ", PpalmZ, 1104u, 0x007FA7E0u },
    { "PpalmtreeZ", PpalmtreeZ, 1232u, 0x007FAC30u },
    { "Pphone1Z", Pphone1Z, 320u, 0x007FB100u },
    { "PplaneZ", PplaneZ, 9696u, 0x007FB240u },
    { "Pplant11Z", Pplant11Z, 960u, 0x007FD820u },
    { "Pplant1Z", Pplant1Z, 912u, 0x007FDBE0u },
    { "Pplant2Z", Pplant2Z, 864u, 0x007FDF70u },
    { "Pplant2bZ", Pplant2bZ, 1040u, 0x007FE2D0u },
    { "Pplant3Z", Pplant3Z, 1104u, 0x007FE6E0u },
    { "Pradio_unit1Z", Pradio_unit1Z, 432u, 0x007FEB30u },
    { "Pradio_unit2Z", Pradio_unit2Z, 448u, 0x007FECE0u },
    { "Pradio_unit3Z", Pradio_unit3Z, 448u, 0x007FEEA0u },
    { "Pradio_unit4Z", Pradio_unit4Z, 448u, 0x007FF060u },
    { "ProofgunZ", ProofgunZ, 1632u, 0x007FF220u },
    { "PsafeZ", PsafeZ, 848u, 0x007FF880u },
    { "PsafedoorZ", PsafedoorZ, 1264u, 0x007FFBD0u },
    { "Psat1_reflectZ", Psat1_reflectZ, 5488u, 0x008000C0u },
    { "PsatboxZ", PsatboxZ, 288u, 0x00801630u },
    { "PsatdishZ", PsatdishZ, 1120u, 0x00801750u },
    { "Psec_panelZ", Psec_panelZ, 416u, 0x00801BB0u },
    { "Psev_door3Z", Psev_door3Z, 656u, 0x00801D50u },
    { "Psev_door3_windZ", Psev_door3_windZ, 912u, 0x00801FE0u },
    { "Psev_door4_windZ", Psev_door4_windZ, 992u, 0x00802370u },
    { "Psev_doorZ", Psev_doorZ, 848u, 0x00802750u },
    { "Psev_door_v1Z", Psev_door_v1Z, 816u, 0x00802AA0u },
    { "Psev_trislideZ", Psev_trislideZ, 944u, 0x00802DD0u },
    { "PsevdishZ", PsevdishZ, 3872u, 0x00803180u },
    { "PsevdoormetslideZ", PsevdoormetslideZ, 736u, 0x008040A0u },
    { "PsevdoornowindZ", PsevdoornowindZ, 368u, 0x00804380u },
    { "PsevdoorwindZ", PsevdoorwindZ, 1072u, 0x008044F0u },
    { "PsevdoorwoodZ", PsevdoorwoodZ, 944u, 0x00804920u },
    { "PshuttleZ", PshuttleZ, 10752u, 0x00804CD0u },
    { "Pshuttle_door_lZ", Pshuttle_door_lZ, 3120u, 0x008076D0u },
    { "Pshuttle_door_rZ", Pshuttle_door_rZ, 3328u, 0x00808300u },
    { "PsilencerZ", PsilencerZ, 416u, 0x00809000u },
    { "Psilo_lift_doorZ", Psilo_lift_doorZ, 576u, 0x008091A0u },
    { "PsilotopdoorZ", PsilotopdoorZ, 752u, 0x008093E0u },
    { "PskorpionmagZ", PskorpionmagZ, 352u, 0x008096D0u },
    { "PspectremagZ", PspectremagZ, 368u, 0x00809830u },
    { "PspeedboatZ", PspeedboatZ, 3392u, 0x008099A0u },
    { "Pst_pete_room_1iZ", Pst_pete_room_1iZ, 12608u, 0x0080A6E0u },
    { "Pst_pete_room_2iZ", Pst_pete_room_2iZ, 12768u, 0x0080D820u },
    { "Pst_pete_room_3tZ", Pst_pete_room_3tZ, 12096u, 0x00810A00u },
    { "Pst_pete_room_5cZ", Pst_pete_room_5cZ, 13712u, 0x00813940u },
    { "Pst_pete_room_6cZ", Pst_pete_room_6cZ, 13328u, 0x00816ED0u },
    { "Psteel_door1Z", Psteel_door1Z, 624u, 0x0081A2E0u },
    { "Psteel_door2Z", Psteel_door2Z, 688u, 0x0081A550u },
    { "Psteel_door2bZ", Psteel_door2bZ, 720u, 0x0081A800u },
    { "Psteel_door3Z", Psteel_door3Z, 720u, 0x0081AAD0u },
    { "Pstool1Z", Pstool1Z, 704u, 0x0081ADA0u },
    { "Pswipe_card2Z", Pswipe_card2Z, 400u, 0x0081B060u },
    { "Pswivel_chair1Z", Pswivel_chair1Z, 656u, 0x0081B1F0u },
    { "PtankZ", PtankZ, 6816u, 0x0081B480u },
    { "PtigerZ", PtigerZ, 7824u, 0x0081CF20u },
    { "Ptorpedo_rackZ", Ptorpedo_rackZ, 2176u, 0x0081EDB0u },
    { "Ptrain_door2Z", Ptrain_door2Z, 976u, 0x0081F630u },
    { "Ptrain_door3Z", Ptrain_door3Z, 1056u, 0x0081FA00u },
    { "Ptrain_doorZ", Ptrain_doorZ, 624u, 0x0081FE20u },
    { "PtrainextdoorZ", PtrainextdoorZ, 832u, 0x00820090u },
    { "Ptt33magZ", Ptt33magZ, 320u, 0x008203D0u },
    { "Ptuning_console1Z", Ptuning_console1Z, 1312u, 0x00820510u },
    { "Ptv1Z", Ptv1Z, 464u, 0x00820A30u },
    { "Ptv4screenZ", Ptv4screenZ, 416u, 0x00820C00u },
    { "Ptv_holderZ", Ptv_holderZ, 1744u, 0x00820DA0u },
    { "PtvscreenZ", PtvscreenZ, 208u, 0x00821470u },
    { "PuzimagZ", PuzimagZ, 320u, 0x00821540u },
    { "PvertdoorZ", PvertdoorZ, 1552u, 0x00821680u },
    { "PwalletbondZ", PwalletbondZ, 5552u, 0x00821C90u },
    { "PwindowZ", PwindowZ, 240u, 0x00823240u },
    { "Pwindow_cor11Z", Pwindow_cor11Z, 224u, 0x00823330u },
    { "Pwindow_lib_lg1Z", Pwindow_lib_lg1Z, 224u, 0x00823410u },
    { "Pwindow_lib_sm1Z", Pwindow_lib_sm1Z, 240u, 0x008234F0u },
    { "Pwood_lg_crate1Z", Pwood_lg_crate1Z, 640u, 0x008235E0u },
    { "Pwood_lg_crate2Z", Pwood_lg_crate2Z, 544u, 0x00823860u },
    { "Pwood_md_crate3Z", Pwood_md_crate3Z, 544u, 0x00823A80u },
    { "Pwood_sm_crate4Z", Pwood_sm_crate4Z, 608u, 0x00823CA0u },
    { "Pwood_sm_crate5Z", Pwood_sm_crate5Z, 608u, 0x00823F00u },
    { "Pwood_sm_crate6Z", Pwood_sm_crate6Z, 544u, 0x00824160u },
    { "Pwooden_table1Z", Pwooden_table1Z, 880u, 0x00824380u },
    { "PwppkmagZ", PwppkmagZ, 320u, 0x008246F0u },
    { "Tbg_ame_all_p_stanZ", Tbg_ame_all_p_stanZ, 6448u, 0x00824830u },
    { "Tbg_arch_all_p_stanZ", Tbg_arch_all_p_stanZ, 23792u, 0x00826160u },
    { "Tbg_arec_all_p_stanZ", Tbg_arec_all_p_stanZ, 33616u, 0x0082BE50u },
    { "Tbg_ark_all_p_stanZ", Tbg_ark_all_p_stanZ, 36800u, 0x008341A0u },
    { "Tbg_ash_all_p_stanZ", Tbg_ash_all_p_stanZ, 6448u, 0x0083D160u },
    { "Tbg_azt_all_p_stanZ", Tbg_azt_all_p_stanZ, 21888u, 0x0083EA90u },
    { "Tbg_cat_all_p_stanZ", Tbg_cat_all_p_stanZ, 10032u, 0x00844010u },
    { "Tbg_cave_all_p_stanZ", Tbg_cave_all_p_stanZ, 20208u, 0x00846740u },
    { "Tbg_crad_all_p_stanZ", Tbg_crad_all_p_stanZ, 10512u, 0x0084B630u },
    { "Tbg_cryp_all_p_stanZ", Tbg_cryp_all_p_stanZ, 12400u, 0x0084DF40u },
    { "Tbg_dam_all_p_stanZ", Tbg_dam_all_p_stanZ, 41952u, 0x00850FB0u },
    { "Tbg_depo_all_p_stanZ", Tbg_depo_all_p_stanZ, 28480u, 0x0085B390u },
    { "Tbg_dest_all_p_stanZ", Tbg_dest_all_p_stanZ, 26864u, 0x008622D0u },
    { "Tbg_dish_all_p_stanZ", Tbg_dish_all_p_stanZ, 2832u, 0x00868BC0u },
    { "Tbg_imp_all_p_stanZ", Tbg_imp_all_p_stanZ, 6448u, 0x008696D0u },
    { "Tbg_jun_all_p_stanZ", Tbg_jun_all_p_stanZ, 29008u, 0x0086B000u },
    { "Tbg_len_all_p_stanZ", Tbg_len_all_p_stanZ, 2752u, 0x00872150u },
    { "Tbg_oat_all_p_stanZ", Tbg_oat_all_p_stanZ, 6400u, 0x00872C10u },
    { "Tbg_pete_all_p_stanZ", Tbg_pete_all_p_stanZ, 18064u, 0x00874510u },
    { "Tbg_ref_all_p_stanZ", Tbg_ref_all_p_stanZ, 7632u, 0x00878BA0u },
    { "Tbg_run_all_p_stanZ", Tbg_run_all_p_stanZ, 6784u, 0x0087A970u },
    { "Tbg_sev_all_p_stanZ", Tbg_sev_all_p_stanZ, 15824u, 0x0087C3F0u },
    { "Tbg_sevb_all_p_stanZ", Tbg_sevb_all_p_stanZ, 20288u, 0x008801C0u },
    { "Tbg_sevx_all_p_stanZ", Tbg_sevx_all_p_stanZ, 37680u, 0x00885100u },
    { "Tbg_silo_all_p_stanZ", Tbg_silo_all_p_stanZ, 37024u, 0x0088E430u },
    { "Tbg_stat_all_p_stanZ", Tbg_stat_all_p_stanZ, 20160u, 0x008974D0u },
    { "Tbg_tra_all_p_stanZ", Tbg_tra_all_p_stanZ, 9168u, 0x0089C390u },
    { "UbriefarchZ", UbriefarchZ, 32u, 0x0089E760u },
    { "UbriefarkZ", UbriefarkZ, 32u, 0x0089E780u },
    { "UbriefaztZ", UbriefaztZ, 32u, 0x0089E7A0u },
    { "UbriefcaveZ", UbriefcaveZ, 32u, 0x0089E7C0u },
    { "UbriefcontrolZ", UbriefcontrolZ, 32u, 0x0089E7E0u },
    { "UbriefcradZ", UbriefcradZ, 32u, 0x0089E800u },
    { "UbriefcrypZ", UbriefcrypZ, 32u, 0x0089E820u },
    { "UbriefdamZ", UbriefdamZ, 32u, 0x0089E840u },
    { "UbriefdepoZ", UbriefdepoZ, 32u, 0x0089E860u },
    { "UbriefdestZ", UbriefdestZ, 32u, 0x0089E880u },
    { "UbriefjunZ", UbriefjunZ, 32u, 0x0089E8A0u },
    { "UbriefpeteZ", UbriefpeteZ, 32u, 0x0089E8C0u },
    { "UbriefrunZ", UbriefrunZ, 32u, 0x0089E8E0u },
    { "UbriefsevbZ", UbriefsevbZ, 32u, 0x0089E900u },
    { "UbriefsevbunkerZ", UbriefsevbunkerZ, 32u, 0x0089E920u },
    { "UbriefsevxZ", UbriefsevxZ, 32u, 0x0089E940u },
    { "UbriefsevxbZ", UbriefsevxbZ, 32u, 0x0089E960u },
    { "UbriefsiloZ", UbriefsiloZ, 32u, 0x0089E980u },
    { "UbriefstatueZ", UbriefstatueZ, 32u, 0x0089E9A0u },
    { "UbrieftraZ", UbrieftraZ, 32u, 0x0089E9C0u },
    { "Ump_setupameZ", Ump_setupameZ, 1824u, 0x0089E9E0u },
    { "Ump_setuparchZ", Ump_setuparchZ, 11680u, 0x0089F100u },
    { "Ump_setuparkZ", Ump_setuparkZ, 7488u, 0x008A1EA0u },
    { "Ump_setupashZ", Ump_setupashZ, 1776u, 0x008A3BE0u },
    { "Ump_setupcaveZ", Ump_setupcaveZ, 9568u, 0x008A42D0u },
    { "Ump_setupcradZ", Ump_setupcradZ, 2400u, 0x008A6830u },
    { "Ump_setupcrypZ", Ump_setupcrypZ, 3424u, 0x008A7190u },
    { "Ump_setupdishZ", Ump_setupdishZ, 1008u, 0x008A7EF0u },
    { "Ump_setupimpZ", Ump_setupimpZ, 1600u, 0x008A82E0u },
    { "Ump_setupoatZ", Ump_setupoatZ, 848u, 0x008A8920u },
    { "Ump_setuprefZ", Ump_setuprefZ, 1040u, 0x008A8C70u },
    { "Ump_setupsevbZ", Ump_setupsevbZ, 4880u, 0x008A9080u },
    { "Ump_setupstatueZ", Ump_setupstatueZ, 3712u, 0x008AA390u },
    { "UsetuparchZ", UsetuparchZ, 17936u, 0x008AB210u },
    { "UsetuparkZ", UsetuparkZ, 15248u, 0x008AF820u },
    { "UsetupaztZ", UsetupaztZ, 10496u, 0x008B33B0u },
    { "UsetupcaveZ", UsetupcaveZ, 15968u, 0x008B5CB0u },
    { "UsetupcontrolZ", UsetupcontrolZ, 15104u, 0x008B9B10u },
    { "UsetupcradZ", UsetupcradZ, 7216u, 0x008BD610u },
    { "UsetupcrypZ", UsetupcrypZ, 7824u, 0x008BF240u },
    { "UsetupdamZ", UsetupdamZ, 17104u, 0x008C10D0u },
    { "UsetupdepoZ", UsetupdepoZ, 12176u, 0x008C53A0u },
    { "UsetupdestZ", UsetupdestZ, 9040u, 0x008C8330u },
    { "UsetupjunZ", UsetupjunZ, 14080u, 0x008CA680u },
    { "UsetuplenZ", UsetuplenZ, 1488u, 0x008CDD80u },
    { "UsetuppeteZ", UsetuppeteZ, 12160u, 0x008CE350u },
    { "UsetuprunZ", UsetuprunZ, 6240u, 0x008D12D0u },
    { "UsetupsevbZ", UsetupsevbZ, 9824u, 0x008D2B30u },
    { "UsetupsevbunkerZ", UsetupsevbunkerZ, 6704u, 0x008D5190u },
    { "UsetupsevxZ", UsetupsevxZ, 17168u, 0x008D6BC0u },
    { "UsetupsevxbZ", UsetupsevxbZ, 16624u, 0x008DAED0u },
    { "UsetupsiloZ", UsetupsiloZ, 10832u, 0x008DEFC0u },
    { "UsetupstatueZ", UsetupstatueZ, 10192u, 0x008E1A10u },
    { "UsetuptraZ", UsetuptraZ, 12848u, 0x008E41E0u },
    { "bg_arch_all_p_seg", bg_arch_all_p_seg, 154352u, 0x004EA7E0u },
    { "bg_arec_all_p_seg", bg_arec_all_p_seg, 189312u, 0x004BC460u },
    { "bg_ark_all_p_seg", bg_ark_all_p_seg, 200576u, 0x0062FDF0u },
    { "bg_azt_all_p_seg", bg_azt_all_p_seg, 137808u, 0x00578FA0u },
    { "bg_cat_all_p_seg", bg_cat_all_p_seg, 21808u, 0x006C55C0u },
    { "bg_cave_all_p_seg", bg_cave_all_p_seg, 148720u, 0x006A10D0u },
    { "bg_crad_all_p_seg", bg_crad_all_p_seg, 66384u, 0x006CAAF0u },
    { "bg_cryp_all_p_seg", bg_cryp_all_p_seg, 87728u, 0x005EA5A0u },
    { "bg_dam_all_p_seg", bg_dam_all_p_seg, 197024u, 0x005FFC50u },
    { "bg_depo_all_p_seg", bg_depo_all_p_seg, 182640u, 0x005B4620u },
    { "bg_dest_all_p_seg", bg_dest_all_p_seg, 186816u, 0x00530840u },
    { "bg_dish_all_p_seg", bg_dish_all_p_seg, 18544u, 0x0069C860u },
    { "bg_ear_all_p_seg", bg_ear_all_p_seg, 1u, 0x006EBBF0u },
    { "bg_imp_all_p_seg", bg_imp_all_p_seg, 1u, 0x006DAE40u },
    { "bg_jun_all_p_seg", bg_jun_all_p_seg, 86352u, 0x00687710u },
    { "bg_lee_all_p_seg", bg_lee_all_p_seg, 1u, 0x006EBBF0u },
    { "bg_len_all_p_seg", bg_len_all_p_seg, 4000u, 0x006EBBF0u },
    { "bg_lip_all_p_seg", bg_lip_all_p_seg, 1u, 0x006EBBF0u },
    { "bg_oat_all_p_seg", bg_oat_all_p_seg, 28240u, 0x006E4DA0u },
    { "bg_pam_all_p_seg", bg_pam_all_p_seg, 9344u, 0x006ECB90u },
    { "bg_pete_all_p_seg", bg_pete_all_p_seg, 105520u, 0x0059A9F0u },
    { "bg_ref_all_p_seg", bg_ref_all_p_seg, 38416u, 0x005E0F90u },
    { "bg_rit_all_p_seg", bg_rit_all_p_seg, 1u, 0x006E4DA0u },
    { "bg_run_all_p_seg", bg_run_all_p_seg, 41936u, 0x00660D70u },
    { "bg_sev_all_p_seg", bg_sev_all_p_seg, 69104u, 0x00438660u },
    { "bg_sevb_all_p_seg", bg_sevb_all_p_seg, 109984u, 0x0055E200u },
    { "bg_sevx_all_p_seg", bg_sevx_all_p_seg, 116176u, 0x0066B140u },
    { "bg_sho_all_p_seg", bg_sho_all_p_seg, 1u, 0x006DAE40u },
    { "bg_silo_all_p_seg", bg_silo_all_p_seg, 331584u, 0x00449450u },
    { "bg_stat_all_p_seg", bg_stat_all_p_seg, 139472u, 0x0049A390u },
    { "bg_tra_all_p_seg", bg_tra_all_p_seg, 132464u, 0x005102D0u },
    { "bg_wax_all_p_seg", bg_wax_all_p_seg, 9344u, 0x006ECB90u },
    { "ob__ob_end_seg", ob__ob_end_seg, 16u, 0x008F7DE0u },
    { "ramrom_BunkerI_1", ramrom_BunkerI_1, 13200u, 0x002D1000u },
    { "ramrom_BunkerI_2", ramrom_BunkerI_2, 21120u, 0x002D4390u },
    { "ramrom_Dam_1", ramrom_Dam_1, 20992u, 0x002BF2D0u },
    { "ramrom_Dam_2", ramrom_Dam_2, 8144u, 0x002C44D0u },
    { "ramrom_Facility_1", ramrom_Facility_1, 6832u, 0x002C64A0u },
    { "ramrom_Facility_2", ramrom_Facility_2, 9184u, 0x002C7F50u },
    { "ramrom_Facility_3", ramrom_Facility_3, 7280u, 0x002CA330u },
    { "ramrom_Frigate_1", ramrom_Frigate_1, 6576u, 0x002DD770u },
    { "ramrom_Frigate_2", ramrom_Frigate_2, 13536u, 0x002DF120u },
    { "ramrom_Runway_1", ramrom_Runway_1, 10064u, 0x002CBFA0u },
    { "ramrom_Runway_2", ramrom_Runway_2, 10512u, 0x002CE6F0u },
    { "ramrom_Silo_1", ramrom_Silo_1, 8592u, 0x002D9610u },
    { "ramrom_Silo_2", ramrom_Silo_2, 8144u, 0x002DB7A0u },
    { "ramrom_Train", ramrom_Train, 15856u, 0x002E2600u },
    { "unknown2", unknown2, 107904u, 0x002A4D50u },
};

const unsigned int ge_asset_count = 729u;
