/*
 * ge_expand.h -- GENERATED by tools/gen_struct_expand.py. Do not edit.
 *
 * Convert one cartridge record into the host's layout.
 *
 * `src` is the record as it sits in the file: N64 offsets, big-endian.
 * `dst` is sizeof(T) bytes of host memory, cleared first, then filled
 * field by field. Use these where the struct CANNOT be pinned with
 * GE_N64PTR -- otherwise geSwap_*() in ge_swap.h is cheaper and converts
 * in place. See the tool's docstring for which is which.
 */
#ifndef GE_EXPAND_H
#define GE_EXPAND_H

#ifdef __cplusplus
extern "C" {
#endif

/* The N64 size of each record: what to stride by in the FILE.
 * sizeof(T) is the host size, which is what to stride by in memory --
 * confusing the two is the bug this whole file exists for. */
#define GE_N64SIZEOF_PropDefHeaderRecord 4   /* host: 4 */
#define GE_N64SIZEOF_ObjectRecord 128   /* host: 144 */
#define GE_N64SIZEOF_GuardRecord 28   /* host: 32 */
#define GE_N64SIZEOF_DoorRecord 256   /* host: 296 */
#define GE_N64SIZEOF_GlobalDoorScaleRecord 8   /* host: 8 */
#define GE_N64SIZEOF_KeyRecord 132   /* host: 152 */
#define GE_N64SIZEOF_TintedGlassRecord 148   /* host: 168 */
#define GE_N64SIZEOF_CCTVRecord 252   /* host: 272 */
#define GE_N64SIZEOF_WeaponObjRecord 136   /* host: 160 */
#define GE_N64SIZEOF_MonitorObjRecord 256   /* host: 288 */
#define GE_N64SIZEOF_MultiMonitorObjRecord 596   /* host: 664 */
#define GE_N64SIZEOF_AutogunRecord 216   /* host: 248 */
#define GE_N64SIZEOF_LinkRecord 16   /* host: 32 */
#define GE_N64SIZEOF_GuardAttributeRecord 12   /* host: 12 */
#define GE_N64SIZEOF_MultiAmmoCrateRecord 180   /* host: 200 */
#define GE_N64SIZEOF_BodyArmourRecord 136   /* host: 152 */
#define GE_N64SIZEOF_TagObjectRecord 16   /* host: 24 */
#define GE_N64SIZEOF_RenameObjectRecord 40   /* host: 48 */
#define GE_N64SIZEOF_LockDoorRecord 16   /* host: 32 */
#define GE_N64SIZEOF_VehichleRecord 176   /* host: 208 */
#define GE_N64SIZEOF_AircraftRecord 180   /* host: 208 */
#define GE_N64SIZEOF_TankRecord 224   /* host: 248 */
#define GE_N64SIZEOF_CutsceneRecord 28   /* host: 28 */
#define GE_N64SIZEOF_SafeObjectRecord 20   /* host: 40 */
#define GE_N64SIZEOF_AmmoCrateRecord 132   /* host: 152 */
#define GE_N64SIZEOF_HatRecord 128   /* host: 144 */
#define GE_N64SIZEOF_GlassRecord 140   /* host: 160 */
#define GE_N64SIZEOF_SafeRecord 140   /* host: 160 */
#define GE_N64SIZEOF_GasReleasingRecord 6   /* host: 6 */
#define GE_N64SIZEOF_SetupIntroEmpty 4   /* host: 4 */
#define GE_N64SIZEOF_SetupIntroSpawn 12   /* host: 12 */
#define GE_N64SIZEOF_SetupIntroItem 16   /* host: 16 */
#define GE_N64SIZEOF_SetupIntroAmmo 16   /* host: 16 */
#define GE_N64SIZEOF_SetupIntroSwirl 32   /* host: 32 */
#define GE_N64SIZEOF_SetupIntroAnim 8   /* host: 8 */
#define GE_N64SIZEOF_SetupIntroCuff 8   /* host: 8 */
#define GE_N64SIZEOF_SetupIntroCamera 40   /* host: 56 */
#define GE_N64SIZEOF_SetupIntroWatch 12   /* host: 12 */
#define GE_N64SIZEOF_SetupIntroCredits 8   /* host: 8 */
#define GE_N64SIZEOF_objective_entry 16   /* host: 16 */
#define GE_N64SIZEOF_criteria_roomentered 16   /* host: 24 */
#define GE_N64SIZEOF_criteria_deposit 20   /* host: 24 */
#define GE_N64SIZEOF_criteria_picture 16   /* host: 24 */
#define GE_N64SIZEOF_setup_objective_text 16   /* host: 24 */

void geExpand_PropDefHeaderRecord(void *dst, const void *src);   /* 4 -> 4 bytes */
void geExpand_ObjectRecord(void *dst, const void *src);   /* 128 -> 144 bytes */
void geExpand_GuardRecord(void *dst, const void *src);   /* 28 -> 32 bytes */
void geExpand_DoorRecord(void *dst, const void *src);   /* 256 -> 296 bytes */
void geExpand_GlobalDoorScaleRecord(void *dst, const void *src);   /* 8 -> 8 bytes */
void geExpand_KeyRecord(void *dst, const void *src);   /* 132 -> 152 bytes */
void geExpand_TintedGlassRecord(void *dst, const void *src);   /* 148 -> 168 bytes */
void geExpand_CCTVRecord(void *dst, const void *src);   /* 252 -> 272 bytes */
void geExpand_WeaponObjRecord(void *dst, const void *src);   /* 136 -> 160 bytes */
void geExpand_MonitorObjRecord(void *dst, const void *src);   /* 256 -> 288 bytes */
void geExpand_MultiMonitorObjRecord(void *dst, const void *src);   /* 596 -> 664 bytes */
void geExpand_AutogunRecord(void *dst, const void *src);   /* 216 -> 248 bytes */
void geExpand_LinkRecord(void *dst, const void *src);   /* 16 -> 32 bytes */
void geExpand_GuardAttributeRecord(void *dst, const void *src);   /* 12 -> 12 bytes */
void geExpand_MultiAmmoCrateRecord(void *dst, const void *src);   /* 180 -> 200 bytes */
void geExpand_BodyArmourRecord(void *dst, const void *src);   /* 136 -> 152 bytes */
void geExpand_TagObjectRecord(void *dst, const void *src);   /* 16 -> 24 bytes */
void geExpand_RenameObjectRecord(void *dst, const void *src);   /* 40 -> 48 bytes */
void geExpand_LockDoorRecord(void *dst, const void *src);   /* 16 -> 32 bytes */
void geExpand_VehichleRecord(void *dst, const void *src);   /* 176 -> 208 bytes */
void geExpand_AircraftRecord(void *dst, const void *src);   /* 180 -> 208 bytes */
void geExpand_TankRecord(void *dst, const void *src);   /* 224 -> 248 bytes */
void geExpand_CutsceneRecord(void *dst, const void *src);   /* 28 -> 28 bytes */
void geExpand_SafeObjectRecord(void *dst, const void *src);   /* 20 -> 40 bytes */
void geExpand_AmmoCrateRecord(void *dst, const void *src);   /* 132 -> 152 bytes */
void geExpand_HatRecord(void *dst, const void *src);   /* 128 -> 144 bytes */
void geExpand_GlassRecord(void *dst, const void *src);   /* 140 -> 160 bytes */
void geExpand_SafeRecord(void *dst, const void *src);   /* 140 -> 160 bytes */
void geExpand_GasReleasingRecord(void *dst, const void *src);   /* 6 -> 6 bytes */
void geExpand_SetupIntroEmpty(void *dst, const void *src);   /* 4 -> 4 bytes */
void geExpand_SetupIntroSpawn(void *dst, const void *src);   /* 12 -> 12 bytes */
void geExpand_SetupIntroItem(void *dst, const void *src);   /* 16 -> 16 bytes */
void geExpand_SetupIntroAmmo(void *dst, const void *src);   /* 16 -> 16 bytes */
void geExpand_SetupIntroSwirl(void *dst, const void *src);   /* 32 -> 32 bytes */
void geExpand_SetupIntroAnim(void *dst, const void *src);   /* 8 -> 8 bytes */
void geExpand_SetupIntroCuff(void *dst, const void *src);   /* 8 -> 8 bytes */
void geExpand_SetupIntroCamera(void *dst, const void *src);   /* 40 -> 56 bytes */
void geExpand_SetupIntroWatch(void *dst, const void *src);   /* 12 -> 12 bytes */
void geExpand_SetupIntroCredits(void *dst, const void *src);   /* 8 -> 8 bytes */
void geExpand_objective_entry(void *dst, const void *src);   /* 16 -> 16 bytes */
void geExpand_criteria_roomentered(void *dst, const void *src);   /* 16 -> 24 bytes */
void geExpand_criteria_deposit(void *dst, const void *src);   /* 20 -> 24 bytes */
void geExpand_criteria_picture(void *dst, const void *src);   /* 16 -> 24 bytes */
void geExpand_setup_objective_text(void *dst, const void *src);   /* 16 -> 24 bytes */

#ifdef __cplusplus
}
#endif

#endif /* GE_EXPAND_H */
