/*
 * ge_swap.h -- GENERATED by tools/gen_struct_swap.py. Do not edit.
 *
 * Byte-swap cartridge data in place, from the N64's layout.
 * Sizes and offsets come from a 32-bit DWARF build of the decomp's own
 * headers, so they are the compiler's answer rather than a transcription.
 *
 * Each function swaps ONE record in place. The struct must be pinned to the
 * N64 layout (pointer members as u32) for these offsets to describe it --
 * see PRIORITIES.md P3h.
 */
#ifndef GE_SWAP_H
#define GE_SWAP_H

#ifdef __cplusplus
extern "C" {
#endif

/* The primitives, exposed: a loader sometimes has to swap a single
 * field (a count it needs before it can size the rest of the table).
 */
void geSwap16(unsigned char *p);
void geSwap32(unsigned char *p);
void geSwap64(unsigned char *p);

void geSwap_Vertex(void *p);   /* 16 bytes on the N64 */
void geSwap_ModelAnimation(void *p);   /* 64 bytes on the N64 */
void geSwap_ModelAnimBitField(void *p);   /* 6 bytes on the N64 */
void geSwap_ModelFileHeader(void *p);   /* 32 bytes on the N64 */
void geSwap_ModelNode(void *p);   /* 24 bytes on the N64 */
void geSwap_ModelSkeleton(void *p);   /* 12 bytes on the N64 */
void geSwap_ModelRoData_HeaderRecord(void *p);   /* 16 bytes on the N64 */
void geSwap_ModelRoData_BSPRecord(void *p);   /* 36 bytes on the N64 */
void geSwap_ModelRoData_Child(void *p);   /* 8 bytes on the N64 */
void geSwap_ModelRoData_DisplayListRecord(void *p);   /* 20 bytes on the N64 */
void geSwap_ModelRoData_DisplayListPrimaryRecord(void *p);   /* 16 bytes on the N64 */
void geSwap_ModelRoData_GroupRecord(void *p);   /* 28 bytes on the N64 */
void geSwap_ModelRoData_GunfireRecord(void *p);   /* 40 bytes on the N64 */
void geSwap_ModelRoData_LODRecord(void *p);   /* 16 bytes on the N64 */
void geSwap_ModelRoData_ShadowRecord(void *p);   /* 32 bytes on the N64 */
void geSwap_ModelRoData_SwitchRecord(void *p);   /* 8 bytes on the N64 */
void geSwap_ModelRoData_Op05Record(void *p);   /* 424 bytes on the N64 */
void geSwap_ModelRoData_Op06Record(void *p);   /* 24 bytes on the N64 */
void geSwap_ModelRoData_Op07Record(void *p);   /* 432 bytes on the N64 */
void geSwap_ModelRoData_Op11Record(void *p);   /* 76 bytes on the N64 */
void geSwap_ModelRoData_Op17Record(void *p);   /* 32 bytes on the N64 */
void geSwap_StandFileHeader(void *p);   /* 8 bytes on the N64 */
void geSwap_StandFileFooter(void *p);   /* 24 bytes on the N64 */
void geSwap_BetaStandTile(void *p);   /* 12 bytes on the N64 */
void geSwap_ModelRoData_DisplayList_CollisionRecord(void *p);   /* 32 bytes on the N64 */
void geSwap_fontchar(void *p);   /* 24 bytes on the N64 */
void geSwap_ALBankFile(void *p);   /* 8 bytes on the N64 */
void geSwap_ALBank(void *p);   /* 16 bytes on the N64 */
void geSwap_ALInstrument(void *p);   /* 20 bytes on the N64 */
void geSwap_ALSound(void *p);   /* 16 bytes on the N64 */
void geSwap_ALKeyMap(void *p);   /* 6 bytes on the N64 */
void geSwap_ALEnvelope(void *p);   /* 16 bytes on the N64 */
void geSwap_RareALSeqData(void *p);   /* 8 bytes on the N64 */
void geSwap_PropDefHeaderRecord(void *p);   /* 4 bytes on the N64 */
void geSwap_ObjectRecord(void *p);   /* 128 bytes on the N64 */
void geSwap_GuardRecord(void *p);   /* 28 bytes on the N64 */
void geSwap_DoorRecord(void *p);   /* 256 bytes on the N64 */
void geSwap_GlobalDoorScaleRecord(void *p);   /* 8 bytes on the N64 */
void geSwap_KeyRecord(void *p);   /* 132 bytes on the N64 */
void geSwap_TintedGlassRecord(void *p);   /* 148 bytes on the N64 */
void geSwap_CCTVRecord(void *p);   /* 252 bytes on the N64 */
void geSwap_WeaponObjRecord(void *p);   /* 136 bytes on the N64 */
void geSwap_MonitorObjRecord(void *p);   /* 256 bytes on the N64 */
void geSwap_MultiMonitorObjRecord(void *p);   /* 596 bytes on the N64 */
void geSwap_AutogunRecord(void *p);   /* 216 bytes on the N64 */
void geSwap_LinkRecord(void *p);   /* 16 bytes on the N64 */
void geSwap_GuardAttributeRecord(void *p);   /* 12 bytes on the N64 */
void geSwap_MultiAmmoCrateRecord(void *p);   /* 180 bytes on the N64 */
void geSwap_BodyArmourRecord(void *p);   /* 136 bytes on the N64 */
void geSwap_TagObjectRecord(void *p);   /* 16 bytes on the N64 */
void geSwap_RenameObjectRecord(void *p);   /* 40 bytes on the N64 */
void geSwap_LockDoorRecord(void *p);   /* 16 bytes on the N64 */
void geSwap_VehichleRecord(void *p);   /* 176 bytes on the N64 */
void geSwap_AircraftRecord(void *p);   /* 180 bytes on the N64 */
void geSwap_TankRecord(void *p);   /* 224 bytes on the N64 */
void geSwap_CutsceneRecord(void *p);   /* 28 bytes on the N64 */
void geSwap_SafeObjectRecord(void *p);   /* 20 bytes on the N64 */
void geSwap_AmmoCrateRecord(void *p);   /* 132 bytes on the N64 */
void geSwap_HatRecord(void *p);   /* 128 bytes on the N64 */
void geSwap_GlassRecord(void *p);   /* 140 bytes on the N64 */
void geSwap_SafeRecord(void *p);   /* 140 bytes on the N64 */
void geSwap_GasReleasingRecord(void *p);   /* 6 bytes on the N64 */
void geSwap_objective_entry(void *p);   /* 16 bytes on the N64 */
void geSwap_criteria_roomentered(void *p);   /* 16 bytes on the N64 */
void geSwap_criteria_deposit(void *p);   /* 20 bytes on the N64 */
void geSwap_criteria_picture(void *p);   /* 16 bytes on the N64 */
void geSwap_setup_objective_text(void *p);   /* 16 bytes on the N64 */

/*
 * UNION HOOKS -- declared, deliberately not defined.
 *
 * A union has no single correct swap: which member is live decides the
 * field widths, and only the caller knows. These are left undefined so an
 * unimplemented one is a LINK ERROR. A generated guess would produce data
 * that decodes to the wrong numbers rather than failing.
 */
void geSwapUnion_Vertex__anon__at8(void *p);   /* Vertex.<anon>, 4 bytes */
void geSwapUnion_Vertex__anon__at12(void *p);   /* Vertex.<anon>, 4 bytes */
void geSwapUnion_ModelRoData_HeaderRecord__anon__at8(void *p);   /* ModelRoData_HeaderRecord.<anon>, 4 bytes */
void geSwapUnion_ModelRoData_Op11Record__anon__at0(void *p);   /* ModelRoData_Op11Record.<anon>, 64 bytes */
void geSwapUnion_ObjectRecord_mtx_at24(void *p);   /* ObjectRecord.mtx, 64 bytes */
void geSwapUnion_ObjectRecord_shadecol__anon__at120(void *p);   /* ObjectRecord.shadecol.<anon>, 4 bytes */
void geSwapUnion_ObjectRecord_nextcol__anon__at124(void *p);   /* ObjectRecord.nextcol.<anon>, 4 bytes */
void geSwapUnion_DoorRecord__anon__mtx_at24(void *p);   /* DoorRecord.<anon>.mtx, 64 bytes */
void geSwapUnion_DoorRecord__anon__shadecol__anon__at120(void *p);   /* DoorRecord.<anon>.shadecol.<anon>, 4 bytes */
void geSwapUnion_DoorRecord__anon__nextcol__anon__at124(void *p);   /* DoorRecord.<anon>.nextcol.<anon>, 4 bytes */
void geSwapUnion_KeyRecord__anon__mtx_at24(void *p);   /* KeyRecord.<anon>.mtx, 64 bytes */
void geSwapUnion_KeyRecord__anon__shadecol__anon__at120(void *p);   /* KeyRecord.<anon>.shadecol.<anon>, 4 bytes */
void geSwapUnion_KeyRecord__anon__nextcol__anon__at124(void *p);   /* KeyRecord.<anon>.nextcol.<anon>, 4 bytes */
void geSwapUnion_KeyRecord__anon__at128(void *p);   /* KeyRecord.<anon>, 4 bytes */
void geSwapUnion_TintedGlassRecord__anon__mtx_at24(void *p);   /* TintedGlassRecord.<anon>.mtx, 64 bytes */
void geSwapUnion_TintedGlassRecord__anon__shadecol__anon__at120(void *p);   /* TintedGlassRecord.<anon>.shadecol.<anon>, 4 bytes */
void geSwapUnion_TintedGlassRecord__anon__nextcol__anon__at124(void *p);   /* TintedGlassRecord.<anon>.nextcol.<anon>, 4 bytes */
void geSwapUnion_CCTVRecord__anon__mtx_at24(void *p);   /* CCTVRecord.<anon>.mtx, 64 bytes */
void geSwapUnion_CCTVRecord__anon__shadecol__anon__at120(void *p);   /* CCTVRecord.<anon>.shadecol.<anon>, 4 bytes */
void geSwapUnion_CCTVRecord__anon__nextcol__anon__at124(void *p);   /* CCTVRecord.<anon>.nextcol.<anon>, 4 bytes */
void geSwapUnion_CCTVRecord_unk84_at132(void *p);   /* CCTVRecord.unk84, 64 bytes */
void geSwapUnion_WeaponObjRecord__anon__mtx_at24(void *p);   /* WeaponObjRecord.<anon>.mtx, 64 bytes */
void geSwapUnion_WeaponObjRecord__anon__shadecol__anon__at120(void *p);   /* WeaponObjRecord.<anon>.shadecol.<anon>, 4 bytes */
void geSwapUnion_WeaponObjRecord__anon__nextcol__anon__at124(void *p);   /* WeaponObjRecord.<anon>.nextcol.<anon>, 4 bytes */
void geSwapUnion_MonitorObjRecord__anon__mtx_at24(void *p);   /* MonitorObjRecord.<anon>.mtx, 64 bytes */
void geSwapUnion_MonitorObjRecord__anon__shadecol__anon__at120(void *p);   /* MonitorObjRecord.<anon>.shadecol.<anon>, 4 bytes */
void geSwapUnion_MonitorObjRecord__anon__nextcol__anon__at124(void *p);   /* MonitorObjRecord.<anon>.nextcol.<anon>, 4 bytes */
void geSwapUnion_MultiMonitorObjRecord__anon__mtx_at24(void *p);   /* MultiMonitorObjRecord.<anon>.mtx, 64 bytes */
void geSwapUnion_MultiMonitorObjRecord__anon__shadecol__anon__at120(void *p);   /* MultiMonitorObjRecord.<anon>.shadecol.<anon>, 4 bytes */
void geSwapUnion_MultiMonitorObjRecord__anon__nextcol__anon__at124(void *p);   /* MultiMonitorObjRecord.<anon>.nextcol.<anon>, 4 bytes */
void geSwapUnion_AutogunRecord__anon__mtx_at24(void *p);   /* AutogunRecord.<anon>.mtx, 64 bytes */
void geSwapUnion_AutogunRecord__anon__shadecol__anon__at120(void *p);   /* AutogunRecord.<anon>.shadecol.<anon>, 4 bytes */
void geSwapUnion_AutogunRecord__anon__nextcol__anon__at124(void *p);   /* AutogunRecord.<anon>.nextcol.<anon>, 4 bytes */
void geSwapUnion_MultiAmmoCrateRecord__anon__mtx_at24(void *p);   /* MultiAmmoCrateRecord.<anon>.mtx, 64 bytes */
void geSwapUnion_MultiAmmoCrateRecord__anon__shadecol__anon__at120(void *p);   /* MultiAmmoCrateRecord.<anon>.shadecol.<anon>, 4 bytes */
void geSwapUnion_MultiAmmoCrateRecord__anon__nextcol__anon__at124(void *p);   /* MultiAmmoCrateRecord.<anon>.nextcol.<anon>, 4 bytes */
void geSwapUnion_BodyArmourRecord__anon__mtx_at24(void *p);   /* BodyArmourRecord.<anon>.mtx, 64 bytes */
void geSwapUnion_BodyArmourRecord__anon__shadecol__anon__at120(void *p);   /* BodyArmourRecord.<anon>.shadecol.<anon>, 4 bytes */
void geSwapUnion_BodyArmourRecord__anon__nextcol__anon__at124(void *p);   /* BodyArmourRecord.<anon>.nextcol.<anon>, 4 bytes */
void geSwapUnion_VehichleRecord__anon__mtx_at24(void *p);   /* VehichleRecord.<anon>.mtx, 64 bytes */
void geSwapUnion_VehichleRecord__anon__shadecol__anon__at120(void *p);   /* VehichleRecord.<anon>.shadecol.<anon>, 4 bytes */
void geSwapUnion_VehichleRecord__anon__nextcol__anon__at124(void *p);   /* VehichleRecord.<anon>.nextcol.<anon>, 4 bytes */
void geSwapUnion_AircraftRecord__anon__mtx_at24(void *p);   /* AircraftRecord.<anon>.mtx, 64 bytes */
void geSwapUnion_AircraftRecord__anon__shadecol__anon__at120(void *p);   /* AircraftRecord.<anon>.shadecol.<anon>, 4 bytes */
void geSwapUnion_AircraftRecord__anon__nextcol__anon__at124(void *p);   /* AircraftRecord.<anon>.nextcol.<anon>, 4 bytes */
void geSwapUnion_TankRecord__anon__mtx_at24(void *p);   /* TankRecord.<anon>.mtx, 64 bytes */
void geSwapUnion_TankRecord__anon__shadecol__anon__at120(void *p);   /* TankRecord.<anon>.shadecol.<anon>, 4 bytes */
void geSwapUnion_TankRecord__anon__nextcol__anon__at124(void *p);   /* TankRecord.<anon>.nextcol.<anon>, 4 bytes */
void geSwapUnion_AmmoCrateRecord__anon__mtx_at24(void *p);   /* AmmoCrateRecord.<anon>.mtx, 64 bytes */
void geSwapUnion_AmmoCrateRecord__anon__shadecol__anon__at120(void *p);   /* AmmoCrateRecord.<anon>.shadecol.<anon>, 4 bytes */
void geSwapUnion_AmmoCrateRecord__anon__nextcol__anon__at124(void *p);   /* AmmoCrateRecord.<anon>.nextcol.<anon>, 4 bytes */
void geSwapUnion_HatRecord__anon__mtx_at24(void *p);   /* HatRecord.<anon>.mtx, 64 bytes */
void geSwapUnion_HatRecord__anon__shadecol__anon__at120(void *p);   /* HatRecord.<anon>.shadecol.<anon>, 4 bytes */
void geSwapUnion_HatRecord__anon__nextcol__anon__at124(void *p);   /* HatRecord.<anon>.nextcol.<anon>, 4 bytes */
void geSwapUnion_GlassRecord__anon__mtx_at24(void *p);   /* GlassRecord.<anon>.mtx, 64 bytes */
void geSwapUnion_GlassRecord__anon__shadecol__anon__at120(void *p);   /* GlassRecord.<anon>.shadecol.<anon>, 4 bytes */
void geSwapUnion_GlassRecord__anon__nextcol__anon__at124(void *p);   /* GlassRecord.<anon>.nextcol.<anon>, 4 bytes */
void geSwapUnion_SafeRecord__anon__mtx_at24(void *p);   /* SafeRecord.<anon>.mtx, 64 bytes */
void geSwapUnion_SafeRecord__anon__shadecol__anon__at120(void *p);   /* SafeRecord.<anon>.shadecol.<anon>, 4 bytes */
void geSwapUnion_SafeRecord__anon__nextcol__anon__at124(void *p);   /* SafeRecord.<anon>.nextcol.<anon>, 4 bytes */

#ifdef __cplusplus
}
#endif

#endif /* GE_SWAP_H */
