/*
 * ge_swap.c -- GENERATED by tools/gen_struct_swap.py. Do not edit.
 */
#include "ge_swap.h"

void geSwap16(unsigned char *p)
{
    unsigned char t = p[0]; p[0] = p[1]; p[1] = t;
}

void geSwap32(unsigned char *p)
{
    unsigned char t;
    t = p[0]; p[0] = p[3]; p[3] = t;
    t = p[1]; p[1] = p[2]; p[2] = t;
}

void geSwap64(unsigned char *p)
{
    unsigned char t; int i;
    for (i = 0; i < 4; ++i) { t = p[i]; p[i] = p[7-i]; p[7-i] = t; }
}

/* Vertex: 16 bytes on the N64 */
void geSwap_Vertex(void *p)
{
    /* union Vertex.coord.<anon>: every arm swaps identically -- no ambiguity */
    geSwap16((unsigned char *)p + 0);   /* Vertex.coord.<anon>.x */
    geSwap16((unsigned char *)p + 2);   /* Vertex.coord.<anon>.y */
    geSwap16((unsigned char *)p + 4);   /* Vertex.coord.<anon>.z */
    geSwap16((unsigned char *)p + 6);   /* Vertex.index */
    geSwapUnion_Vertex__anon__at8((unsigned char *)p + 8);  /* union: Vertex.<anon> -- see the hook */
    geSwapUnion_Vertex__anon__at12((unsigned char *)p + 12);  /* union: Vertex.<anon> -- see the hook */
}

/* ModelAnimation: 64 bytes on the N64 */
void geSwap_ModelAnimation(void *p)
{
    geSwap32((unsigned char *)p + 0);   /* ModelAnimation.address */
    geSwap16((unsigned char *)p + 4);   /* ModelAnimation.unk04 */
    geSwap32((unsigned char *)p + 8);   /* ModelAnimation.bitDescriptors */
    geSwap16((unsigned char *)p + 12);   /* ModelAnimation.unk0C */
    geSwap16((unsigned char *)p + 14);   /* ModelAnimation.unk0E */
    geSwap32((unsigned char *)p + 16);   /* ModelAnimation.bitStream */
    geSwap32((unsigned char *)p + 20);   /* ModelAnimation.unk14 */
    geSwap32((unsigned char *)p + 24);   /* ModelAnimation.unk18 */
    geSwap32((unsigned char *)p + 28);   /* ModelAnimation.unk1c */
    geSwap32((unsigned char *)p + 32);   /* ModelAnimation.unk20 */
    geSwap32((unsigned char *)p + 36);   /* ModelAnimation.unk24 */
    geSwap32((unsigned char *)p + 40);   /* ModelAnimation.unk28 */
    geSwap32((unsigned char *)p + 44);   /* ModelAnimation.unk2c */
    geSwap32((unsigned char *)p + 48);   /* ModelAnimation.unk30 */
    geSwap32((unsigned char *)p + 52);   /* ModelAnimation.unk34 */
    geSwap32((unsigned char *)p + 56);   /* ModelAnimation.unk38 */
    geSwap32((unsigned char *)p + 60);   /* ModelAnimation.unk3c */
}

/* ModelAnimBitField: 6 bytes on the N64 */
void geSwap_ModelAnimBitField(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* ModelAnimBitField.bitOffset */
    geSwap16((unsigned char *)p + 4);   /* ModelAnimBitField.valueOffset */
}

/* ModelFileHeader: 32 bytes on the N64 */
void geSwap_ModelFileHeader(void *p)
{
    geSwap32((unsigned char *)p + 0);   /* ModelFileHeader.RootNode */
    geSwap32((unsigned char *)p + 4);   /* ModelFileHeader.Skeleton */
    geSwap32((unsigned char *)p + 8);   /* ModelFileHeader.Switches */
    geSwap16((unsigned char *)p + 12);   /* ModelFileHeader.numSwitches */
    geSwap16((unsigned char *)p + 14);   /* ModelFileHeader.numMatrices */
    geSwap32((unsigned char *)p + 16);   /* ModelFileHeader.BoundingVolumeRadius */
    geSwap16((unsigned char *)p + 20);   /* ModelFileHeader.numRecords */
    geSwap16((unsigned char *)p + 22);   /* ModelFileHeader.numtextures */
    geSwap32((unsigned char *)p + 24);   /* ModelFileHeader.Textures */
    geSwap32((unsigned char *)p + 28);   /* ModelFileHeader.isLoaded */
}

/* ModelNode: 24 bytes on the N64 */
void geSwap_ModelNode(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* ModelNode.Opcode */
    geSwap32((unsigned char *)p + 4);   /* ModelNode.Data */
    geSwap32((unsigned char *)p + 8);   /* ModelNode.Parent */
    geSwap32((unsigned char *)p + 12);   /* ModelNode.Next */
    geSwap32((unsigned char *)p + 16);   /* ModelNode.Prev */
    geSwap32((unsigned char *)p + 20);   /* ModelNode.Child */
}

/* ModelSkeleton: 12 bytes on the N64 */
void geSwap_ModelSkeleton(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* ModelSkeleton.numjoints */
    geSwap16((unsigned char *)p + 2);   /* ModelSkeleton.pad1 */
    geSwap32((unsigned char *)p + 4);   /* ModelSkeleton.Joints */
    geSwap16((unsigned char *)p + 8);   /* ModelSkeleton.SkeletonSize */
    geSwap16((unsigned char *)p + 10);   /* ModelSkeleton.pad2 */
}

/* ModelRoData_HeaderRecord: 16 bytes on the N64 */
void geSwap_ModelRoData_HeaderRecord(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* ModelRoData_HeaderRecord.AnimPart */
    geSwap16((unsigned char *)p + 2);   /* ModelRoData_HeaderRecord.MatrixIndex */
    /* union ModelRoData_HeaderRecord.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 4);   /* ModelRoData_HeaderRecord.<anon> */
    geSwapUnion_ModelRoData_HeaderRecord__anon__at8((unsigned char *)p + 8);  /* union: ModelRoData_HeaderRecord.<anon> -- see the hook */
    geSwap16((unsigned char *)p + 12);   /* ModelRoData_HeaderRecord.RwDataIndex */
    geSwap16((unsigned char *)p + 14);   /* ModelRoData_HeaderRecord.reserved */
}

/* ModelRoData_BSPRecord: 36 bytes on the N64 */
void geSwap_ModelRoData_BSPRecord(void *p)
{
    /* union ModelRoData_BSPRecord.Point.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 0);   /* ModelRoData_BSPRecord.Point.<anon>.x */
    geSwap32((unsigned char *)p + 4);   /* ModelRoData_BSPRecord.Point.<anon>.y */
    geSwap32((unsigned char *)p + 8);   /* ModelRoData_BSPRecord.Point.<anon>.z */
    /* union ModelRoData_BSPRecord.Vector.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 12);   /* ModelRoData_BSPRecord.Vector.<anon>.x */
    geSwap32((unsigned char *)p + 16);   /* ModelRoData_BSPRecord.Vector.<anon>.y */
    geSwap32((unsigned char *)p + 20);   /* ModelRoData_BSPRecord.Vector.<anon>.z */
    geSwap32((unsigned char *)p + 24);   /* ModelRoData_BSPRecord.leftChild */
    geSwap32((unsigned char *)p + 28);   /* ModelRoData_BSPRecord.rightChild */
    geSwap16((unsigned char *)p + 32);   /* ModelRoData_BSPRecord.reserved */
    geSwap16((unsigned char *)p + 34);   /* ModelRoData_BSPRecord.RwDataIndex */
}

/* ModelRoData_Child: 8 bytes on the N64 */
void geSwap_ModelRoData_Child(void *p)
{
    geSwap16((unsigned char *)p + 2);   /* ModelRoData_Child.unk02 */
    geSwap32((unsigned char *)p + 4);   /* ModelRoData_Child.unk04 */
}

/* ModelRoData_DisplayListRecord: 20 bytes on the N64 */
void geSwap_ModelRoData_DisplayListRecord(void *p)
{
    geSwap32((unsigned char *)p + 0);   /* ModelRoData_DisplayListRecord.Primary */
    geSwap32((unsigned char *)p + 4);   /* ModelRoData_DisplayListRecord.Secondary */
    geSwap32((unsigned char *)p + 8);   /* ModelRoData_DisplayListRecord.BaseAddr */
    geSwap32((unsigned char *)p + 12);   /* ModelRoData_DisplayListRecord.Vertices */
    geSwap16((unsigned char *)p + 16);   /* ModelRoData_DisplayListRecord.numVertices */
}

/* ModelRoData_DisplayListPrimaryRecord: 16 bytes on the N64 */
void geSwap_ModelRoData_DisplayListPrimaryRecord(void *p)
{
    geSwap32((unsigned char *)p + 0);   /* ModelRoData_DisplayListPrimaryRecord.numVertices */
    geSwap32((unsigned char *)p + 4);   /* ModelRoData_DisplayListPrimaryRecord.Vertices */
    geSwap32((unsigned char *)p + 8);   /* ModelRoData_DisplayListPrimaryRecord.Primary */
    geSwap32((unsigned char *)p + 12);   /* ModelRoData_DisplayListPrimaryRecord.BaseAddr */
}

/* ModelRoData_GroupRecord: 28 bytes on the N64 */
void geSwap_ModelRoData_GroupRecord(void *p)
{
    /* union ModelRoData_GroupRecord.Origin.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 0);   /* ModelRoData_GroupRecord.Origin.<anon>.x */
    geSwap32((unsigned char *)p + 4);   /* ModelRoData_GroupRecord.Origin.<anon>.y */
    geSwap32((unsigned char *)p + 8);   /* ModelRoData_GroupRecord.Origin.<anon>.z */
    geSwap16((unsigned char *)p + 12);   /* ModelRoData_GroupRecord.JointID */
    /* union ModelRoData_GroupRecord.<anon>: every arm swaps identically -- no ambiguity */
    geSwap16((unsigned char *)p + 14);   /* ModelRoData_GroupRecord.<anon>[0] */
    geSwap16((unsigned char *)p + 16);   /* ModelRoData_GroupRecord.<anon>[1] */
    geSwap16((unsigned char *)p + 18);   /* ModelRoData_GroupRecord.<anon>[2] */
    /* union ModelRoData_GroupRecord.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 20);   /* ModelRoData_GroupRecord.<anon> */
    geSwap32((unsigned char *)p + 24);   /* ModelRoData_GroupRecord.BoundingVolumeRadius */
}

/* ModelRoData_GunfireRecord: 40 bytes on the N64 */
void geSwap_ModelRoData_GunfireRecord(void *p)
{
    /* union ModelRoData_GunfireRecord.Offset.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 0);   /* ModelRoData_GunfireRecord.Offset.<anon>.x */
    geSwap32((unsigned char *)p + 4);   /* ModelRoData_GunfireRecord.Offset.<anon>.y */
    geSwap32((unsigned char *)p + 8);   /* ModelRoData_GunfireRecord.Offset.<anon>.z */
    /* union ModelRoData_GunfireRecord.Size.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 12);   /* ModelRoData_GunfireRecord.Size.<anon>.x */
    geSwap32((unsigned char *)p + 16);   /* ModelRoData_GunfireRecord.Size.<anon>.y */
    geSwap32((unsigned char *)p + 20);   /* ModelRoData_GunfireRecord.Size.<anon>.z */
    geSwap32((unsigned char *)p + 24);   /* ModelRoData_GunfireRecord.Image */
    geSwap32((unsigned char *)p + 28);   /* ModelRoData_GunfireRecord.Scale */
    geSwap16((unsigned char *)p + 32);   /* ModelRoData_GunfireRecord.RwDataIndex */
    geSwap16((unsigned char *)p + 34);   /* ModelRoData_GunfireRecord.reserved */
    geSwap32((unsigned char *)p + 36);   /* ModelRoData_GunfireRecord.BaseAddr */
}

/* ModelRoData_LODRecord: 16 bytes on the N64 */
void geSwap_ModelRoData_LODRecord(void *p)
{
    geSwap32((unsigned char *)p + 0);   /* ModelRoData_LODRecord.MinDistance */
    geSwap32((unsigned char *)p + 4);   /* ModelRoData_LODRecord.MaxDistance */
    geSwap32((unsigned char *)p + 8);   /* ModelRoData_LODRecord.Affects */
    geSwap16((unsigned char *)p + 12);   /* ModelRoData_LODRecord.RwDataIndex */
    geSwap16((unsigned char *)p + 14);   /* ModelRoData_LODRecord.reserved */
}

/* ModelRoData_ShadowRecord: 32 bytes on the N64 */
void geSwap_ModelRoData_ShadowRecord(void *p)
{
    /* union ModelRoData_ShadowRecord.pos.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 0);   /* ModelRoData_ShadowRecord.pos.<anon>.x */
    geSwap32((unsigned char *)p + 4);   /* ModelRoData_ShadowRecord.pos.<anon>.y */
    /* union ModelRoData_ShadowRecord.size.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 8);   /* ModelRoData_ShadowRecord.size.<anon>.x */
    geSwap32((unsigned char *)p + 12);   /* ModelRoData_ShadowRecord.size.<anon>.y */
    geSwap32((unsigned char *)p + 16);   /* ModelRoData_ShadowRecord.image */
    /* union ModelRoData_ShadowRecord.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 20);   /* ModelRoData_ShadowRecord.<anon> */
    geSwap32((unsigned char *)p + 24);   /* ModelRoData_ShadowRecord.Scale */
    geSwap32((unsigned char *)p + 28);   /* ModelRoData_ShadowRecord.BaseAddr */
}

/* ModelRoData_SwitchRecord: 8 bytes on the N64 */
void geSwap_ModelRoData_SwitchRecord(void *p)
{
    geSwap32((unsigned char *)p + 0);   /* ModelRoData_SwitchRecord.Controls */
    geSwap16((unsigned char *)p + 4);   /* ModelRoData_SwitchRecord.RwDataIndex */
    geSwap16((unsigned char *)p + 6);   /* ModelRoData_SwitchRecord.reserved */
}

/* ModelRoData_Op05Record: 424 bytes on the N64 */
void geSwap_ModelRoData_Op05Record(void *p)
{
    geSwap32((unsigned char *)p + 0);   /* ModelRoData_Op05Record.NumChildren */
    geSwap32((unsigned char *)p + 4);   /* ModelRoData_Op05Record.Children */
    geSwap32((unsigned char *)p + 8);   /* ModelRoData_Op05Record.Vertices */
    geSwap32((unsigned char *)p + 12);   /* ModelRoData_Op05Record.Images */
    geSwap32((unsigned char *)p + 416);   /* ModelRoData_Op05Record.unk1A0 */
    geSwap32((unsigned char *)p + 420);   /* ModelRoData_Op05Record.BaseAddr */
}

/* ModelRoData_Op06Record: 24 bytes on the N64 */
void geSwap_ModelRoData_Op06Record(void *p)
{
    geSwap32((unsigned char *)p + 0);   /* ModelRoData_Op06Record.unk00 */
    geSwap32((unsigned char *)p + 4);   /* ModelRoData_Op06Record.unk04 */
    geSwap32((unsigned char *)p + 8);   /* ModelRoData_Op06Record.unk08 */
    geSwap32((unsigned char *)p + 12);   /* ModelRoData_Op06Record.unk0C */
    geSwap32((unsigned char *)p + 16);   /* ModelRoData_Op06Record.unk10 */
    geSwap32((unsigned char *)p + 20);   /* ModelRoData_Op06Record.BaseAddr */
}

/* ModelRoData_Op07Record: 432 bytes on the N64 */
void geSwap_ModelRoData_Op07Record(void *p)
{
    geSwap32((unsigned char *)p + 0);   /* ModelRoData_Op07Record.unk00 */
    geSwap32((unsigned char *)p + 4);   /* ModelRoData_Op07Record.unk04 */
    geSwap32((unsigned char *)p + 8);   /* ModelRoData_Op07Record.NumChildren */
    geSwap32((unsigned char *)p + 12);   /* ModelRoData_Op07Record.Children */
    geSwap32((unsigned char *)p + 16);   /* ModelRoData_Op07Record.Vertices */
    geSwap32((unsigned char *)p + 20);   /* ModelRoData_Op07Record.Images */
    geSwap16((unsigned char *)p + 424);   /* ModelRoData_Op07Record.unk1A8 */
    geSwap16((unsigned char *)p + 426);   /* ModelRoData_Op07Record.RwDataIndex */
    geSwap32((unsigned char *)p + 428);   /* ModelRoData_Op07Record.BaseAddr */
}

/* ModelRoData_Op11Record: 76 bytes on the N64 */
void geSwap_ModelRoData_Op11Record(void *p)
{
    geSwapUnion_ModelRoData_Op11Record__anon__at0((unsigned char *)p + 0);  /* union: ModelRoData_Op11Record.<anon> -- see the hook */
    geSwap32((unsigned char *)p + 64);   /* ModelRoData_Op11Record.BoundingVolumeRadius */
    geSwap16((unsigned char *)p + 68);   /* ModelRoData_Op11Record.RwDataIndex */
    geSwap16((unsigned char *)p + 70);   /* ModelRoData_Op11Record.unk46 */
    geSwap32((unsigned char *)p + 72);   /* ModelRoData_Op11Record.BaseAddr */
}

/* ModelRoData_Op17Record: 32 bytes on the N64 */
void geSwap_ModelRoData_Op17Record(void *p)
{
    geSwap32((unsigned char *)p + 0);   /* ModelRoData_Op17Record.hitpart */
    geSwap32((unsigned char *)p + 4);   /* ModelRoData_Op17Record.radiusSq */
    /* union ModelRoData_Op17Record.pos.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 8);   /* ModelRoData_Op17Record.pos.<anon>.x */
    geSwap32((unsigned char *)p + 12);   /* ModelRoData_Op17Record.pos.<anon>.y */
    geSwap32((unsigned char *)p + 16);   /* ModelRoData_Op17Record.pos.<anon>.z */
    geSwap32((unsigned char *)p + 20);   /* ModelRoData_Op17Record.othernode */
    geSwap32((unsigned char *)p + 24);   /* ModelRoData_Op17Record.scale1 */
    geSwap32((unsigned char *)p + 28);   /* ModelRoData_Op17Record.scale2 */
}

/* StandFileHeader: 8 bytes on the N64 */
void geSwap_StandFileHeader(void *p)
{
    geSwap32((unsigned char *)p + 0);   /* StandFileHeader.unk1 */
    geSwap32((unsigned char *)p + 4);   /* StandFileHeader.firstTile */
    /* StandFileHeader.unk2: array of unknown extent, NOT swapped */
}

/* StandFileFooter: 24 bytes on the N64 */
void geSwap_StandFileFooter(void *p)
{
    geSwap32((unsigned char *)p + 8);   /* StandFileFooter.unk3 */
    geSwap32((unsigned char *)p + 12);   /* StandFileFooter.unk4 */
    geSwap32((unsigned char *)p + 16);   /* StandFileFooter.unk5 */
    geSwap32((unsigned char *)p + 20);   /* StandFileFooter.unk6 */
}

/* BetaStandTile: 12 bytes on the N64 */
void geSwap_BetaStandTile(void *p)
{
    geSwap32((unsigned char *)p + 0);   /* BetaStandTile.id */
    /* BetaStandTile.headerMid.b: bitfield, swapped with its storage unit */
    /* BetaStandTile.headerMid.g: bitfield, swapped with its storage unit */
    /* BetaStandTile.headerMid.r: bitfield, swapped with its storage unit */
    /* BetaStandTile.headerMid.special: bitfield, swapped with its storage unit */
    geSwap16((unsigned char *)p + 6);   /* BetaStandTile.betaUnknown */
    /* BetaStandTile.points: array of unknown extent, NOT swapped */
}

/* ModelRoData_DisplayList_CollisionRecord: 32 bytes on the N64 */
void geSwap_ModelRoData_DisplayList_CollisionRecord(void *p)
{
    geSwap32((unsigned char *)p + 0);   /* ModelRoData_DisplayList_CollisionRecord.Primary */
    geSwap32((unsigned char *)p + 4);   /* ModelRoData_DisplayList_CollisionRecord.Secondary */
    geSwap32((unsigned char *)p + 8);   /* ModelRoData_DisplayList_CollisionRecord.Vertices */
    geSwap16((unsigned char *)p + 12);   /* ModelRoData_DisplayList_CollisionRecord.numVertices */
    geSwap16((unsigned char *)p + 14);   /* ModelRoData_DisplayList_CollisionRecord.numCollisionVertices */
    geSwap32((unsigned char *)p + 16);   /* ModelRoData_DisplayList_CollisionRecord.CollisionVertices */
    geSwap32((unsigned char *)p + 20);   /* ModelRoData_DisplayList_CollisionRecord.PointUsage */
    geSwap16((unsigned char *)p + 24);   /* ModelRoData_DisplayList_CollisionRecord.ModelType */
    geSwap16((unsigned char *)p + 26);   /* ModelRoData_DisplayList_CollisionRecord.RwDataIndex */
    geSwap32((unsigned char *)p + 28);   /* ModelRoData_DisplayList_CollisionRecord.BaseAddr */
}

/* fontchar: 24 bytes on the N64 */
void geSwap_fontchar(void *p)
{
    geSwap32((unsigned char *)p + 0);   /* fontchar.index */
    geSwap32((unsigned char *)p + 4);   /* fontchar.baseline */
    geSwap32((unsigned char *)p + 8);   /* fontchar.height */
    geSwap32((unsigned char *)p + 12);   /* fontchar.width */
    geSwap32((unsigned char *)p + 16);   /* fontchar.kerningindex */
    geSwap32((unsigned char *)p + 20);   /* fontchar.pixeldata */
}

/* ALBankFile: 8 bytes on the N64 */
void geSwap_ALBankFile(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* ALBankFile.revision */
    geSwap16((unsigned char *)p + 2);   /* ALBankFile.bankCount */
    geSwap32((unsigned char *)p + 4);   /* ALBankFile.bankArray[0] */
}

/* ALBank: 16 bytes on the N64 */
void geSwap_ALBank(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* ALBank.instCount */
    geSwap32((unsigned char *)p + 4);   /* ALBank.sampleRate */
    geSwap32((unsigned char *)p + 8);   /* ALBank.percussion */
    geSwap32((unsigned char *)p + 12);   /* ALBank.instArray[0] */
}

/* ALInstrument: 20 bytes on the N64 */
void geSwap_ALInstrument(void *p)
{
    geSwap16((unsigned char *)p + 12);   /* ALInstrument.bendRange */
    geSwap16((unsigned char *)p + 14);   /* ALInstrument.soundCount */
    geSwap32((unsigned char *)p + 16);   /* ALInstrument.soundArray[0] */
}

/* ALSound: 16 bytes on the N64 */
void geSwap_ALSound(void *p)
{
    geSwap32((unsigned char *)p + 0);   /* ALSound.envelope */
    geSwap32((unsigned char *)p + 4);   /* ALSound.keyMap */
    geSwap32((unsigned char *)p + 8);   /* ALSound.wavetable */
}

/* ALKeyMap: 6 bytes on the N64 */
void geSwap_ALKeyMap(void *p)
{
    (void)p;
}

/* ALEnvelope: 16 bytes on the N64 */
void geSwap_ALEnvelope(void *p)
{
    geSwap32((unsigned char *)p + 0);   /* ALEnvelope.attackTime */
    geSwap32((unsigned char *)p + 4);   /* ALEnvelope.decayTime */
    geSwap32((unsigned char *)p + 8);   /* ALEnvelope.releaseTime */
}

/* RareALSeqData: 8 bytes on the N64 */
void geSwap_RareALSeqData(void *p)
{
    geSwap32((unsigned char *)p + 0);   /* RareALSeqData.address */
    geSwap16((unsigned char *)p + 4);   /* RareALSeqData.uncompressed_len */
    geSwap16((unsigned char *)p + 6);   /* RareALSeqData.len */
}

/* PropDefHeaderRecord: 4 bytes on the N64 */
void geSwap_PropDefHeaderRecord(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* PropDefHeaderRecord.extrascale */
}

/* ObjectRecord: 128 bytes on the N64 */
void geSwap_ObjectRecord(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* ObjectRecord.<anon>.extrascale */
    geSwap16((unsigned char *)p + 4);   /* ObjectRecord.obj */
    geSwap16((unsigned char *)p + 6);   /* ObjectRecord.pad */
    geSwap32((unsigned char *)p + 8);   /* ObjectRecord.flags */
    geSwap32((unsigned char *)p + 12);   /* ObjectRecord.flags2 */
    geSwap32((unsigned char *)p + 16);   /* ObjectRecord.prop */
    geSwap32((unsigned char *)p + 20);   /* ObjectRecord.model */
    geSwapUnion_ObjectRecord_mtx_at24((unsigned char *)p + 24);  /* union: ObjectRecord.mtx -- see the hook */
    /* union ObjectRecord.runtime_pos.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 88);   /* ObjectRecord.runtime_pos.<anon>.x */
    geSwap32((unsigned char *)p + 92);   /* ObjectRecord.runtime_pos.<anon>.y */
    geSwap32((unsigned char *)p + 96);   /* ObjectRecord.runtime_pos.<anon>.z */
    /* union ObjectRecord.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 100);   /* ObjectRecord.<anon> */
    geSwap32((unsigned char *)p + 104);   /* ObjectRecord.ptr_allocated_collisiondata_block */
    /* union ObjectRecord.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 108);   /* ObjectRecord.<anon> */
    geSwap32((unsigned char *)p + 112);   /* ObjectRecord.maxdamage */
    geSwap32((unsigned char *)p + 116);   /* ObjectRecord.damage */
    geSwapUnion_ObjectRecord_shadecol__anon__at120((unsigned char *)p + 120);  /* union: ObjectRecord.shadecol.<anon> -- see the hook */
    geSwapUnion_ObjectRecord_nextcol__anon__at124((unsigned char *)p + 124);  /* union: ObjectRecord.nextcol.<anon> -- see the hook */
}

/* GuardRecord: 28 bytes on the N64 */
void geSwap_GuardRecord(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* GuardRecord.<anon>.extrascale */
    geSwap16((unsigned char *)p + 4);   /* GuardRecord.chrnum */
    geSwap16((unsigned char *)p + 6);   /* GuardRecord.PadID */
    geSwap16((unsigned char *)p + 8);   /* GuardRecord.BodyID */
    geSwap16((unsigned char *)p + 10);   /* GuardRecord.AIListID */
    geSwap16((unsigned char *)p + 12);   /* GuardRecord.Preset */
    geSwap16((unsigned char *)p + 14);   /* GuardRecord.chrpreset1 */
    geSwap16((unsigned char *)p + 16);   /* GuardRecord.health */
    geSwap16((unsigned char *)p + 18);   /* GuardRecord.ReactionTime */
    geSwap16((unsigned char *)p + 20);   /* GuardRecord.bitflags */
    geSwap16((unsigned char *)p + 22);   /* GuardRecord.HeadID */
    geSwap32((unsigned char *)p + 24);   /* GuardRecord.Data */
}

/* DoorRecord: 256 bytes on the N64 */
void geSwap_DoorRecord(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* DoorRecord.<anon>.<anon>.extrascale */
    geSwap16((unsigned char *)p + 4);   /* DoorRecord.<anon>.obj */
    geSwap16((unsigned char *)p + 6);   /* DoorRecord.<anon>.pad */
    geSwap32((unsigned char *)p + 8);   /* DoorRecord.<anon>.flags */
    geSwap32((unsigned char *)p + 12);   /* DoorRecord.<anon>.flags2 */
    geSwap32((unsigned char *)p + 16);   /* DoorRecord.<anon>.prop */
    geSwap32((unsigned char *)p + 20);   /* DoorRecord.<anon>.model */
    geSwapUnion_DoorRecord__anon__mtx_at24((unsigned char *)p + 24);  /* union: DoorRecord.<anon>.mtx -- see the hook */
    /* union DoorRecord.<anon>.runtime_pos.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 88);   /* DoorRecord.<anon>.runtime_pos.<anon>.x */
    geSwap32((unsigned char *)p + 92);   /* DoorRecord.<anon>.runtime_pos.<anon>.y */
    geSwap32((unsigned char *)p + 96);   /* DoorRecord.<anon>.runtime_pos.<anon>.z */
    /* union DoorRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 100);   /* DoorRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 104);   /* DoorRecord.<anon>.ptr_allocated_collisiondata_block */
    /* union DoorRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 108);   /* DoorRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 112);   /* DoorRecord.<anon>.maxdamage */
    geSwap32((unsigned char *)p + 116);   /* DoorRecord.<anon>.damage */
    geSwapUnion_DoorRecord__anon__shadecol__anon__at120((unsigned char *)p + 120);  /* union: DoorRecord.<anon>.shadecol.<anon> -- see the hook */
    geSwapUnion_DoorRecord__anon__nextcol__anon__at124((unsigned char *)p + 124);  /* union: DoorRecord.<anon>.nextcol.<anon> -- see the hook */
    geSwap32((unsigned char *)p + 128);   /* DoorRecord.linkedDoorOffset */
    geSwap32((unsigned char *)p + 132);   /* DoorRecord.maxFrac */
    geSwap32((unsigned char *)p + 136);   /* DoorRecord.perimFrac */
    geSwap32((unsigned char *)p + 140);   /* DoorRecord.accel */
    geSwap32((unsigned char *)p + 144);   /* DoorRecord.decel */
    geSwap32((unsigned char *)p + 148);   /* DoorRecord.maxSpeed */
    geSwap16((unsigned char *)p + 152);   /* DoorRecord.doorFlags */
    geSwap16((unsigned char *)p + 154);   /* DoorRecord.doorType */
    geSwap32((unsigned char *)p + 156);   /* DoorRecord.keyflags */
    geSwap32((unsigned char *)p + 160);   /* DoorRecord.autoCloseFrames */
    geSwap32((unsigned char *)p + 164);   /* DoorRecord.doorOpenSound */
    geSwap32((unsigned char *)p + 168);   /* DoorRecord.frac */
    geSwap32((unsigned char *)p + 172);   /* DoorRecord.unkac */
    geSwap32((unsigned char *)p + 176);   /* DoorRecord.unkb0 */
    geSwap32((unsigned char *)p + 180);   /* DoorRecord.openPosition */
    geSwap32((unsigned char *)p + 184);   /* DoorRecord.speed */
    geSwap16((unsigned char *)p + 190);   /* DoorRecord.calculatedopacity */
    geSwap32((unsigned char *)p + 192);   /* DoorRecord.TintDist */
    geSwap16((unsigned char *)p + 196);   /* DoorRecord.CullDist */
    geSwap32((unsigned char *)p + 200);   /* DoorRecord.linkedDoor */
    geSwap32((unsigned char *)p + 204);   /* DoorRecord.unkcc */
    geSwap32((unsigned char *)p + 208);   /* DoorRecord.bbox.ModelNumber */
    /* union DoorRecord.bbox.Bounds.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 212);   /* DoorRecord.bbox.Bounds.<anon>.xmin */
    geSwap32((unsigned char *)p + 216);   /* DoorRecord.bbox.Bounds.<anon>.xmax */
    geSwap32((unsigned char *)p + 220);   /* DoorRecord.bbox.Bounds.<anon>.ymin */
    geSwap32((unsigned char *)p + 224);   /* DoorRecord.bbox.Bounds.<anon>.ymax */
    geSwap32((unsigned char *)p + 228);   /* DoorRecord.bbox.Bounds.<anon>.zmin */
    geSwap32((unsigned char *)p + 232);   /* DoorRecord.bbox.Bounds.<anon>.zmax */
    geSwap32((unsigned char *)p + 236);   /* DoorRecord.openedTime */
    geSwap32((unsigned char *)p + 240);   /* DoorRecord.portalNumber */
    geSwap32((unsigned char *)p + 244);   /* DoorRecord.openSoundState */
    geSwap32((unsigned char *)p + 248);   /* DoorRecord.closeSoundState */
    /* union DoorRecord.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 252);   /* DoorRecord.<anon> */
}

/* GlobalDoorScaleRecord: 8 bytes on the N64 */
void geSwap_GlobalDoorScaleRecord(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* GlobalDoorScaleRecord.<anon>.extrascale */
    geSwap32((unsigned char *)p + 4);   /* GlobalDoorScaleRecord.Scale */
}

/* KeyRecord: 132 bytes on the N64 */
void geSwap_KeyRecord(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* KeyRecord.<anon>.<anon>.extrascale */
    geSwap16((unsigned char *)p + 4);   /* KeyRecord.<anon>.obj */
    geSwap16((unsigned char *)p + 6);   /* KeyRecord.<anon>.pad */
    geSwap32((unsigned char *)p + 8);   /* KeyRecord.<anon>.flags */
    geSwap32((unsigned char *)p + 12);   /* KeyRecord.<anon>.flags2 */
    geSwap32((unsigned char *)p + 16);   /* KeyRecord.<anon>.prop */
    geSwap32((unsigned char *)p + 20);   /* KeyRecord.<anon>.model */
    geSwapUnion_KeyRecord__anon__mtx_at24((unsigned char *)p + 24);  /* union: KeyRecord.<anon>.mtx -- see the hook */
    /* union KeyRecord.<anon>.runtime_pos.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 88);   /* KeyRecord.<anon>.runtime_pos.<anon>.x */
    geSwap32((unsigned char *)p + 92);   /* KeyRecord.<anon>.runtime_pos.<anon>.y */
    geSwap32((unsigned char *)p + 96);   /* KeyRecord.<anon>.runtime_pos.<anon>.z */
    /* union KeyRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 100);   /* KeyRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 104);   /* KeyRecord.<anon>.ptr_allocated_collisiondata_block */
    /* union KeyRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 108);   /* KeyRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 112);   /* KeyRecord.<anon>.maxdamage */
    geSwap32((unsigned char *)p + 116);   /* KeyRecord.<anon>.damage */
    geSwapUnion_KeyRecord__anon__shadecol__anon__at120((unsigned char *)p + 120);  /* union: KeyRecord.<anon>.shadecol.<anon> -- see the hook */
    geSwapUnion_KeyRecord__anon__nextcol__anon__at124((unsigned char *)p + 124);  /* union: KeyRecord.<anon>.nextcol.<anon> -- see the hook */
    geSwapUnion_KeyRecord__anon__at128((unsigned char *)p + 128);  /* union: KeyRecord.<anon> -- see the hook */
}

/* TintedGlassRecord: 148 bytes on the N64 */
void geSwap_TintedGlassRecord(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* TintedGlassRecord.<anon>.<anon>.extrascale */
    geSwap16((unsigned char *)p + 4);   /* TintedGlassRecord.<anon>.obj */
    geSwap16((unsigned char *)p + 6);   /* TintedGlassRecord.<anon>.pad */
    geSwap32((unsigned char *)p + 8);   /* TintedGlassRecord.<anon>.flags */
    geSwap32((unsigned char *)p + 12);   /* TintedGlassRecord.<anon>.flags2 */
    geSwap32((unsigned char *)p + 16);   /* TintedGlassRecord.<anon>.prop */
    geSwap32((unsigned char *)p + 20);   /* TintedGlassRecord.<anon>.model */
    geSwapUnion_TintedGlassRecord__anon__mtx_at24((unsigned char *)p + 24);  /* union: TintedGlassRecord.<anon>.mtx -- see the hook */
    /* union TintedGlassRecord.<anon>.runtime_pos.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 88);   /* TintedGlassRecord.<anon>.runtime_pos.<anon>.x */
    geSwap32((unsigned char *)p + 92);   /* TintedGlassRecord.<anon>.runtime_pos.<anon>.y */
    geSwap32((unsigned char *)p + 96);   /* TintedGlassRecord.<anon>.runtime_pos.<anon>.z */
    /* union TintedGlassRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 100);   /* TintedGlassRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 104);   /* TintedGlassRecord.<anon>.ptr_allocated_collisiondata_block */
    /* union TintedGlassRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 108);   /* TintedGlassRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 112);   /* TintedGlassRecord.<anon>.maxdamage */
    geSwap32((unsigned char *)p + 116);   /* TintedGlassRecord.<anon>.damage */
    geSwapUnion_TintedGlassRecord__anon__shadecol__anon__at120((unsigned char *)p + 120);  /* union: TintedGlassRecord.<anon>.shadecol.<anon> -- see the hook */
    geSwapUnion_TintedGlassRecord__anon__nextcol__anon__at124((unsigned char *)p + 124);  /* union: TintedGlassRecord.<anon>.nextcol.<anon> -- see the hook */
    geSwap32((unsigned char *)p + 128);   /* TintedGlassRecord.TintDist */
    geSwap32((unsigned char *)p + 132);   /* TintedGlassRecord.CullDist */
    geSwap32((unsigned char *)p + 136);   /* TintedGlassRecord.calculatedopacity */
    geSwap32((unsigned char *)p + 140);   /* TintedGlassRecord.portalnum */
    geSwap32((unsigned char *)p + 144);   /* TintedGlassRecord.unk90 */
}

/* CCTVRecord: 252 bytes on the N64 */
void geSwap_CCTVRecord(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* CCTVRecord.<anon>.<anon>.extrascale */
    geSwap16((unsigned char *)p + 4);   /* CCTVRecord.<anon>.obj */
    geSwap16((unsigned char *)p + 6);   /* CCTVRecord.<anon>.pad */
    geSwap32((unsigned char *)p + 8);   /* CCTVRecord.<anon>.flags */
    geSwap32((unsigned char *)p + 12);   /* CCTVRecord.<anon>.flags2 */
    geSwap32((unsigned char *)p + 16);   /* CCTVRecord.<anon>.prop */
    geSwap32((unsigned char *)p + 20);   /* CCTVRecord.<anon>.model */
    geSwapUnion_CCTVRecord__anon__mtx_at24((unsigned char *)p + 24);  /* union: CCTVRecord.<anon>.mtx -- see the hook */
    /* union CCTVRecord.<anon>.runtime_pos.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 88);   /* CCTVRecord.<anon>.runtime_pos.<anon>.x */
    geSwap32((unsigned char *)p + 92);   /* CCTVRecord.<anon>.runtime_pos.<anon>.y */
    geSwap32((unsigned char *)p + 96);   /* CCTVRecord.<anon>.runtime_pos.<anon>.z */
    /* union CCTVRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 100);   /* CCTVRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 104);   /* CCTVRecord.<anon>.ptr_allocated_collisiondata_block */
    /* union CCTVRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 108);   /* CCTVRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 112);   /* CCTVRecord.<anon>.maxdamage */
    geSwap32((unsigned char *)p + 116);   /* CCTVRecord.<anon>.damage */
    geSwapUnion_CCTVRecord__anon__shadecol__anon__at120((unsigned char *)p + 120);  /* union: CCTVRecord.<anon>.shadecol.<anon> -- see the hook */
    geSwapUnion_CCTVRecord__anon__nextcol__anon__at124((unsigned char *)p + 124);  /* union: CCTVRecord.<anon>.nextcol.<anon> -- see the hook */
    geSwap32((unsigned char *)p + 128);   /* CCTVRecord.lookpad */
    geSwapUnion_CCTVRecord_unk84_at132((unsigned char *)p + 132);  /* union: CCTVRecord.unk84 -- see the hook */
    geSwap32((unsigned char *)p + 196);   /* CCTVRecord.unkC4 */
    geSwap32((unsigned char *)p + 200);   /* CCTVRecord.unkC8 */
    geSwap32((unsigned char *)p + 204);   /* CCTVRecord.unkCC */
    geSwap32((unsigned char *)p + 208);   /* CCTVRecord.unkD0 */
    geSwap32((unsigned char *)p + 212);   /* CCTVRecord.unkD4 */
    geSwap32((unsigned char *)p + 216);   /* CCTVRecord.unkD8 */
    geSwap32((unsigned char *)p + 220);   /* CCTVRecord.unkDC */
    geSwap32((unsigned char *)p + 224);   /* CCTVRecord.timer */
    geSwap32((unsigned char *)p + 228);   /* CCTVRecord.convert_to_f32 */
    geSwap32((unsigned char *)p + 232);   /* CCTVRecord.unkE8 */
    geSwap32((unsigned char *)p + 236);   /* CCTVRecord.unkEC */
    geSwap32((unsigned char *)p + 240);   /* CCTVRecord.unkF0 */
    geSwap32((unsigned char *)p + 244);   /* CCTVRecord.unkF4 */
    geSwap32((unsigned char *)p + 248);   /* CCTVRecord.unkF8 */
}

/* WeaponObjRecord: 136 bytes on the N64 */
void geSwap_WeaponObjRecord(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* WeaponObjRecord.<anon>.<anon>.extrascale */
    geSwap16((unsigned char *)p + 4);   /* WeaponObjRecord.<anon>.obj */
    geSwap16((unsigned char *)p + 6);   /* WeaponObjRecord.<anon>.pad */
    geSwap32((unsigned char *)p + 8);   /* WeaponObjRecord.<anon>.flags */
    geSwap32((unsigned char *)p + 12);   /* WeaponObjRecord.<anon>.flags2 */
    geSwap32((unsigned char *)p + 16);   /* WeaponObjRecord.<anon>.prop */
    geSwap32((unsigned char *)p + 20);   /* WeaponObjRecord.<anon>.model */
    geSwapUnion_WeaponObjRecord__anon__mtx_at24((unsigned char *)p + 24);  /* union: WeaponObjRecord.<anon>.mtx -- see the hook */
    /* union WeaponObjRecord.<anon>.runtime_pos.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 88);   /* WeaponObjRecord.<anon>.runtime_pos.<anon>.x */
    geSwap32((unsigned char *)p + 92);   /* WeaponObjRecord.<anon>.runtime_pos.<anon>.y */
    geSwap32((unsigned char *)p + 96);   /* WeaponObjRecord.<anon>.runtime_pos.<anon>.z */
    /* union WeaponObjRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 100);   /* WeaponObjRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 104);   /* WeaponObjRecord.<anon>.ptr_allocated_collisiondata_block */
    /* union WeaponObjRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 108);   /* WeaponObjRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 112);   /* WeaponObjRecord.<anon>.maxdamage */
    geSwap32((unsigned char *)p + 116);   /* WeaponObjRecord.<anon>.damage */
    geSwapUnion_WeaponObjRecord__anon__shadecol__anon__at120((unsigned char *)p + 120);  /* union: WeaponObjRecord.<anon>.shadecol.<anon> -- see the hook */
    geSwapUnion_WeaponObjRecord__anon__nextcol__anon__at124((unsigned char *)p + 124);  /* union: WeaponObjRecord.<anon>.nextcol.<anon> -- see the hook */
    geSwap16((unsigned char *)p + 130);   /* WeaponObjRecord.timer */
    geSwap32((unsigned char *)p + 132);   /* WeaponObjRecord.dualweapon */
}

/* MonitorObjRecord: 256 bytes on the N64 */
void geSwap_MonitorObjRecord(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* MonitorObjRecord.<anon>.<anon>.extrascale */
    geSwap16((unsigned char *)p + 4);   /* MonitorObjRecord.<anon>.obj */
    geSwap16((unsigned char *)p + 6);   /* MonitorObjRecord.<anon>.pad */
    geSwap32((unsigned char *)p + 8);   /* MonitorObjRecord.<anon>.flags */
    geSwap32((unsigned char *)p + 12);   /* MonitorObjRecord.<anon>.flags2 */
    geSwap32((unsigned char *)p + 16);   /* MonitorObjRecord.<anon>.prop */
    geSwap32((unsigned char *)p + 20);   /* MonitorObjRecord.<anon>.model */
    geSwapUnion_MonitorObjRecord__anon__mtx_at24((unsigned char *)p + 24);  /* union: MonitorObjRecord.<anon>.mtx -- see the hook */
    /* union MonitorObjRecord.<anon>.runtime_pos.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 88);   /* MonitorObjRecord.<anon>.runtime_pos.<anon>.x */
    geSwap32((unsigned char *)p + 92);   /* MonitorObjRecord.<anon>.runtime_pos.<anon>.y */
    geSwap32((unsigned char *)p + 96);   /* MonitorObjRecord.<anon>.runtime_pos.<anon>.z */
    /* union MonitorObjRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 100);   /* MonitorObjRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 104);   /* MonitorObjRecord.<anon>.ptr_allocated_collisiondata_block */
    /* union MonitorObjRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 108);   /* MonitorObjRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 112);   /* MonitorObjRecord.<anon>.maxdamage */
    geSwap32((unsigned char *)p + 116);   /* MonitorObjRecord.<anon>.damage */
    geSwapUnion_MonitorObjRecord__anon__shadecol__anon__at120((unsigned char *)p + 120);  /* union: MonitorObjRecord.<anon>.shadecol.<anon> -- see the hook */
    geSwapUnion_MonitorObjRecord__anon__nextcol__anon__at124((unsigned char *)p + 124);  /* union: MonitorObjRecord.<anon>.nextcol.<anon> -- see the hook */
    geSwap32((unsigned char *)p + 128);   /* MonitorObjRecord.Monitor.cmdlist */
    geSwap16((unsigned char *)p + 132);   /* MonitorObjRecord.Monitor.offset */
    geSwap16((unsigned char *)p + 134);   /* MonitorObjRecord.Monitor.pause60 */
    geSwap32((unsigned char *)p + 136);   /* MonitorObjRecord.Monitor.tconfig */
    geSwap32((unsigned char *)p + 140);   /* MonitorObjRecord.Monitor.rot */
    geSwap32((unsigned char *)p + 144);   /* MonitorObjRecord.Monitor.xscale */
    geSwap32((unsigned char *)p + 148);   /* MonitorObjRecord.Monitor.xscalefrac */
    geSwap32((unsigned char *)p + 152);   /* MonitorObjRecord.Monitor.xscaleinc */
    geSwap32((unsigned char *)p + 156);   /* MonitorObjRecord.Monitor.xscaleold */
    geSwap32((unsigned char *)p + 160);   /* MonitorObjRecord.Monitor.xscalenew */
    geSwap32((unsigned char *)p + 164);   /* MonitorObjRecord.Monitor.yscale */
    geSwap32((unsigned char *)p + 168);   /* MonitorObjRecord.Monitor.yscalefrac */
    geSwap32((unsigned char *)p + 172);   /* MonitorObjRecord.Monitor.yscaleinc */
    geSwap32((unsigned char *)p + 176);   /* MonitorObjRecord.Monitor.yscaleold */
    geSwap32((unsigned char *)p + 180);   /* MonitorObjRecord.Monitor.yscalenew */
    geSwap32((unsigned char *)p + 184);   /* MonitorObjRecord.Monitor.xmid */
    geSwap32((unsigned char *)p + 188);   /* MonitorObjRecord.Monitor.xmidfrac */
    geSwap32((unsigned char *)p + 192);   /* MonitorObjRecord.Monitor.xmidinc */
    geSwap32((unsigned char *)p + 196);   /* MonitorObjRecord.Monitor.xmidold */
    geSwap32((unsigned char *)p + 200);   /* MonitorObjRecord.Monitor.xmidnew */
    geSwap32((unsigned char *)p + 204);   /* MonitorObjRecord.Monitor.ymid */
    geSwap32((unsigned char *)p + 208);   /* MonitorObjRecord.Monitor.ymidfrac */
    geSwap32((unsigned char *)p + 212);   /* MonitorObjRecord.Monitor.ymidinc */
    geSwap32((unsigned char *)p + 216);   /* MonitorObjRecord.Monitor.ymidold */
    geSwap32((unsigned char *)p + 220);   /* MonitorObjRecord.Monitor.ymidnew */
    geSwap32((unsigned char *)p + 236);   /* MonitorObjRecord.Monitor.colfrac */
    geSwap32((unsigned char *)p + 240);   /* MonitorObjRecord.Monitor.colinc */
    geSwap32((unsigned char *)p + 244);   /* MonitorObjRecord.OwnerOffset */
    geSwap32((unsigned char *)p + 248);   /* MonitorObjRecord.OwnerPart */
    geSwap32((unsigned char *)p + 252);   /* MonitorObjRecord.ImageNum */
}

/* MultiMonitorObjRecord: 596 bytes on the N64 */
void geSwap_MultiMonitorObjRecord(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* MultiMonitorObjRecord.<anon>.<anon>.extrascale */
    geSwap16((unsigned char *)p + 4);   /* MultiMonitorObjRecord.<anon>.obj */
    geSwap16((unsigned char *)p + 6);   /* MultiMonitorObjRecord.<anon>.pad */
    geSwap32((unsigned char *)p + 8);   /* MultiMonitorObjRecord.<anon>.flags */
    geSwap32((unsigned char *)p + 12);   /* MultiMonitorObjRecord.<anon>.flags2 */
    geSwap32((unsigned char *)p + 16);   /* MultiMonitorObjRecord.<anon>.prop */
    geSwap32((unsigned char *)p + 20);   /* MultiMonitorObjRecord.<anon>.model */
    geSwapUnion_MultiMonitorObjRecord__anon__mtx_at24((unsigned char *)p + 24);  /* union: MultiMonitorObjRecord.<anon>.mtx -- see the hook */
    /* union MultiMonitorObjRecord.<anon>.runtime_pos.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 88);   /* MultiMonitorObjRecord.<anon>.runtime_pos.<anon>.x */
    geSwap32((unsigned char *)p + 92);   /* MultiMonitorObjRecord.<anon>.runtime_pos.<anon>.y */
    geSwap32((unsigned char *)p + 96);   /* MultiMonitorObjRecord.<anon>.runtime_pos.<anon>.z */
    /* union MultiMonitorObjRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 100);   /* MultiMonitorObjRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 104);   /* MultiMonitorObjRecord.<anon>.ptr_allocated_collisiondata_block */
    /* union MultiMonitorObjRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 108);   /* MultiMonitorObjRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 112);   /* MultiMonitorObjRecord.<anon>.maxdamage */
    geSwap32((unsigned char *)p + 116);   /* MultiMonitorObjRecord.<anon>.damage */
    geSwapUnion_MultiMonitorObjRecord__anon__shadecol__anon__at120((unsigned char *)p + 120);  /* union: MultiMonitorObjRecord.<anon>.shadecol.<anon> -- see the hook */
    geSwapUnion_MultiMonitorObjRecord__anon__nextcol__anon__at124((unsigned char *)p + 124);  /* union: MultiMonitorObjRecord.<anon>.nextcol.<anon> -- see the hook */
    geSwap32((unsigned char *)p + 128);   /* MultiMonitorObjRecord.Monitor[0].cmdlist */
    geSwap16((unsigned char *)p + 132);   /* MultiMonitorObjRecord.Monitor[0].offset */
    geSwap16((unsigned char *)p + 134);   /* MultiMonitorObjRecord.Monitor[0].pause60 */
    geSwap32((unsigned char *)p + 136);   /* MultiMonitorObjRecord.Monitor[0].tconfig */
    geSwap32((unsigned char *)p + 140);   /* MultiMonitorObjRecord.Monitor[0].rot */
    geSwap32((unsigned char *)p + 144);   /* MultiMonitorObjRecord.Monitor[0].xscale */
    geSwap32((unsigned char *)p + 148);   /* MultiMonitorObjRecord.Monitor[0].xscalefrac */
    geSwap32((unsigned char *)p + 152);   /* MultiMonitorObjRecord.Monitor[0].xscaleinc */
    geSwap32((unsigned char *)p + 156);   /* MultiMonitorObjRecord.Monitor[0].xscaleold */
    geSwap32((unsigned char *)p + 160);   /* MultiMonitorObjRecord.Monitor[0].xscalenew */
    geSwap32((unsigned char *)p + 164);   /* MultiMonitorObjRecord.Monitor[0].yscale */
    geSwap32((unsigned char *)p + 168);   /* MultiMonitorObjRecord.Monitor[0].yscalefrac */
    geSwap32((unsigned char *)p + 172);   /* MultiMonitorObjRecord.Monitor[0].yscaleinc */
    geSwap32((unsigned char *)p + 176);   /* MultiMonitorObjRecord.Monitor[0].yscaleold */
    geSwap32((unsigned char *)p + 180);   /* MultiMonitorObjRecord.Monitor[0].yscalenew */
    geSwap32((unsigned char *)p + 184);   /* MultiMonitorObjRecord.Monitor[0].xmid */
    geSwap32((unsigned char *)p + 188);   /* MultiMonitorObjRecord.Monitor[0].xmidfrac */
    geSwap32((unsigned char *)p + 192);   /* MultiMonitorObjRecord.Monitor[0].xmidinc */
    geSwap32((unsigned char *)p + 196);   /* MultiMonitorObjRecord.Monitor[0].xmidold */
    geSwap32((unsigned char *)p + 200);   /* MultiMonitorObjRecord.Monitor[0].xmidnew */
    geSwap32((unsigned char *)p + 204);   /* MultiMonitorObjRecord.Monitor[0].ymid */
    geSwap32((unsigned char *)p + 208);   /* MultiMonitorObjRecord.Monitor[0].ymidfrac */
    geSwap32((unsigned char *)p + 212);   /* MultiMonitorObjRecord.Monitor[0].ymidinc */
    geSwap32((unsigned char *)p + 216);   /* MultiMonitorObjRecord.Monitor[0].ymidold */
    geSwap32((unsigned char *)p + 220);   /* MultiMonitorObjRecord.Monitor[0].ymidnew */
    geSwap32((unsigned char *)p + 236);   /* MultiMonitorObjRecord.Monitor[0].colfrac */
    geSwap32((unsigned char *)p + 240);   /* MultiMonitorObjRecord.Monitor[0].colinc */
    geSwap32((unsigned char *)p + 244);   /* MultiMonitorObjRecord.Monitor[1].cmdlist */
    geSwap16((unsigned char *)p + 248);   /* MultiMonitorObjRecord.Monitor[1].offset */
    geSwap16((unsigned char *)p + 250);   /* MultiMonitorObjRecord.Monitor[1].pause60 */
    geSwap32((unsigned char *)p + 252);   /* MultiMonitorObjRecord.Monitor[1].tconfig */
    geSwap32((unsigned char *)p + 256);   /* MultiMonitorObjRecord.Monitor[1].rot */
    geSwap32((unsigned char *)p + 260);   /* MultiMonitorObjRecord.Monitor[1].xscale */
    geSwap32((unsigned char *)p + 264);   /* MultiMonitorObjRecord.Monitor[1].xscalefrac */
    geSwap32((unsigned char *)p + 268);   /* MultiMonitorObjRecord.Monitor[1].xscaleinc */
    geSwap32((unsigned char *)p + 272);   /* MultiMonitorObjRecord.Monitor[1].xscaleold */
    geSwap32((unsigned char *)p + 276);   /* MultiMonitorObjRecord.Monitor[1].xscalenew */
    geSwap32((unsigned char *)p + 280);   /* MultiMonitorObjRecord.Monitor[1].yscale */
    geSwap32((unsigned char *)p + 284);   /* MultiMonitorObjRecord.Monitor[1].yscalefrac */
    geSwap32((unsigned char *)p + 288);   /* MultiMonitorObjRecord.Monitor[1].yscaleinc */
    geSwap32((unsigned char *)p + 292);   /* MultiMonitorObjRecord.Monitor[1].yscaleold */
    geSwap32((unsigned char *)p + 296);   /* MultiMonitorObjRecord.Monitor[1].yscalenew */
    geSwap32((unsigned char *)p + 300);   /* MultiMonitorObjRecord.Monitor[1].xmid */
    geSwap32((unsigned char *)p + 304);   /* MultiMonitorObjRecord.Monitor[1].xmidfrac */
    geSwap32((unsigned char *)p + 308);   /* MultiMonitorObjRecord.Monitor[1].xmidinc */
    geSwap32((unsigned char *)p + 312);   /* MultiMonitorObjRecord.Monitor[1].xmidold */
    geSwap32((unsigned char *)p + 316);   /* MultiMonitorObjRecord.Monitor[1].xmidnew */
    geSwap32((unsigned char *)p + 320);   /* MultiMonitorObjRecord.Monitor[1].ymid */
    geSwap32((unsigned char *)p + 324);   /* MultiMonitorObjRecord.Monitor[1].ymidfrac */
    geSwap32((unsigned char *)p + 328);   /* MultiMonitorObjRecord.Monitor[1].ymidinc */
    geSwap32((unsigned char *)p + 332);   /* MultiMonitorObjRecord.Monitor[1].ymidold */
    geSwap32((unsigned char *)p + 336);   /* MultiMonitorObjRecord.Monitor[1].ymidnew */
    geSwap32((unsigned char *)p + 352);   /* MultiMonitorObjRecord.Monitor[1].colfrac */
    geSwap32((unsigned char *)p + 356);   /* MultiMonitorObjRecord.Monitor[1].colinc */
    geSwap32((unsigned char *)p + 360);   /* MultiMonitorObjRecord.Monitor[2].cmdlist */
    geSwap16((unsigned char *)p + 364);   /* MultiMonitorObjRecord.Monitor[2].offset */
    geSwap16((unsigned char *)p + 366);   /* MultiMonitorObjRecord.Monitor[2].pause60 */
    geSwap32((unsigned char *)p + 368);   /* MultiMonitorObjRecord.Monitor[2].tconfig */
    geSwap32((unsigned char *)p + 372);   /* MultiMonitorObjRecord.Monitor[2].rot */
    geSwap32((unsigned char *)p + 376);   /* MultiMonitorObjRecord.Monitor[2].xscale */
    geSwap32((unsigned char *)p + 380);   /* MultiMonitorObjRecord.Monitor[2].xscalefrac */
    geSwap32((unsigned char *)p + 384);   /* MultiMonitorObjRecord.Monitor[2].xscaleinc */
    geSwap32((unsigned char *)p + 388);   /* MultiMonitorObjRecord.Monitor[2].xscaleold */
    geSwap32((unsigned char *)p + 392);   /* MultiMonitorObjRecord.Monitor[2].xscalenew */
    geSwap32((unsigned char *)p + 396);   /* MultiMonitorObjRecord.Monitor[2].yscale */
    geSwap32((unsigned char *)p + 400);   /* MultiMonitorObjRecord.Monitor[2].yscalefrac */
    geSwap32((unsigned char *)p + 404);   /* MultiMonitorObjRecord.Monitor[2].yscaleinc */
    geSwap32((unsigned char *)p + 408);   /* MultiMonitorObjRecord.Monitor[2].yscaleold */
    geSwap32((unsigned char *)p + 412);   /* MultiMonitorObjRecord.Monitor[2].yscalenew */
    geSwap32((unsigned char *)p + 416);   /* MultiMonitorObjRecord.Monitor[2].xmid */
    geSwap32((unsigned char *)p + 420);   /* MultiMonitorObjRecord.Monitor[2].xmidfrac */
    geSwap32((unsigned char *)p + 424);   /* MultiMonitorObjRecord.Monitor[2].xmidinc */
    geSwap32((unsigned char *)p + 428);   /* MultiMonitorObjRecord.Monitor[2].xmidold */
    geSwap32((unsigned char *)p + 432);   /* MultiMonitorObjRecord.Monitor[2].xmidnew */
    geSwap32((unsigned char *)p + 436);   /* MultiMonitorObjRecord.Monitor[2].ymid */
    geSwap32((unsigned char *)p + 440);   /* MultiMonitorObjRecord.Monitor[2].ymidfrac */
    geSwap32((unsigned char *)p + 444);   /* MultiMonitorObjRecord.Monitor[2].ymidinc */
    geSwap32((unsigned char *)p + 448);   /* MultiMonitorObjRecord.Monitor[2].ymidold */
    geSwap32((unsigned char *)p + 452);   /* MultiMonitorObjRecord.Monitor[2].ymidnew */
    geSwap32((unsigned char *)p + 468);   /* MultiMonitorObjRecord.Monitor[2].colfrac */
    geSwap32((unsigned char *)p + 472);   /* MultiMonitorObjRecord.Monitor[2].colinc */
    geSwap32((unsigned char *)p + 476);   /* MultiMonitorObjRecord.Monitor[3].cmdlist */
    geSwap16((unsigned char *)p + 480);   /* MultiMonitorObjRecord.Monitor[3].offset */
    geSwap16((unsigned char *)p + 482);   /* MultiMonitorObjRecord.Monitor[3].pause60 */
    geSwap32((unsigned char *)p + 484);   /* MultiMonitorObjRecord.Monitor[3].tconfig */
    geSwap32((unsigned char *)p + 488);   /* MultiMonitorObjRecord.Monitor[3].rot */
    geSwap32((unsigned char *)p + 492);   /* MultiMonitorObjRecord.Monitor[3].xscale */
    geSwap32((unsigned char *)p + 496);   /* MultiMonitorObjRecord.Monitor[3].xscalefrac */
    geSwap32((unsigned char *)p + 500);   /* MultiMonitorObjRecord.Monitor[3].xscaleinc */
    geSwap32((unsigned char *)p + 504);   /* MultiMonitorObjRecord.Monitor[3].xscaleold */
    geSwap32((unsigned char *)p + 508);   /* MultiMonitorObjRecord.Monitor[3].xscalenew */
    geSwap32((unsigned char *)p + 512);   /* MultiMonitorObjRecord.Monitor[3].yscale */
    geSwap32((unsigned char *)p + 516);   /* MultiMonitorObjRecord.Monitor[3].yscalefrac */
    geSwap32((unsigned char *)p + 520);   /* MultiMonitorObjRecord.Monitor[3].yscaleinc */
    geSwap32((unsigned char *)p + 524);   /* MultiMonitorObjRecord.Monitor[3].yscaleold */
    geSwap32((unsigned char *)p + 528);   /* MultiMonitorObjRecord.Monitor[3].yscalenew */
    geSwap32((unsigned char *)p + 532);   /* MultiMonitorObjRecord.Monitor[3].xmid */
    geSwap32((unsigned char *)p + 536);   /* MultiMonitorObjRecord.Monitor[3].xmidfrac */
    geSwap32((unsigned char *)p + 540);   /* MultiMonitorObjRecord.Monitor[3].xmidinc */
    geSwap32((unsigned char *)p + 544);   /* MultiMonitorObjRecord.Monitor[3].xmidold */
    geSwap32((unsigned char *)p + 548);   /* MultiMonitorObjRecord.Monitor[3].xmidnew */
    geSwap32((unsigned char *)p + 552);   /* MultiMonitorObjRecord.Monitor[3].ymid */
    geSwap32((unsigned char *)p + 556);   /* MultiMonitorObjRecord.Monitor[3].ymidfrac */
    geSwap32((unsigned char *)p + 560);   /* MultiMonitorObjRecord.Monitor[3].ymidinc */
    geSwap32((unsigned char *)p + 564);   /* MultiMonitorObjRecord.Monitor[3].ymidold */
    geSwap32((unsigned char *)p + 568);   /* MultiMonitorObjRecord.Monitor[3].ymidnew */
    geSwap32((unsigned char *)p + 584);   /* MultiMonitorObjRecord.Monitor[3].colfrac */
    geSwap32((unsigned char *)p + 588);   /* MultiMonitorObjRecord.Monitor[3].colinc */
}

/* AutogunRecord: 216 bytes on the N64 */
void geSwap_AutogunRecord(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* AutogunRecord.<anon>.<anon>.extrascale */
    geSwap16((unsigned char *)p + 4);   /* AutogunRecord.<anon>.obj */
    geSwap16((unsigned char *)p + 6);   /* AutogunRecord.<anon>.pad */
    geSwap32((unsigned char *)p + 8);   /* AutogunRecord.<anon>.flags */
    geSwap32((unsigned char *)p + 12);   /* AutogunRecord.<anon>.flags2 */
    geSwap32((unsigned char *)p + 16);   /* AutogunRecord.<anon>.prop */
    geSwap32((unsigned char *)p + 20);   /* AutogunRecord.<anon>.model */
    geSwapUnion_AutogunRecord__anon__mtx_at24((unsigned char *)p + 24);  /* union: AutogunRecord.<anon>.mtx -- see the hook */
    /* union AutogunRecord.<anon>.runtime_pos.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 88);   /* AutogunRecord.<anon>.runtime_pos.<anon>.x */
    geSwap32((unsigned char *)p + 92);   /* AutogunRecord.<anon>.runtime_pos.<anon>.y */
    geSwap32((unsigned char *)p + 96);   /* AutogunRecord.<anon>.runtime_pos.<anon>.z */
    /* union AutogunRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 100);   /* AutogunRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 104);   /* AutogunRecord.<anon>.ptr_allocated_collisiondata_block */
    /* union AutogunRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 108);   /* AutogunRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 112);   /* AutogunRecord.<anon>.maxdamage */
    geSwap32((unsigned char *)p + 116);   /* AutogunRecord.<anon>.damage */
    geSwapUnion_AutogunRecord__anon__shadecol__anon__at120((unsigned char *)p + 120);  /* union: AutogunRecord.<anon>.shadecol.<anon> -- see the hook */
    geSwapUnion_AutogunRecord__anon__nextcol__anon__at124((unsigned char *)p + 124);  /* union: AutogunRecord.<anon>.nextcol.<anon> -- see the hook */
    geSwap32((unsigned char *)p + 128);   /* AutogunRecord.padID */
    geSwap32((unsigned char *)p + 132);   /* AutogunRecord.rot_related */
    geSwap32((unsigned char *)p + 136);   /* AutogunRecord.unk88 */
    geSwap32((unsigned char *)p + 140);   /* AutogunRecord.unk8C */
    geSwap32((unsigned char *)p + 144);   /* AutogunRecord.unk90 */
    geSwap32((unsigned char *)p + 148);   /* AutogunRecord.unk94 */
    geSwap32((unsigned char *)p + 152);   /* AutogunRecord.unk98 */
    geSwap32((unsigned char *)p + 156);   /* AutogunRecord.unk9C */
    geSwap32((unsigned char *)p + 160);   /* AutogunRecord.unkA0 */
    geSwap32((unsigned char *)p + 164);   /* AutogunRecord.speed */
    geSwap32((unsigned char *)p + 168);   /* AutogunRecord.aimdist */
    geSwap32((unsigned char *)p + 172);   /* AutogunRecord.unkAC */
    geSwap32((unsigned char *)p + 176);   /* AutogunRecord.unkB0 */
    geSwap32((unsigned char *)p + 180);   /* AutogunRecord.unkB4 */
    geSwap32((unsigned char *)p + 184);   /* AutogunRecord.unkB8 */
    geSwap32((unsigned char *)p + 188);   /* AutogunRecord.unkBC */
    geSwap32((unsigned char *)p + 192);   /* AutogunRecord.unkC0 */
    geSwap32((unsigned char *)p + 196);   /* AutogunRecord.unkC4 */
    geSwap32((unsigned char *)p + 200);   /* AutogunRecord.unkC8 */
    geSwap32((unsigned char *)p + 204);   /* AutogunRecord.beam */
    geSwap32((unsigned char *)p + 208);   /* AutogunRecord.is_active */
    geSwap32((unsigned char *)p + 212);   /* AutogunRecord.unkD4 */
}

/* LinkRecord: 16 bytes on the N64 */
void geSwap_LinkRecord(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* LinkRecord.<anon>.extrascale */
    /* union LinkRecord.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 4);   /* LinkRecord.<anon> */
    /* union LinkRecord.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 8);   /* LinkRecord.<anon> */
    geSwap32((unsigned char *)p + 12);   /* LinkRecord.next */
}

/* GuardAttributeRecord: 12 bytes on the N64 */
void geSwap_GuardAttributeRecord(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* GuardAttributeRecord.<anon>.extrascale */
    geSwap32((unsigned char *)p + 4);   /* GuardAttributeRecord.chrnum */
    geSwap16((unsigned char *)p + 8);   /* GuardAttributeRecord.unk8 */
}

/* MultiAmmoCrateRecord: 180 bytes on the N64 */
void geSwap_MultiAmmoCrateRecord(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* MultiAmmoCrateRecord.<anon>.<anon>.extrascale */
    geSwap16((unsigned char *)p + 4);   /* MultiAmmoCrateRecord.<anon>.obj */
    geSwap16((unsigned char *)p + 6);   /* MultiAmmoCrateRecord.<anon>.pad */
    geSwap32((unsigned char *)p + 8);   /* MultiAmmoCrateRecord.<anon>.flags */
    geSwap32((unsigned char *)p + 12);   /* MultiAmmoCrateRecord.<anon>.flags2 */
    geSwap32((unsigned char *)p + 16);   /* MultiAmmoCrateRecord.<anon>.prop */
    geSwap32((unsigned char *)p + 20);   /* MultiAmmoCrateRecord.<anon>.model */
    geSwapUnion_MultiAmmoCrateRecord__anon__mtx_at24((unsigned char *)p + 24);  /* union: MultiAmmoCrateRecord.<anon>.mtx -- see the hook */
    /* union MultiAmmoCrateRecord.<anon>.runtime_pos.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 88);   /* MultiAmmoCrateRecord.<anon>.runtime_pos.<anon>.x */
    geSwap32((unsigned char *)p + 92);   /* MultiAmmoCrateRecord.<anon>.runtime_pos.<anon>.y */
    geSwap32((unsigned char *)p + 96);   /* MultiAmmoCrateRecord.<anon>.runtime_pos.<anon>.z */
    /* union MultiAmmoCrateRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 100);   /* MultiAmmoCrateRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 104);   /* MultiAmmoCrateRecord.<anon>.ptr_allocated_collisiondata_block */
    /* union MultiAmmoCrateRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 108);   /* MultiAmmoCrateRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 112);   /* MultiAmmoCrateRecord.<anon>.maxdamage */
    geSwap32((unsigned char *)p + 116);   /* MultiAmmoCrateRecord.<anon>.damage */
    geSwapUnion_MultiAmmoCrateRecord__anon__shadecol__anon__at120((unsigned char *)p + 120);  /* union: MultiAmmoCrateRecord.<anon>.shadecol.<anon> -- see the hook */
    geSwapUnion_MultiAmmoCrateRecord__anon__nextcol__anon__at124((unsigned char *)p + 124);  /* union: MultiAmmoCrateRecord.<anon>.nextcol.<anon> -- see the hook */
    geSwap16((unsigned char *)p + 128);   /* MultiAmmoCrateRecord.slots[0].modelnum */
    geSwap16((unsigned char *)p + 130);   /* MultiAmmoCrateRecord.slots[0].quantity */
    geSwap16((unsigned char *)p + 132);   /* MultiAmmoCrateRecord.slots[1].modelnum */
    geSwap16((unsigned char *)p + 134);   /* MultiAmmoCrateRecord.slots[1].quantity */
    geSwap16((unsigned char *)p + 136);   /* MultiAmmoCrateRecord.slots[2].modelnum */
    geSwap16((unsigned char *)p + 138);   /* MultiAmmoCrateRecord.slots[2].quantity */
    geSwap16((unsigned char *)p + 140);   /* MultiAmmoCrateRecord.slots[3].modelnum */
    geSwap16((unsigned char *)p + 142);   /* MultiAmmoCrateRecord.slots[3].quantity */
    geSwap16((unsigned char *)p + 144);   /* MultiAmmoCrateRecord.slots[4].modelnum */
    geSwap16((unsigned char *)p + 146);   /* MultiAmmoCrateRecord.slots[4].quantity */
    geSwap16((unsigned char *)p + 148);   /* MultiAmmoCrateRecord.slots[5].modelnum */
    geSwap16((unsigned char *)p + 150);   /* MultiAmmoCrateRecord.slots[5].quantity */
    geSwap16((unsigned char *)p + 152);   /* MultiAmmoCrateRecord.slots[6].modelnum */
    geSwap16((unsigned char *)p + 154);   /* MultiAmmoCrateRecord.slots[6].quantity */
    geSwap16((unsigned char *)p + 156);   /* MultiAmmoCrateRecord.slots[7].modelnum */
    geSwap16((unsigned char *)p + 158);   /* MultiAmmoCrateRecord.slots[7].quantity */
    geSwap16((unsigned char *)p + 160);   /* MultiAmmoCrateRecord.slots[8].modelnum */
    geSwap16((unsigned char *)p + 162);   /* MultiAmmoCrateRecord.slots[8].quantity */
    geSwap16((unsigned char *)p + 164);   /* MultiAmmoCrateRecord.slots[9].modelnum */
    geSwap16((unsigned char *)p + 166);   /* MultiAmmoCrateRecord.slots[9].quantity */
    geSwap16((unsigned char *)p + 168);   /* MultiAmmoCrateRecord.slots[10].modelnum */
    geSwap16((unsigned char *)p + 170);   /* MultiAmmoCrateRecord.slots[10].quantity */
    geSwap16((unsigned char *)p + 172);   /* MultiAmmoCrateRecord.slots[11].modelnum */
    geSwap16((unsigned char *)p + 174);   /* MultiAmmoCrateRecord.slots[11].quantity */
    geSwap16((unsigned char *)p + 176);   /* MultiAmmoCrateRecord.slots[12].modelnum */
    geSwap16((unsigned char *)p + 178);   /* MultiAmmoCrateRecord.slots[12].quantity */
}

/* BodyArmourRecord: 136 bytes on the N64 */
void geSwap_BodyArmourRecord(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* BodyArmourRecord.<anon>.<anon>.extrascale */
    geSwap16((unsigned char *)p + 4);   /* BodyArmourRecord.<anon>.obj */
    geSwap16((unsigned char *)p + 6);   /* BodyArmourRecord.<anon>.pad */
    geSwap32((unsigned char *)p + 8);   /* BodyArmourRecord.<anon>.flags */
    geSwap32((unsigned char *)p + 12);   /* BodyArmourRecord.<anon>.flags2 */
    geSwap32((unsigned char *)p + 16);   /* BodyArmourRecord.<anon>.prop */
    geSwap32((unsigned char *)p + 20);   /* BodyArmourRecord.<anon>.model */
    geSwapUnion_BodyArmourRecord__anon__mtx_at24((unsigned char *)p + 24);  /* union: BodyArmourRecord.<anon>.mtx -- see the hook */
    /* union BodyArmourRecord.<anon>.runtime_pos.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 88);   /* BodyArmourRecord.<anon>.runtime_pos.<anon>.x */
    geSwap32((unsigned char *)p + 92);   /* BodyArmourRecord.<anon>.runtime_pos.<anon>.y */
    geSwap32((unsigned char *)p + 96);   /* BodyArmourRecord.<anon>.runtime_pos.<anon>.z */
    /* union BodyArmourRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 100);   /* BodyArmourRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 104);   /* BodyArmourRecord.<anon>.ptr_allocated_collisiondata_block */
    /* union BodyArmourRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 108);   /* BodyArmourRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 112);   /* BodyArmourRecord.<anon>.maxdamage */
    geSwap32((unsigned char *)p + 116);   /* BodyArmourRecord.<anon>.damage */
    geSwapUnion_BodyArmourRecord__anon__shadecol__anon__at120((unsigned char *)p + 120);  /* union: BodyArmourRecord.<anon>.shadecol.<anon> -- see the hook */
    geSwapUnion_BodyArmourRecord__anon__nextcol__anon__at124((unsigned char *)p + 124);  /* union: BodyArmourRecord.<anon>.nextcol.<anon> -- see the hook */
    geSwap32((unsigned char *)p + 128);   /* BodyArmourRecord.initialamount */
    geSwap32((unsigned char *)p + 132);   /* BodyArmourRecord.amount */
}

/* TagObjectRecord: 16 bytes on the N64 */
void geSwap_TagObjectRecord(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* TagObjectRecord.<anon>.extrascale */
    geSwap16((unsigned char *)p + 4);   /* TagObjectRecord.ID */
    geSwap16((unsigned char *)p + 6);   /* TagObjectRecord.OffsetToObj */
    geSwap32((unsigned char *)p + 8);   /* TagObjectRecord.NextTag */
    geSwap32((unsigned char *)p + 12);   /* TagObjectRecord.TaggedObject */
}

/* RenameObjectRecord: 40 bytes on the N64 */
void geSwap_RenameObjectRecord(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* RenameObjectRecord.<anon>.extrascale */
    geSwap32((unsigned char *)p + 4);   /* RenameObjectRecord.TagID */
    geSwap32((unsigned char *)p + 8);   /* RenameObjectRecord.unk08 */
    geSwap32((unsigned char *)p + 12);   /* RenameObjectRecord.unk0c */
    geSwap32((unsigned char *)p + 16);   /* RenameObjectRecord.unk10 */
    geSwap32((unsigned char *)p + 20);   /* RenameObjectRecord.unk14 */
    geSwap32((unsigned char *)p + 24);   /* RenameObjectRecord.unk18 */
    geSwap32((unsigned char *)p + 28);   /* RenameObjectRecord.unk1c */
    geSwap32((unsigned char *)p + 32);   /* RenameObjectRecord.unk20 */
    geSwap32((unsigned char *)p + 36);   /* RenameObjectRecord.renobj */
}

/* LockDoorRecord: 16 bytes on the N64 */
void geSwap_LockDoorRecord(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* LockDoorRecord.<anon>.extrascale */
    /* union LockDoorRecord.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 4);   /* LockDoorRecord.<anon> */
    /* union LockDoorRecord.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 8);   /* LockDoorRecord.<anon> */
    geSwap32((unsigned char *)p + 12);   /* LockDoorRecord.next */
}

/* VehichleRecord: 176 bytes on the N64 */
void geSwap_VehichleRecord(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* VehichleRecord.<anon>.<anon>.extrascale */
    geSwap16((unsigned char *)p + 4);   /* VehichleRecord.<anon>.obj */
    geSwap16((unsigned char *)p + 6);   /* VehichleRecord.<anon>.pad */
    geSwap32((unsigned char *)p + 8);   /* VehichleRecord.<anon>.flags */
    geSwap32((unsigned char *)p + 12);   /* VehichleRecord.<anon>.flags2 */
    geSwap32((unsigned char *)p + 16);   /* VehichleRecord.<anon>.prop */
    geSwap32((unsigned char *)p + 20);   /* VehichleRecord.<anon>.model */
    geSwapUnion_VehichleRecord__anon__mtx_at24((unsigned char *)p + 24);  /* union: VehichleRecord.<anon>.mtx -- see the hook */
    /* union VehichleRecord.<anon>.runtime_pos.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 88);   /* VehichleRecord.<anon>.runtime_pos.<anon>.x */
    geSwap32((unsigned char *)p + 92);   /* VehichleRecord.<anon>.runtime_pos.<anon>.y */
    geSwap32((unsigned char *)p + 96);   /* VehichleRecord.<anon>.runtime_pos.<anon>.z */
    /* union VehichleRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 100);   /* VehichleRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 104);   /* VehichleRecord.<anon>.ptr_allocated_collisiondata_block */
    /* union VehichleRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 108);   /* VehichleRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 112);   /* VehichleRecord.<anon>.maxdamage */
    geSwap32((unsigned char *)p + 116);   /* VehichleRecord.<anon>.damage */
    geSwapUnion_VehichleRecord__anon__shadecol__anon__at120((unsigned char *)p + 120);  /* union: VehichleRecord.<anon>.shadecol.<anon> -- see the hook */
    geSwapUnion_VehichleRecord__anon__nextcol__anon__at124((unsigned char *)p + 124);  /* union: VehichleRecord.<anon>.nextcol.<anon> -- see the hook */
    geSwap32((unsigned char *)p + 128);   /* VehichleRecord.ailist */
    geSwap16((unsigned char *)p + 132);   /* VehichleRecord.aioffset */
    geSwap16((unsigned char *)p + 134);   /* VehichleRecord.aireturnlist */
    geSwap32((unsigned char *)p + 136);   /* VehichleRecord.speed */
    geSwap32((unsigned char *)p + 140);   /* VehichleRecord.wheelxrot */
    geSwap32((unsigned char *)p + 144);   /* VehichleRecord.wheelyrot */
    geSwap32((unsigned char *)p + 148);   /* VehichleRecord.speedaim */
    geSwap32((unsigned char *)p + 152);   /* VehichleRecord.speedtime60 */
    geSwap32((unsigned char *)p + 156);   /* VehichleRecord.turnrot60 */
    geSwap32((unsigned char *)p + 160);   /* VehichleRecord.roty */
    geSwap32((unsigned char *)p + 164);   /* VehichleRecord.path */
    geSwap32((unsigned char *)p + 168);   /* VehichleRecord.nextstep */
    geSwap32((unsigned char *)p + 172);   /* VehichleRecord.Sound */
}

/* AircraftRecord: 180 bytes on the N64 */
void geSwap_AircraftRecord(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* AircraftRecord.<anon>.<anon>.extrascale */
    geSwap16((unsigned char *)p + 4);   /* AircraftRecord.<anon>.obj */
    geSwap16((unsigned char *)p + 6);   /* AircraftRecord.<anon>.pad */
    geSwap32((unsigned char *)p + 8);   /* AircraftRecord.<anon>.flags */
    geSwap32((unsigned char *)p + 12);   /* AircraftRecord.<anon>.flags2 */
    geSwap32((unsigned char *)p + 16);   /* AircraftRecord.<anon>.prop */
    geSwap32((unsigned char *)p + 20);   /* AircraftRecord.<anon>.model */
    geSwapUnion_AircraftRecord__anon__mtx_at24((unsigned char *)p + 24);  /* union: AircraftRecord.<anon>.mtx -- see the hook */
    /* union AircraftRecord.<anon>.runtime_pos.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 88);   /* AircraftRecord.<anon>.runtime_pos.<anon>.x */
    geSwap32((unsigned char *)p + 92);   /* AircraftRecord.<anon>.runtime_pos.<anon>.y */
    geSwap32((unsigned char *)p + 96);   /* AircraftRecord.<anon>.runtime_pos.<anon>.z */
    /* union AircraftRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 100);   /* AircraftRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 104);   /* AircraftRecord.<anon>.ptr_allocated_collisiondata_block */
    /* union AircraftRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 108);   /* AircraftRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 112);   /* AircraftRecord.<anon>.maxdamage */
    geSwap32((unsigned char *)p + 116);   /* AircraftRecord.<anon>.damage */
    geSwapUnion_AircraftRecord__anon__shadecol__anon__at120((unsigned char *)p + 120);  /* union: AircraftRecord.<anon>.shadecol.<anon> -- see the hook */
    geSwapUnion_AircraftRecord__anon__nextcol__anon__at124((unsigned char *)p + 124);  /* union: AircraftRecord.<anon>.nextcol.<anon> -- see the hook */
    geSwap32((unsigned char *)p + 128);   /* AircraftRecord.ailist */
    geSwap16((unsigned char *)p + 132);   /* AircraftRecord.aioffset */
    geSwap16((unsigned char *)p + 134);   /* AircraftRecord.aireturnlist */
    geSwap32((unsigned char *)p + 136);   /* AircraftRecord.rotoryrot */
    geSwap32((unsigned char *)p + 140);   /* AircraftRecord.rotaryspeed */
    geSwap32((unsigned char *)p + 144);   /* AircraftRecord.rotaryspeedaim */
    geSwap32((unsigned char *)p + 148);   /* AircraftRecord.rotaryspeedtime */
    geSwap32((unsigned char *)p + 152);   /* AircraftRecord.speed */
    geSwap32((unsigned char *)p + 156);   /* AircraftRecord.speedaim */
    geSwap32((unsigned char *)p + 160);   /* AircraftRecord.speedtime60 */
    geSwap32((unsigned char *)p + 164);   /* AircraftRecord.yrot */
    geSwap32((unsigned char *)p + 168);   /* AircraftRecord.nextstep */
    geSwap32((unsigned char *)p + 172);   /* AircraftRecord.path */
    geSwap32((unsigned char *)p + 176);   /* AircraftRecord.Sound */
}

/* TankRecord: 224 bytes on the N64 */
void geSwap_TankRecord(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* TankRecord.<anon>.<anon>.extrascale */
    geSwap16((unsigned char *)p + 4);   /* TankRecord.<anon>.obj */
    geSwap16((unsigned char *)p + 6);   /* TankRecord.<anon>.pad */
    geSwap32((unsigned char *)p + 8);   /* TankRecord.<anon>.flags */
    geSwap32((unsigned char *)p + 12);   /* TankRecord.<anon>.flags2 */
    geSwap32((unsigned char *)p + 16);   /* TankRecord.<anon>.prop */
    geSwap32((unsigned char *)p + 20);   /* TankRecord.<anon>.model */
    geSwapUnion_TankRecord__anon__mtx_at24((unsigned char *)p + 24);  /* union: TankRecord.<anon>.mtx -- see the hook */
    /* union TankRecord.<anon>.runtime_pos.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 88);   /* TankRecord.<anon>.runtime_pos.<anon>.x */
    geSwap32((unsigned char *)p + 92);   /* TankRecord.<anon>.runtime_pos.<anon>.y */
    geSwap32((unsigned char *)p + 96);   /* TankRecord.<anon>.runtime_pos.<anon>.z */
    /* union TankRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 100);   /* TankRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 104);   /* TankRecord.<anon>.ptr_allocated_collisiondata_block */
    /* union TankRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 108);   /* TankRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 112);   /* TankRecord.<anon>.maxdamage */
    geSwap32((unsigned char *)p + 116);   /* TankRecord.<anon>.damage */
    geSwapUnion_TankRecord__anon__shadecol__anon__at120((unsigned char *)p + 120);  /* union: TankRecord.<anon>.shadecol.<anon> -- see the hook */
    geSwapUnion_TankRecord__anon__nextcol__anon__at124((unsigned char *)p + 124);  /* union: TankRecord.<anon>.nextcol.<anon> -- see the hook */
    geSwap32((unsigned char *)p + 128);   /* TankRecord.collision */
    /* union TankRecord.rect.<anon>: every arm swaps identically -- no ambiguity */
    /* union TankRecord.rect.<anon>[0].<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 132);   /* TankRecord.rect.<anon>[0].<anon>.x */
    geSwap32((unsigned char *)p + 136);   /* TankRecord.rect.<anon>[0].<anon>.y */
    /* union TankRecord.rect.<anon>[1].<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 140);   /* TankRecord.rect.<anon>[1].<anon>.x */
    geSwap32((unsigned char *)p + 144);   /* TankRecord.rect.<anon>[1].<anon>.y */
    /* union TankRecord.rect.<anon>[2].<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 148);   /* TankRecord.rect.<anon>[2].<anon>.x */
    geSwap32((unsigned char *)p + 152);   /* TankRecord.rect.<anon>[2].<anon>.y */
    /* union TankRecord.rect.<anon>[3].<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 156);   /* TankRecord.rect.<anon>[3].<anon>.x */
    geSwap32((unsigned char *)p + 160);   /* TankRecord.rect.<anon>[3].<anon>.y */
    geSwap32((unsigned char *)p + 164);   /* TankRecord.unkA4 */
    geSwap32((unsigned char *)p + 168);   /* TankRecord.unkA8 */
    geSwap32((unsigned char *)p + 172);   /* TankRecord.unkAC */
    geSwap32((unsigned char *)p + 176);   /* TankRecord.unkB0 */
    geSwap32((unsigned char *)p + 180);   /* TankRecord.unkB4 */
    geSwap32((unsigned char *)p + 184);   /* TankRecord.unkB8 */
    geSwap32((unsigned char *)p + 188);   /* TankRecord.unkBC */
    geSwap32((unsigned char *)p + 192);   /* TankRecord.unkC0 */
    geSwap32((unsigned char *)p + 196);   /* TankRecord.is_firing_tank */
    geSwap32((unsigned char *)p + 200);   /* TankRecord.turret_vertical_angle */
    geSwap32((unsigned char *)p + 204);   /* TankRecord.turret_orientation_angle */
    geSwap32((unsigned char *)p + 208);   /* TankRecord.unkD0 */
    geSwap32((unsigned char *)p + 212);   /* TankRecord.stan_y */
    geSwap32((unsigned char *)p + 216);   /* TankRecord.unkD8 */
    geSwap32((unsigned char *)p + 220);   /* TankRecord.tank_orientation_angle */
}

/* CutsceneRecord: 28 bytes on the N64 */
void geSwap_CutsceneRecord(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* CutsceneRecord.<anon>.extrascale */
    /* union CutsceneRecord.pos.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 4);   /* CutsceneRecord.pos.<anon>.x */
    geSwap32((unsigned char *)p + 8);   /* CutsceneRecord.pos.<anon>.y */
    geSwap32((unsigned char *)p + 12);   /* CutsceneRecord.pos.<anon>.z */
    geSwap32((unsigned char *)p + 16);   /* CutsceneRecord.theta */
    geSwap32((unsigned char *)p + 20);   /* CutsceneRecord.verta */
    geSwap32((unsigned char *)p + 24);   /* CutsceneRecord.pad */
}

/* SafeObjectRecord: 20 bytes on the N64 */
void geSwap_SafeObjectRecord(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* SafeObjectRecord.<anon>.extrascale */
    /* union SafeObjectRecord.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 4);   /* SafeObjectRecord.<anon> */
    /* union SafeObjectRecord.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 8);   /* SafeObjectRecord.<anon> */
    /* union SafeObjectRecord.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 12);   /* SafeObjectRecord.<anon> */
    geSwap32((unsigned char *)p + 16);   /* SafeObjectRecord.next */
}

/* AmmoCrateRecord: 132 bytes on the N64 */
void geSwap_AmmoCrateRecord(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* AmmoCrateRecord.<anon>.<anon>.extrascale */
    geSwap16((unsigned char *)p + 4);   /* AmmoCrateRecord.<anon>.obj */
    geSwap16((unsigned char *)p + 6);   /* AmmoCrateRecord.<anon>.pad */
    geSwap32((unsigned char *)p + 8);   /* AmmoCrateRecord.<anon>.flags */
    geSwap32((unsigned char *)p + 12);   /* AmmoCrateRecord.<anon>.flags2 */
    geSwap32((unsigned char *)p + 16);   /* AmmoCrateRecord.<anon>.prop */
    geSwap32((unsigned char *)p + 20);   /* AmmoCrateRecord.<anon>.model */
    geSwapUnion_AmmoCrateRecord__anon__mtx_at24((unsigned char *)p + 24);  /* union: AmmoCrateRecord.<anon>.mtx -- see the hook */
    /* union AmmoCrateRecord.<anon>.runtime_pos.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 88);   /* AmmoCrateRecord.<anon>.runtime_pos.<anon>.x */
    geSwap32((unsigned char *)p + 92);   /* AmmoCrateRecord.<anon>.runtime_pos.<anon>.y */
    geSwap32((unsigned char *)p + 96);   /* AmmoCrateRecord.<anon>.runtime_pos.<anon>.z */
    /* union AmmoCrateRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 100);   /* AmmoCrateRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 104);   /* AmmoCrateRecord.<anon>.ptr_allocated_collisiondata_block */
    /* union AmmoCrateRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 108);   /* AmmoCrateRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 112);   /* AmmoCrateRecord.<anon>.maxdamage */
    geSwap32((unsigned char *)p + 116);   /* AmmoCrateRecord.<anon>.damage */
    geSwapUnion_AmmoCrateRecord__anon__shadecol__anon__at120((unsigned char *)p + 120);  /* union: AmmoCrateRecord.<anon>.shadecol.<anon> -- see the hook */
    geSwapUnion_AmmoCrateRecord__anon__nextcol__anon__at124((unsigned char *)p + 124);  /* union: AmmoCrateRecord.<anon>.nextcol.<anon> -- see the hook */
    geSwap32((unsigned char *)p + 128);   /* AmmoCrateRecord.ammoType */
}

/* HatRecord: 128 bytes on the N64 */
void geSwap_HatRecord(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* HatRecord.<anon>.<anon>.extrascale */
    geSwap16((unsigned char *)p + 4);   /* HatRecord.<anon>.obj */
    geSwap16((unsigned char *)p + 6);   /* HatRecord.<anon>.pad */
    geSwap32((unsigned char *)p + 8);   /* HatRecord.<anon>.flags */
    geSwap32((unsigned char *)p + 12);   /* HatRecord.<anon>.flags2 */
    geSwap32((unsigned char *)p + 16);   /* HatRecord.<anon>.prop */
    geSwap32((unsigned char *)p + 20);   /* HatRecord.<anon>.model */
    geSwapUnion_HatRecord__anon__mtx_at24((unsigned char *)p + 24);  /* union: HatRecord.<anon>.mtx -- see the hook */
    /* union HatRecord.<anon>.runtime_pos.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 88);   /* HatRecord.<anon>.runtime_pos.<anon>.x */
    geSwap32((unsigned char *)p + 92);   /* HatRecord.<anon>.runtime_pos.<anon>.y */
    geSwap32((unsigned char *)p + 96);   /* HatRecord.<anon>.runtime_pos.<anon>.z */
    /* union HatRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 100);   /* HatRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 104);   /* HatRecord.<anon>.ptr_allocated_collisiondata_block */
    /* union HatRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 108);   /* HatRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 112);   /* HatRecord.<anon>.maxdamage */
    geSwap32((unsigned char *)p + 116);   /* HatRecord.<anon>.damage */
    geSwapUnion_HatRecord__anon__shadecol__anon__at120((unsigned char *)p + 120);  /* union: HatRecord.<anon>.shadecol.<anon> -- see the hook */
    geSwapUnion_HatRecord__anon__nextcol__anon__at124((unsigned char *)p + 124);  /* union: HatRecord.<anon>.nextcol.<anon> -- see the hook */
}

/* GlassRecord: 140 bytes on the N64 */
void geSwap_GlassRecord(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* GlassRecord.<anon>.<anon>.extrascale */
    geSwap16((unsigned char *)p + 4);   /* GlassRecord.<anon>.obj */
    geSwap16((unsigned char *)p + 6);   /* GlassRecord.<anon>.pad */
    geSwap32((unsigned char *)p + 8);   /* GlassRecord.<anon>.flags */
    geSwap32((unsigned char *)p + 12);   /* GlassRecord.<anon>.flags2 */
    geSwap32((unsigned char *)p + 16);   /* GlassRecord.<anon>.prop */
    geSwap32((unsigned char *)p + 20);   /* GlassRecord.<anon>.model */
    geSwapUnion_GlassRecord__anon__mtx_at24((unsigned char *)p + 24);  /* union: GlassRecord.<anon>.mtx -- see the hook */
    /* union GlassRecord.<anon>.runtime_pos.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 88);   /* GlassRecord.<anon>.runtime_pos.<anon>.x */
    geSwap32((unsigned char *)p + 92);   /* GlassRecord.<anon>.runtime_pos.<anon>.y */
    geSwap32((unsigned char *)p + 96);   /* GlassRecord.<anon>.runtime_pos.<anon>.z */
    /* union GlassRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 100);   /* GlassRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 104);   /* GlassRecord.<anon>.ptr_allocated_collisiondata_block */
    /* union GlassRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 108);   /* GlassRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 112);   /* GlassRecord.<anon>.maxdamage */
    geSwap32((unsigned char *)p + 116);   /* GlassRecord.<anon>.damage */
    geSwapUnion_GlassRecord__anon__shadecol__anon__at120((unsigned char *)p + 120);  /* union: GlassRecord.<anon>.shadecol.<anon> -- see the hook */
    geSwapUnion_GlassRecord__anon__nextcol__anon__at124((unsigned char *)p + 124);  /* union: GlassRecord.<anon>.nextcol.<anon> -- see the hook */
    /* union GlassRecord.normal.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 128);   /* GlassRecord.normal.<anon>.x */
    geSwap32((unsigned char *)p + 132);   /* GlassRecord.normal.<anon>.y */
    geSwap32((unsigned char *)p + 136);   /* GlassRecord.normal.<anon>.z */
}

/* SafeRecord: 140 bytes on the N64 */
void geSwap_SafeRecord(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* SafeRecord.<anon>.<anon>.extrascale */
    geSwap16((unsigned char *)p + 4);   /* SafeRecord.<anon>.obj */
    geSwap16((unsigned char *)p + 6);   /* SafeRecord.<anon>.pad */
    geSwap32((unsigned char *)p + 8);   /* SafeRecord.<anon>.flags */
    geSwap32((unsigned char *)p + 12);   /* SafeRecord.<anon>.flags2 */
    geSwap32((unsigned char *)p + 16);   /* SafeRecord.<anon>.prop */
    geSwap32((unsigned char *)p + 20);   /* SafeRecord.<anon>.model */
    geSwapUnion_SafeRecord__anon__mtx_at24((unsigned char *)p + 24);  /* union: SafeRecord.<anon>.mtx -- see the hook */
    /* union SafeRecord.<anon>.runtime_pos.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 88);   /* SafeRecord.<anon>.runtime_pos.<anon>.x */
    geSwap32((unsigned char *)p + 92);   /* SafeRecord.<anon>.runtime_pos.<anon>.y */
    geSwap32((unsigned char *)p + 96);   /* SafeRecord.<anon>.runtime_pos.<anon>.z */
    /* union SafeRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 100);   /* SafeRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 104);   /* SafeRecord.<anon>.ptr_allocated_collisiondata_block */
    /* union SafeRecord.<anon>.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 108);   /* SafeRecord.<anon>.<anon> */
    geSwap32((unsigned char *)p + 112);   /* SafeRecord.<anon>.maxdamage */
    geSwap32((unsigned char *)p + 116);   /* SafeRecord.<anon>.damage */
    geSwapUnion_SafeRecord__anon__shadecol__anon__at120((unsigned char *)p + 120);  /* union: SafeRecord.<anon>.shadecol.<anon> -- see the hook */
    geSwapUnion_SafeRecord__anon__nextcol__anon__at124((unsigned char *)p + 124);  /* union: SafeRecord.<anon>.nextcol.<anon> -- see the hook */
    /* union SafeRecord.normal.<anon>: every arm swaps identically -- no ambiguity */
    geSwap32((unsigned char *)p + 128);   /* SafeRecord.normal.<anon>.x */
    geSwap32((unsigned char *)p + 132);   /* SafeRecord.normal.<anon>.y */
    geSwap32((unsigned char *)p + 136);   /* SafeRecord.normal.<anon>.z */
}

/* GasReleasingRecord: 6 bytes on the N64 */
void geSwap_GasReleasingRecord(void *p)
{
    geSwap16((unsigned char *)p + 0);   /* GasReleasingRecord.<anon>.extrascale */
    geSwap16((unsigned char *)p + 4);   /* GasReleasingRecord.unk4 */
}

/* objective_entry: 16 bytes on the N64 */
void geSwap_objective_entry(void *p)
{
    geSwap32((unsigned char *)p + 0);   /* objective_entry.id */
    geSwap32((unsigned char *)p + 4);   /* objective_entry.menu */
    geSwap16((unsigned char *)p + 8);   /* objective_entry.reserved */
    geSwap16((unsigned char *)p + 10);   /* objective_entry.text */
    geSwap16((unsigned char *)p + 12);   /* objective_entry.unkC */
}

/* criteria_roomentered: 16 bytes on the N64 */
void geSwap_criteria_roomentered(void *p)
{
    geSwap32((unsigned char *)p + 0);   /* criteria_roomentered.unk00 */
    geSwap32((unsigned char *)p + 4);   /* criteria_roomentered.pad */
    geSwap32((unsigned char *)p + 8);   /* criteria_roomentered.status */
    geSwap32((unsigned char *)p + 12);   /* criteria_roomentered.next */
}

/* criteria_deposit: 20 bytes on the N64 */
void geSwap_criteria_deposit(void *p)
{
    geSwap32((unsigned char *)p + 0);   /* criteria_deposit.unk00 */
    geSwap32((unsigned char *)p + 4);   /* criteria_deposit.weaponnum */
    geSwap32((unsigned char *)p + 8);   /* criteria_deposit.padid */
    geSwap32((unsigned char *)p + 12);   /* criteria_deposit.flag */
    geSwap32((unsigned char *)p + 16);   /* criteria_deposit.next */
}

/* criteria_picture: 16 bytes on the N64 */
void geSwap_criteria_picture(void *p)
{
    geSwap32((unsigned char *)p + 0);   /* criteria_picture.unk00 */
    geSwap32((unsigned char *)p + 4);   /* criteria_picture.tag_id */
    geSwap32((unsigned char *)p + 8);   /* criteria_picture.flag */
    geSwap32((unsigned char *)p + 12);   /* criteria_picture.next */
}

/* setup_objective_text: 16 bytes on the N64 */
void geSwap_setup_objective_text(void *p)
{
    geSwap32((unsigned char *)p + 0);   /* setup_objective_text.unk00 */
    geSwap32((unsigned char *)p + 4);   /* setup_objective_text.unk04 */
    geSwap32((unsigned char *)p + 8);   /* setup_objective_text.unk08 */
    geSwap32((unsigned char *)p + 12);   /* setup_objective_text.next */
}

