#!/usr/bin/env python3
"""
check_struct_layout.py -- find structs whose host layout does not match the N64's.

WHY

Three of these have been found the expensive way, one crash at a time:

    OSThread          448 on the N64, 472 in the shim -- osCreateThread wrote 24
                      bytes past the end of the caller's static
    struct huft       8 vs 16 -- the Huffman pool overran a stack array by 2x and
                      HUNG rather than crashed
    ModelAnimation    two 4-byte pointer fields became 8, moving every field
                      past 0x08; its instances are cartridge data

The common cause is a pointer member. A pointer is 4 bytes on the N64 and 8 on
the host, so any struct containing one changes size and shifts every member
after it. That matters whenever the struct describes data the port did not lay
out itself -- anything romCopy'd from the cartridge, and anything the game and
the shim both declare.

Three found by crashing is a pattern, not a run of bad luck. This turns the rest
into a list.

HOW

The oracle is a 32-bit compile of the same headers. On i386 a pointer is 4 bytes,
which is the property that matters here, so the sizes it reports are the N64's
for every struct whose members are integers, floats and pointers.

Rather than link and run a 32-bit binary -- which needs a multilib runtime that
is often not installed -- this measures sizes natively, writes them into
`_Static_assert`s, and compiles THOSE for 32-bit. Every assertion that fails
names a struct whose layout differs, and the compiler does the reporting.

KNOWN LIMIT, STATED RATHER THAN HIDDEN

i386 aligns `double` and `long long` to 4 bytes; MIPS o32 aligns them to 8. A
struct whose only difference is an f64/s64 member can therefore be reported as
matching when it does not, or vice versa. Those are flagged separately rather
than silently trusted. Pointers -- the actual cause of all three known bugs --
are exact.

Usage:
    check_struct_layout.py --decomp <root> [--hostcompat <dir>] [--header ...]
"""
import argparse, os, re, subprocess, sys, tempfile

DEFAULT_HEADERS = ["src/bondtypes.h"]

# A minimal stdint.h so the 32-bit compile does not need glibc's multilib
# headers, which is the one thing that stops -m32 working on a stock container.
STDINT_SHIM = """/* generated by tools/check_struct_layout.py -- 32-bit probe only */
#ifndef _STDINT_H
#define _STDINT_H
typedef signed char        int8_t;
typedef unsigned char      uint8_t;
typedef short              int16_t;
typedef unsigned short     uint16_t;
typedef int                int32_t;
typedef unsigned int       uint32_t;
typedef long long          int64_t;
typedef unsigned long long uint64_t;
typedef long               intptr_t;
typedef unsigned long      uintptr_t;
#endif
"""


def struct_names(paths):
    """Every named struct/typedef we can refer to in a sizeof()."""
    names = []
    for p in paths:
        txt = open(p, errors="ignore").read()
        # typedef struct [Tag] { ... } Name;
        for m in re.finditer(r'typedef\s+struct\s+(\w+)?\s*\{.*?\}\s*(\w+)\s*;', txt, re.S):
            names.append(m.group(2))
        # struct Tag { ... };   (no typedef)
        for m in re.finditer(r'(?<!typedef )struct\s+(\w+)\s*\{.*?\}\s*;', txt, re.S):
            names.append("struct " + m.group(1))
    seen, out = set(), []
    for n in names:
        if n not in seen:
            seen.add(n)
            out.append(n)
    return out


def has_pointer_member(paths, name):
    bare = name.replace("struct ", "")
    for p in paths:
        txt = open(p, errors="ignore").read()
        for m in re.finditer(r'struct\s+' + re.escape(bare) + r'\s*\{(.*?)\}', txt, re.S):
            if re.search(r'\*\s*\**\s*\w+\s*(\[|;)', m.group(1)):
                return True
        for m in re.finditer(r'typedef\s+struct\s+\w*\s*\{(.*?)\}\s*' + re.escape(bare) + r'\s*;',
                             txt, re.S):
            if re.search(r'\*\s*\**\s*\w+\s*(\[|;)', m.group(1)):
                return True
    return False


def has_wide_scalar(paths, name):
    """f64/s64/double/long long -- the case where i386 and MIPS o32 disagree."""
    bare = name.replace("struct ", "")
    pat = re.compile(r'\b(f64|s64|u64|double|long\s+long)\b')
    for p in paths:
        txt = open(p, errors="ignore").read()
        for m in re.finditer(r'struct\s+' + re.escape(bare) + r'\s*\{(.*?)\}', txt, re.S):
            if pat.search(m.group(1)):
                return True
    return False


def documented_offsets(paths):
    """member -> documented offset, from `// 0xNN` comments. Cross-check only."""
    out = {}
    for p in paths:
        cur = None
        for line in open(p, errors="ignore"):
            m = re.search(r'struct\s+(\w+)\s*$|struct\s+(\w+)\s*\{', line)
            if m:
                cur = m.group(1) or m.group(2)
            if cur:
                d = re.search(r'(\w+)\s*(?:\[[^\]]*\])?\s*;\s*(?://|/\*)\s*0x([0-9A-Fa-f]+)', line)
                if d:
                    out.setdefault(cur, {})[d.group(1)] = int(d.group(2), 16)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--decomp", required=True)
    ap.add_argument("--hostcompat", default="hostcompat")
    ap.add_argument("--header", action="append", default=None)
    ap.add_argument("--cc", default="clang",
                    help="compiler for both probes. clang by default: the port's\n                          cartridge structs use __ptr32, which GCC does not have.")
    a = ap.parse_args()

    D = a.decomp
    headers = a.header or DEFAULT_HEADERS
    paths = [os.path.join(D, h) for h in headers]
    for p in paths:
        if not os.path.exists(p):
            sys.exit(f"no such header: {p}")

    inc = " ".join("-I " + x for x in [
        a.hostcompat, D, D + "/include", D + "/include/PR", D + "/src",
        D + "/src/game", D + "/src/inflate", D + "/src/libultra"])
    dfn = ("-D_LANGUAGE_C -DGE_HOST_PORT -DVERSION_US -DLANG_US -DREFRESH_NTSC "
           "-DLEFTOVERDEBUG -DLEFTOVERSPECTRUM -DBUGFIX_R0 -DBYTEMATCH")
    incs = "\n".join(f'#include <{h.split("/")[-1]}>' for h in headers)

    names = struct_names(paths)
    print(f"{len(names)} named structs in {', '.join(headers)}")

    tmp = tempfile.mkdtemp(prefix="ge_layout_")
    shim = os.path.join(tmp, "shim")
    os.makedirs(shim, exist_ok=True)
    open(os.path.join(shim, "stdint.h"), "w").write(STDINT_SHIM)

    # ---- 1. host sizes, measured by running a native build ------------------
    #
    # The name scrape is regex over C, so it picks up nested struct tags and the
    # occasional member name. Rather than make the regex cleverer -- which is how
    # you get a parser that is wrong in quieter ways -- let the COMPILER decide
    # what is a real type: probe, drop whatever it rejects, retry. It converges
    # in a couple of rounds and cannot silently keep a bogus name.
    #
    src = os.path.join(tmp, "sizes.c")
    exe = os.path.join(tmp, "sizes")
    dropped = []
    for _round in range(6):
        with open(src, "w") as f:
            f.write("#include <ultra64.h>\n" + incs + "\n#include <stdio.h>\n")
            f.write("int main(void){\n")
            for n in names:
                f.write(f'    printf("%s %zu\\n", "{n}", sizeof({n}));\n')
            f.write("    return 0;\n}\n")
        r = subprocess.run(f"{a.cc} -w -std=gnu99 -fms-extensions {inc} {dfn} {src} -o {exe}",
                           shell=True, capture_output=True, text=True)
        if r.returncode == 0:
            break
        # gcc and clang word these differently and quote with different
        # characters (gcc uses U+2018/U+2019). Match both rather than pick one:
        # the tool is meant to run under either compiler.
        q = "['‘’]"
        pats = [
            q + r"(\w+)" + q + r" undeclared",                 # gcc
            r"use of undeclared identifier " + q + r"(\w+)" + q,  # clang
            r"incomplete type " + q + r"struct (\w+)" + q,
            r"incomplete type " + q + r"(\w+)" + q,
            r"unknown type name " + q + r"(\w+)" + q,
        ]
        bad_names = set()
        for pat in pats:
            bad_names |= set(re.findall(pat, r.stderr))
        if not bad_names:
            sys.exit("host probe failed:\n" + r.stderr[:2000])
        before = len(names)
        names = [n for n in names
                 if n not in bad_names and n.replace("struct ", "") not in bad_names]
        dropped += sorted(bad_names)
        if len(names) == before:
            sys.exit("host probe failed and made no progress:\n" + r.stderr[:2000])
    else:
        sys.exit("host probe did not converge")
    if dropped:
        print(f"  ({len(dropped)} scraped names were not types and were dropped)")
    host = {}
    for line in subprocess.run(exe, capture_output=True, text=True).stdout.splitlines():
        k, v = line.rsplit(" ", 1)
        host[k] = int(v)
    print(f"measured {len(host)} host sizes")

    # ---- 2. assert them under -m32; failures name the mismatches ------------
    src32 = os.path.join(tmp, "assert32.c")
    with open(src32, "w") as f:
        f.write("#include <ultra64.h>\n" + incs + "\n")
        for n, sz in host.items():
            tag = n.replace("struct ", "S_").replace(" ", "_")
            f.write(f'_Static_assert(sizeof({n}) == {sz}, "GELAYOUT {n}");\n')
    # -ferror-limit=0 / -fmax-errors=0 are LOAD-BEARING. clang stops after 20
    # errors by default, so without this the report is silently truncated and
    # reads as "only 38 structs differ" when the real answer is larger. A tool
    # that under-reports is worse than no tool.
    r = subprocess.run(
        f"{a.cc} -m32 -c -w -std=gnu99 -fms-extensions -ferror-limit=0 -fmax-errors=0 "
        f"-I {shim} {inc} {dfn} {src32} "
        f"-o {os.path.join(tmp,'a32.o')}",
        shell=True, capture_output=True, text=True)

    bad = []
    for m in re.finditer(r'GELAYOUT ([^"]+)"', r.stderr):
        bad.append(m.group(1))
    if r.returncode != 0 and not bad:
        sys.exit("32-bit probe failed for a reason other than the assertions:\n"
                 + r.stderr[:2000])

    # ---- 3. report ---------------------------------------------------------
    docs = documented_offsets(paths)
    print()
    if not bad:
        print("no struct changes size between 32-bit and 64-bit. Nothing to fix.")
        return 0

    ptr, wide, other = [], [], []
    for n in sorted(set(bad)):
        if has_pointer_member(paths, n):
            ptr.append(n)
        elif has_wide_scalar(paths, n):
            wide.append(n)
        else:
            other.append(n)

    print(f"{len(set(bad))} structs have a different layout on the host.\n")
    print(f"--- {len(ptr)} contain a POINTER member. These are the real ones: a")
    print("    pointer is 4 bytes on the N64 and 8 here, so every member after")
    print("    it moves. Any of these that describes cartridge data, or that the")
    print("    shim also declares, is a live bug.")
    for n in ptr:
        note = ""
        bare = n.replace("struct ", "")
        if bare in docs:
            note = f"   [{len(docs[bare])} documented offsets to check]"
        print(f"      {n:38} host sizeof {host[n]}{note}")

    if wide:
        print(f"\n--- {len(wide)} differ but contain f64/s64 and NO pointer.")
        print("    i386 aligns those to 4 and MIPS o32 to 8, so the 32-bit probe")
        print("    is not authoritative here. Check by hand rather than trusting")
        print("    either answer.")
        for n in wide:
            print(f"      {n:38} host sizeof {host[n]}")

    if other:
        print(f"\n--- {len(other)} differ for some other reason. Worth a look.")
        for n in other:
            print(f"      {n:38} host sizeof {host[n]}")
    return 1


if __name__ == "__main__":
    sys.exit(main())
