#!/usr/bin/env bash
# check_abi.sh — print the sizes and offsets of every type the game and the shim
# BOTH see, from the decomp's own headers.
#
# These cannot be compared inside one translation unit: both sides define the
# same type names, so they can never be included together. That is precisely why
# a 448-vs-472 disagreement on OSThread went unnoticed until it corrupted memory
# and surfaced as a fault in swapcontext().
#
# Run this after touching src/ultra/os.h and paste the numbers into
# tests/test_abi_layout.cpp.
#
# Usage: tools/check_abi.sh <decomp-root>
set -u
REPO="${1:?usage: check_abi.sh <decomp-root>}"
HERE="$(cd "$(dirname "$0")/.." && pwd)"

cat > /tmp/ge_abi_probe.c <<'PROBE'
#include <stdio.h>
#include <ultra64.h>
#define SZ(t)     printf("    expect(\"sizeof(" #t ")\", sizeof(" #t "), %zu);\n", sizeof(t))
#define OFF(t, m) printf("    expect(\"offsetof(" #t ", " #m ")\", offsetof(" #t ", " #m "), %zu);\n", \
                         (size_t)__builtin_offsetof(t, m))
int main(void) {
    SZ(OSThread);  OFF(OSThread, context);
    SZ(__OSThreadContext);
    SZ(OSMesgQueue);
    SZ(OSTimer);
    SZ(OSTask);
    SZ(OSContPad);
    SZ(OSViMode);
    return 0;
}
PROBE

cc -w -std=gnu99 -D_LANGUAGE_C -DGE_HOST_PORT -DVERSION_US -DLANG_US \
   -DREFRESH_NTSC -DBUGFIX_R0 -DBYTEMATCH \
   -I "$HERE/hostcompat" -I "$HERE/src/host" -I "$REPO" -I "$REPO/include" \
   -I "$REPO/include/PR" -I "$REPO/src" \
   /tmp/ge_abi_probe.c -o /tmp/ge_abi_probe || exit 1

echo "// Generated by tools/check_abi.sh from the decomp's own headers."
/tmp/ge_abi_probe
