#!/usr/bin/env python3
"""
extract_segments.py -- build the host segment table from a linked N64 map file.

WHY THIS EXISTS

The game reaches its own ROM layout through linker-defined symbols:

    romCopy(dst, &_animation_dataSegmentRomStart, size);
    inflate_size = (u32)&_inflateSegmentRomStart - (u32)&_codeSegmentRomStart;

On N64 these are absolute link-time constants: ROM byte offsets and RDRAM
virtual addresses. A host toolchain cannot give an ordinary symbol a chosen
address -- and on Windows there is no portable way to define an absolute symbol
at all -- so the port cannot reproduce them as symbols. It needs their VALUES.

Those values are only known after linking, so they cannot be derived from
ge007.ld alone. But they are FIXED for a given ROM version: every US cartridge
has the same layout. So the table is extracted once per version and shipped as
data, keyed by the ROM's SHA1.

Usage:
    tools/extract_segments.py <ge007.u.map> <sha1-of-rom> > hostcompat/ge_segments.h
"""
import re, sys

def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    mapfile, sha1 = sys.argv[1], sys.argv[2]

    # ld map lines come in two shapes, and missing the second silently drops
    # more than half the table (16 of 39 on the US build):
    #
    #     0x003b4450   _instrumentsctlSegmentRomStart
    #     0x00001050   _codeSegmentRomStart = _startSegmentRomEnd
    #
    # The second is a PROVIDE/assignment; ld prints the resolved value on the
    # left and the defining expression on the right. The value is what matters,
    # so accept anything after the name.
    pat = re.compile(r'^\s+0x([0-9a-fA-F]+)\s+(_?[A-Za-z0-9_]*Segment'
                     r'(?:RomStart|RomEnd|Start|End|VaddrStart|VaddrEnd))'
                     r'(?:\s*=.*)?\s*$')
    syms = {}
    with open(mapfile) as fh:
        for line in fh:
            m = pat.match(line)
            if m:
                addr, name = int(m.group(1), 16), m.group(2)
                # A symbol should not appear twice with different values.
                if name in syms and syms[name] != addr:
                    print(f"warning: {name} appears as 0x{syms[name]:08X} and "
                          f"0x{addr:08X}", file=sys.stderr)
                syms[name] = addr

    if not syms:
        sys.exit(f"{mapfile}: no segment symbols found -- is this an ld map?")

    # get_*Segment*() are FUNCTIONS, not linker constants: src/boot.s defines
    # five two-instruction accessors that just return the corresponding symbol.
    # Their "addresses" are code addresses in the 0x70000000 TLB region, so
    # leaving them in the table produces entries that look like wild ROM offsets.
    # They belong in ge_segments.c as real functions instead.
    funcs = {k: v for k, v in syms.items() if k.startswith("get_")}
    syms  = {k: v for k, v in syms.items() if not k.startswith("get_")}

    # Validate what is genuinely checkable. Not the virtual addresses: GoldenEye
    # TLB-maps several segments, so 0x70000000 and 0x7F000000 are expected and a
    # "must be in RDRAM" check only produces false alarms.
    problems = []
    for name in sorted(syms):
        if name.endswith("RomStart"):
            end = name[: -len("RomStart")] + "RomEnd"
            if end in syms and syms[end] < syms[name]:
                problems.append(f"{name} 0x{syms[name]:X} > {end} 0x{syms[end]:X}")
    for p in problems:
        print(f"warning: reversed range: {p}", file=sys.stderr)

    out = sys.stdout
    out.write(f"""/*
 * ge_segments.h -- GENERATED by tools/extract_segments.py. Do not edit.
 *
 * ROM layout constants for one specific ROM version:
 *   SHA1 {sha1}
 *
 * These are the values of the linker-defined *Segment* symbols. On N64 they are
 * absolute link-time constants; a host toolchain cannot give a symbol a chosen
 * address, so the port uses the values directly. See the tool's docstring.
 *
 * {len(syms)} symbols.
 */
#ifndef GE_SEGMENTS_H
#define GE_SEGMENTS_H

#define GE_ROM_SHA1 "{sha1}"

""")
    width = max(len(n) for n in syms)
    for name in sorted(syms):
        out.write(f"#define GE_SEG_{name:<{width}} 0x{syms[name]:08X}u\n")
    if funcs:
        out.write("\n/*\n"
                  " * src/boot.s also defines these as two-instruction accessor\n"
                  " * FUNCTIONS returning the symbol above. src/ultra/segments.c\n"
                  " * implements them for the host.\n"
                  " */\n")
        for name in sorted(funcs):
            out.write(f"/*   {name}() */\n")
    out.write("\n#endif /* GE_SEGMENTS_H */\n")
    print(f"{len(syms)} segment constants, {len(funcs)} accessor functions",
          file=sys.stderr)

if __name__ == "__main__":
    main()
