#!/usr/bin/env python3
"""
gen_ucode_blobs.py -- emit the RSP microcode blobs as C, from the decomp's own
extracted binaries.

WHY

src/gspboot.s and friends are just labels around `.incbin "bin/gspboot.text.bin"`.
Those .bin files are produced by the decomp's extraction step from the user's
own cartridge dump, so generating C from them ships no game data -- the same
rule the rest of this project follows.

The port does not EXECUTE this microcode; the display-list interpreter replaces
it. But the bytes still matter, for two reasons:

  1. The game puts these pointers and sizes into every OSTask it builds.
  2. RT64 identifies which microcode a task is running by hashing the text
     (XXH3-64). Hand it a placeholder and it either fails to recognise gsp3D or,
     worse, matches some other game's ucode and renders with the wrong
     semantics.

WHY A HEADER OF MACROS RATHER THAN PLAIN ARRAYS

The game reads the END labels too:

    task->t.ucode_boot_size = (s32)rspbootTextEnd - (s32)rspbootTextStart;

In assembly `rspbootTextEnd` is simply the next address after the blob. C cannot
place one array's symbol at another array's end, so the End names become macros
pointing one past the array -- and the decomp's `extern` declarations are
guarded, exactly as the segment symbols are.

Usage:
    tools/gen_ucode_blobs.py <decomp-root> <out.c> <out.h>
"""
import os, sys

# label prefix -> (text file, data file). Names come from the .s files.
BLOBS = [
    ("gsp3D",    "bin/gspboot.text.bin", "bin/gspboot.data.bin"),
    ("aspMain",  "bin/aspboot.text.bin", "bin/aspboot.data.bin"),
    ("rspboot",  "bin/rspboot.text.bin", None),
]

def emit_array(out, cname, blob):
    out.write(f"\n/* {len(blob)} bytes */\n")
    out.write(f"long long int {cname}[{(len(blob) + 7) // 8}] "
              "__attribute__((aligned(8))) = {\n")
    # Pack big-endian, the way the RSP reads it and the way .incbin laid it out.
    for i in range(0, len(blob), 8):
        chunk = blob[i:i + 8].ljust(8, b"\x00")
        out.write(f"    0x{int.from_bytes(chunk, 'big'):016X}LL,\n")
    out.write("};\n")

def main():
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    root, out_c, out_h = sys.argv[1], sys.argv[2], sys.argv[3]

    found = []
    for label, textf, dataf in BLOBS:
        for kind, path in (("Text", textf), ("Data", dataf)):
            if path is None:
                continue
            full = os.path.join(root, path)
            if not os.path.exists(full):
                print(f"warning: {path} missing -- run the decomp's extraction "
                      f"step first", file=sys.stderr)
                continue
            with open(full, "rb") as fh:
                found.append((label, kind, path, fh.read()))

    if not found:
        sys.exit("no microcode binaries found; nothing to generate")

    with open(out_c, "w") as c:
        c.write("/*\n * ucode_blobs.c -- GENERATED by tools/gen_ucode_blobs.py."
                " Do not edit.\n *\n * The RSP microcode, from the user's own"
                " extracted ROM data. See the\n * generator's docstring for why"
                " the bytes have to be real.\n */\n\n"
                '#include "ge_ucode.h"\n')
        for label, kind, path, blob in found:
            c.write(f"\n/* {path} */")
            emit_array(c, f"ge_{label}{kind}", blob)

    with open(out_h, "w") as h:
        h.write("""/*
 * ge_ucode.h -- GENERATED by tools/gen_ucode_blobs.py. Do not edit.
 *
 * Maps the decomp's assembly labels onto the generated arrays. The *End names
 * are macros because C cannot place a symbol at another array's end; the
 * matching `extern` declarations in src/game/rsp.c are guarded for the host.
 */
#ifndef GE_UCODE_H
#define GE_UCODE_H

#ifdef __cplusplus
extern "C" {
#endif

""")
        for label, kind, path, blob in found:
            qwords = (len(blob) + 7) // 8
            h.write(f"extern long long int ge_{label}{kind}[{qwords}];\n")
            h.write(f"#define {label}{kind}Start (ge_{label}{kind})\n")
            h.write(f"#define {label}{kind}End   (ge_{label}{kind} + {qwords})\n")
            h.write(f"#define GE_{label.upper()}_{kind.upper()}_BYTES {len(blob)}\n\n")
        h.write("#ifdef __cplusplus\n}\n#endif\n\n#endif /* GE_UCODE_H */\n")

    print(f"{len(found)} microcode blobs generated", file=sys.stderr)

if __name__ == "__main__":
    main()
